// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccountProject = "account_project"

// AccountProject mapped from table <account_project>
type AccountProject struct {
	ID          uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AccountID   uint32 `gorm:"column:account_id;not null" json:"account_id"`
	Name        string `gorm:"column:name;not null;comment:项目名称" json:"name"`                  // 项目名称
	Role        string `gorm:"column:role;not null;comment:角色" json:"role"`                    // 角色
	StartTime   int64  `gorm:"column:start_time;not null;comment:项目时间 - 开始" json:"start_time"` // 项目时间 - 开始
	EndTime     int64  `gorm:"column:end_time;not null;comment:项目时间-结束" json:"end_time"`       // 项目时间-结束
	Description string `gorm:"column:description;not null;comment:描述" json:"description"`      // 描述
	Performance string `gorm:"column:performance;not null;comment:业绩" json:"performance"`      // 业绩
	Link        string `gorm:"column:link;not null;comment:项目连接" json:"link"`                  // 项目连接
	CreatedTime int64  `gorm:"column:created_time;not null;comment:创建时间" json:"created_time"`  // 创建时间
	UpdatedTime int64  `gorm:"column:updated_time;not null;comment:更新时间" json:"updated_time"`  // 更新时间
}

// TableName AccountProject's table name
func (*AccountProject) TableName() string {
	return TableNameAccountProject
}
