// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccountApplyResumeAuth = "account_apply_resume_auth"

// AccountApplyResumeAuth mapped from table <account_apply_resume_auth>
type AccountApplyResumeAuth struct {
	ID               uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AccountApplyID   uint32 `gorm:"column:account_apply_id;not null" json:"account_apply_id"`
	RequestAccountID uint32 `gorm:"column:request_account_id;not null" json:"request_account_id"`
	AuthState        uint32 `gorm:"column:auth_state;not null;comment:0 未处理 1 通过 其他拒绝" json:"auth_state"` // 0 未处理 1 通过 其他拒绝
	CreatedTime      int64  `gorm:"column:created_time;not null;comment:创建时间" json:"created_time"`        // 创建时间
	UpdatedTime      int64  `gorm:"column:updated_time;not null;comment:更新时间" json:"updated_time"`        // 更新时间
	Status           uint32 `gorm:"column:status;not null" json:"status"`
}

// TableName AccountApplyResumeAuth's table name
func (*AccountApplyResumeAuth) TableName() string {
	return TableNameAccountApplyResumeAuth
}
