// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccountHelp = "account_help"

// AccountHelp mapped from table <account_help>
type AccountHelp struct {
	ID              uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AccountApplyID  uint32 `gorm:"column:account_apply_id;not null;comment:被协助者求职id" json:"account_apply_id"` // 被协助者求职id
	HelperAccountID uint32 `gorm:"column:helper_account_id;not null;comment:协助人ID" json:"helper_account_id"`  // 协助人ID
	Company         string `gorm:"column:company;not null;comment:公司" json:"company"`                         // 公司
	Position        string `gorm:"column:position;not null;comment:职位" json:"position"`                       // 职位
	HelpPlan        string `gorm:"column:help_plan;not null" json:"help_plan"`
	CreatedTime     int64  `gorm:"column:created_time;not null;comment:创建时间" json:"created_time"` // 创建时间
	UpdatedTime     int64  `gorm:"column:updated_time;not null;comment:更新时间" json:"updated_time"` // 更新时间
}

// TableName AccountHelp's table name
func (*AccountHelp) TableName() string {
	return TableNameAccountHelp
}
