// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccountApply = "account_apply"

// AccountApply mapped from table <account_apply>
type AccountApply struct {
	ID                  uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AccountID           uint32 `gorm:"column:account_id;not null;comment:用户id" json:"account_id"` // 用户id
	IsPublic            int32  `gorm:"column:is_public;not null;comment:是否公开" json:"is_public"`   // 是否公开
	IsFirst             int32  `gorm:"column:is_first;not null;comment:是否优先" json:"is_first"`     // 是否优先
	CurrentState        string `gorm:"column:current_state;not null" json:"current_state"`
	CurrentCity         string `gorm:"column:current_city;not null" json:"current_city"`
	CurrentIndustry     string `gorm:"column:current_industry;not null" json:"current_industry"`
	CurrentCompany      string `gorm:"column:current_company;not null" json:"current_company"`
	CurrentPositionTag  string `gorm:"column:current_position_tag;not null;comment:当前职位类别" json:"current_position_tag"` // 当前职位类别
	CurrentPosition     string `gorm:"column:current_position;not null" json:"current_position"`
	DestCity            string `gorm:"column:dest_city;not null" json:"dest_city"`
	DestIndustry        string `gorm:"column:dest_industry;not null;comment:期望行业" json:"dest_industry"` // 期望行业
	DestCompany         string `gorm:"column:dest_company;not null" json:"dest_company"`
	DestPositionTag     string `gorm:"column:dest_position_tag;not null;comment:期望职位类别" json:"dest_position_tag"` // 期望职位类别
	DestPosition        string `gorm:"column:dest_position;not null" json:"dest_position"`
	DestSalary          string `gorm:"column:dest_salary;not null;comment:目标薪资" json:"dest_salary"` // 目标薪资
	Education           string `gorm:"column:education;not null" json:"education"`
	University          string `gorm:"column:university;not null" json:"university"`
	Description         string `gorm:"column:description;not null" json:"description"`
	Contact             string `gorm:"column:contact;not null;comment:联系方式" json:"contact"`                                   // 联系方式
	HelpReward          uint32 `gorm:"column:help_reward;not null;comment:协助奖金" json:"help_reward"`                           // 协助奖金
	HelpRewardToC       uint32 `gorm:"column:help_reward_to_c;not null;comment:协助奖金显示" json:"help_reward_to_c"`               // 协助奖金显示
	IsHelpRewardVisible uint32 `gorm:"column:is_help_reward_visible;not null;comment:协助奖金是否显示" json:"is_help_reward_visible"` // 协助奖金是否显示
	CreatedTime         int64  `gorm:"column:created_time;not null;comment:创建时间" json:"created_time"`                         // 创建时间
	UpdatedTime         int64  `gorm:"column:updated_time;not null;comment:更新时间" json:"updated_time"`                         // 更新时间
	Status              int32  `gorm:"column:status;not null;comment:求职状态" json:"status"`                                     // 求职状态
}

// TableName AccountApply's table name
func (*AccountApply) TableName() string {
	return TableNameAccountApply
}
