// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccountEducation = "account_education"

// AccountEducation mapped from table <account_education>
type AccountEducation struct {
	ID          uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AccountID   uint32 `gorm:"column:account_id;not null" json:"account_id"`
	Name        string `gorm:"column:name;not null;comment:学校名称" json:"name"`                  // 学校名称
	Degree      string `gorm:"column:degree;not null;comment:学历" json:"degree"`                // 学历
	Profession  string `gorm:"column:profession;not null;comment:专业" json:"profession"`        // 专业
	StartTime   int64  `gorm:"column:start_time;not null;comment:在职时间 - 开始" json:"start_time"` // 在职时间 - 开始
	EndTime     int64  `gorm:"column:end_time;not null;comment:在职时间-结束" json:"end_time"`       // 在职时间-结束
	Experience  string `gorm:"column:experience;not null;comment:经历" json:"experience"`        // 经历
	CreatedTime int64  `gorm:"column:created_time;not null;comment:创建时间" json:"created_time"`  // 创建时间
	UpdatedTime int64  `gorm:"column:updated_time;not null;comment:更新时间" json:"updated_time"`  // 更新时间
}

// TableName AccountEducation's table name
func (*AccountEducation) TableName() string {
	return TableNameAccountEducation
}
