// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAdmin = "admin"

// Admin mapped from table <admin>
type Admin struct {
	ID            uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name          string `gorm:"column:name;not null" json:"name"`
	Password      string `gorm:"column:password;not null" json:"password"`
	Type          int32  `gorm:"column:type;comment:0=总账户、1=企业账户、2=HR账户、3=特别企业账户" json:"type"` // 0=总账户、1=企业账户、2=HR账户、3=特别企业账户
	FatherAdminID int32  `gorm:"column:father_admin_id" json:"father_admin_id"`
	CountPassage  int32  `gorm:"column:count_passage;not null" json:"count_passage"`
	CountApply    int32  `gorm:"column:count_apply;not null" json:"count_apply"`
	CountRelay    int32  `gorm:"column:count_relay;not null" json:"count_relay"`
	Status        int32  `gorm:"column:status;not null;comment:0、正常，1、审核中，2、停用" json:"status"` // 0、正常，1、审核中，2、停用
	CompanyID     int32  `gorm:"column:company_id" json:"company_id"`
	Score         int32  `gorm:"column:score;not null;comment:积分" json:"score"` // 积分
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
