// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameApply = "apply"

// Apply mapped from table <apply>
type Apply struct {
	ID           uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ConnectionID uint32 `gorm:"column:connection_id" json:"connection_id"`
	Name         string `gorm:"column:name" json:"name"`
	Phone        string `gorm:"column:phone" json:"phone"`
	Email        string `gorm:"column:email" json:"email"`
	WechatID     string `gorm:"column:wechat_id;comment:微信号" json:"wechat_id"` // 微信号
	Position     string `gorm:"column:position" json:"position"`
	PassageID    int32  `gorm:"column:passage_id" json:"passage_id"`
	Resume       string `gorm:"column:resume" json:"resume"`
	ResumeName   string `gorm:"column:resume_name" json:"resume_name"`
	Remarks      string `gorm:"column:remarks" json:"remarks"`
	Time         string `gorm:"column:time" json:"time"`
	Birth        string `gorm:"column:birth" json:"birth"`
	HomeUID      int32  `gorm:"column:home_uid" json:"home_uid"`
	Status       int32  `gorm:"column:status" json:"status"`
	NowCompany   string `gorm:"column:now_company" json:"now_company"`
	NowPosition  string `gorm:"column:now_position" json:"now_position"`
	Type         int32  `gorm:"column:type;default:1;comment:1=自己应聘、2=推荐他人" json:"type"` // 1=自己应聘、2=推荐他人
}

// TableName Apply's table name
func (*Apply) TableName() string {
	return TableNameApply
}
