// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCompanyAddress = "company_address"

// CompanyAddress 公司地址表
type CompanyAddress struct {
	ID         uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CompanyID  uint32 `gorm:"column:company_id;comment:公司Id" json:"company_id"`               // 公司Id
	Address    string `gorm:"column:address;comment:地址" json:"address"`                       // 地址
	TimeInsert int32  `gorm:"column:time_insert;comment:添加时间" json:"time_insert"`             // 添加时间
	Status     int32  `gorm:"column:status;default:2;comment:0-删除，1-暂不使用，2-正常" json:"status"` // 0-删除，1-暂不使用，2-正常
}

// TableName CompanyAddress's table name
func (*CompanyAddress) TableName() string {
	return TableNameCompanyAddress
}
