// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataCity = "data_city"

// DataCity mapped from table <data_city>
type DataCity struct {
	ID         uint32 `gorm:"column:id;primaryKey" json:"id"`
	CityIndex  int32  `gorm:"column:city_index" json:"city_index"`
	ProvinceID int32  `gorm:"column:province_id" json:"province_id"`
	Sort       int32  `gorm:"column:sort;comment:排序" json:"sort"` // 排序
	Name       string `gorm:"column:name" json:"name"`
}

// TableName DataCity's table name
func (*DataCity) TableName() string {
	return TableNameDataCity
}
