// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataPositionTag = "data_position_tag"

// DataPositionTag mapped from table <data_position_tag>
type DataPositionTag struct {
	ID    uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Pid   uint32 `gorm:"column:pid;not null" json:"pid"`
	Level uint32 `gorm:"column:level;not null" json:"level"`
	Name  string `gorm:"column:name;not null" json:"name"`
	Path  string `gorm:"column:path;not null" json:"path"`
	Sort  uint32 `gorm:"column:sort;not null" json:"sort"`
}

// TableName DataPositionTag's table name
func (*DataPositionTag) TableName() string {
	return TableNameDataPositionTag
}
