// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDataDistrict = "data_district"

// DataDistrict mapped from table <data_district>
type DataDistrict struct {
	ID     uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CityID uint32 `gorm:"column:city_id;not null" json:"city_id"`
	Sort   int32  `gorm:"column:sort;not null" json:"sort"`
	Name   string `gorm:"column:name;not null" json:"name"`
}

// TableName DataDistrict's table name
func (*DataDistrict) TableName() string {
	return TableNameDataDistrict
}
