// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDeliver = "deliver"

// Deliver mapped from table <deliver>
type Deliver struct {
	ID                       uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type                     uint32 `gorm:"column:type;not null;comment:投递类型: 1. 自己投递，2. 手动推荐" json:"type"` // 投递类型: 1. 自己投递，2. 手动推荐
	AccountID                uint32 `gorm:"column:account_id;not null" json:"account_id"`
	AccountName              string `gorm:"column:account_name;not null;comment:账号名称" json:"account_name"`      // 账号名称
	AccountMobile            string `gorm:"column:account_mobile;not null;comment:账号手机号" json:"account_mobile"` // 账号手机号
	Name                     string `gorm:"column:name;not null;comment:候选人姓名" json:"name"`                     // 候选人姓名
	Mobile                   string `gorm:"column:mobile;not null;comment:候选人手机号" json:"mobile"`                // 候选人手机号
	Email                    string `gorm:"column:email;not null;comment:候选人邮箱" json:"email"`                   // 候选人邮箱
	PassageID                uint32 `gorm:"column:passage_id;not null" json:"passage_id"`
	PassageRecommendID       uint32 `gorm:"column:passage_recommend_id;not null" json:"passage_recommend_id"`
	PassageRecommendPath     string `gorm:"column:passage_recommend_path;not null;default:0;comment:职位推荐路径" json:"passage_recommend_path"`      // 职位推荐路径
	PassageRecommendPathFull string `gorm:"column:passage_recommend_path_full;not null;comment:职位推荐路径，带上自己" json:"passage_recommend_path_full"` // 职位推荐路径，带上自己
	RecommendAccountID       uint32 `gorm:"column:recommend_account_id;not null" json:"recommend_account_id"`
	RecommendComment         string `gorm:"column:recommend_comment;not null;comment:推荐评价" json:"recommend_comment"` // 推荐评价
	ResumeURL                string `gorm:"column:resume_url;not null;comment:简历地址" json:"resume_url"`               // 简历地址
	ProgressEid              uint32 `gorm:"column:progress_eid;not null;default:1;comment:投递状态" json:"progress_eid"` // 投递状态
	Progress                 string `gorm:"column:progress;not null;comment:投递状态" json:"progress"`                   // 投递状态
	IsReal                   uint32 `gorm:"column:is_real;not null;comment:是否已经投递" json:"is_real"`                   // 是否已经投递
	DeliverTime              uint64 `gorm:"column:deliver_time;not null;comment:投递时间" json:"deliver_time"`           // 投递时间
	CreatedTime              int64  `gorm:"column:created_time;not null;comment:创建时间" json:"created_time"`           // 创建时间
	UpdatedTime              int64  `gorm:"column:updated_time;not null;comment:更新时间" json:"updated_time"`           // 更新时间
}

// TableName Deliver's table name
func (*Deliver) TableName() string {
	return TableNameDeliver
}
