// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEmploy = "employ"

// Employ mapped from table <employ>
type Employ struct {
	ID           uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string `gorm:"column:name" json:"name"`
	Phone        string `gorm:"column:phone" json:"phone"`
	Email        string `gorm:"column:email" json:"email"`
	Campany      string `gorm:"column:campany" json:"campany"`
	ConnectionID int32  `gorm:"column:connection_id" json:"connection_id"`
	PassageID    int32  `gorm:"column:passage_id" json:"passage_id"`
	Need         string `gorm:"column:need" json:"need"`
}

// TableName Employ's table name
func (*Employ) TableName() string {
	return TableNameEmploy
}
