// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameHomeUser = "home_user"

// HomeUser mapped from table <home_user>
type HomeUser struct {
	ID            uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Unionid       string `gorm:"column:unionid" json:"unionid"`
	Password      string `gorm:"column:password" json:"password"`
	Phone         int64  `gorm:"column:phone" json:"phone"`
	Nickname      string `gorm:"column:nickname" json:"nickname"`
	Realname      string `gorm:"column:realname;not null;comment:真实姓名" json:"realname"` // 真实姓名
	Sex           string `gorm:"column:sex" json:"sex"`
	Headimgurl    string `gorm:"column:headimgurl" json:"headimgurl"`
	Myreward      int32  `gorm:"column:myreward" json:"myreward"`
	Email         string `gorm:"column:email" json:"email"`
	Birthday      string `gorm:"column:birthday;comment:出生年月日" json:"birthday"` // 出生年月日
	UserID        int32  `gorm:"column:user_id" json:"user_id"`
	Company       string `gorm:"column:company;not null;comment:当前公司" json:"company"`    // 当前公司
	Position      string `gorm:"column:position;not null;comment:当前职位" json:"position"`  // 当前职位
	WechatID      string `gorm:"column:wechat_id;not null;comment:微信号" json:"wechat_id"` // 微信号
	SearchHistory string `gorm:"column:search_history;not null" json:"search_history"`
}

// TableName HomeUser's table name
func (*HomeUser) TableName() string {
	return TableNameHomeUser
}
