// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameIndustryAssociation = "industry_association"

// IndustryAssociation mapped from table <industry_association>
type IndustryAssociation struct {
	ID              int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type            string `gorm:"column:type;not null;default:industry_association" json:"type"`
	Title           string `gorm:"column:title;not null" json:"title"`
	Digest          string `gorm:"column:digest;not null" json:"digest"`
	ImageURL        string `gorm:"column:image_url;not null" json:"image_url"`
	TimeBegin       int32  `gorm:"column:time_begin;not null" json:"time_begin"`
	TimeEnd         int32  `gorm:"column:time_end;not null" json:"time_end"`
	PeopleDemand    string `gorm:"column:people_demand;not null" json:"people_demand"`
	Cost            string `gorm:"column:cost;not null" json:"cost"`
	Address         string `gorm:"column:address;not null" json:"address"`
	Content         string `gorm:"column:content;not null" json:"content"`
	Requirement     string `gorm:"column:requirement;not null;comment:参与条件" json:"requirement"` // 参与条件
	Attention       string `gorm:"column:attention;not null;comment:注意事项" json:"attention"`     // 注意事项
	AdminID         int32  `gorm:"column:admin_id;not null" json:"admin_id"`
	CompanyID       int32  `gorm:"column:company_id;not null" json:"company_id"`
	City            string `gorm:"column:city;not null" json:"city"`
	MeetingCategory string `gorm:"column:meeting_category;not null" json:"meeting_category"`
	PositionTag     string `gorm:"column:position_tag;not null" json:"position_tag"`
	Experience      string `gorm:"column:experience;not null" json:"experience"`
	Salary          string `gorm:"column:salary;not null" json:"salary"`
	PassageIds      string `gorm:"column:passage_ids;not null;comment:关联的职位id列表" json:"passage_ids"`  // 关联的职位id列表
	AccountID       uint32 `gorm:"column:account_id;not null;comment:文章account_id" json:"account_id"` // 文章account_id
	SourceURL       string `gorm:"column:source_url;not null;comment:原文地址" json:"source_url"`         // 原文地址
	IsTop           int32  `gorm:"column:is_top;not null;comment:是否置顶" json:"is_top"`                 // 是否置顶
	Pulisher        string `gorm:"column:pulisher;not null;comment:发布者" json:"pulisher"`              // 发布者
	ViewCount       int32  `gorm:"column:view_count;not null;comment:阅读数量" json:"view_count"`         // 阅读数量
	LikeCount       uint32 `gorm:"column:like_count;not null;comment:点赞量" json:"like_count"`          // 点赞量
	TimeInsert      int32  `gorm:"column:time_insert;not null" json:"time_insert"`
	TimeUpdate      int32  `gorm:"column:time_update;not null" json:"time_update"`
	Status          int32  `gorm:"column:status;not null" json:"status"`
}

// TableName IndustryAssociation's table name
func (*IndustryAssociation) TableName() string {
	return TableNameIndustryAssociation
}
