// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMeetingJoin = "meeting_join"

// MeetingJoin mapped from table <meeting_join>
type MeetingJoin struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     int32  `gorm:"column:user_id;not null" json:"user_id"`
	MeetingID  int32  `gorm:"column:meeting_id;not null" json:"meeting_id"`
	Name       string `gorm:"column:name;not null" json:"name"`
	Company    string `gorm:"column:company;not null" json:"company"`
	Position   string `gorm:"column:position;not null" json:"position"`
	WechatID   string `gorm:"column:wechat_id;not null;comment:微信号" json:"wechat_id"` // 微信号
	Birthday   string `gorm:"column:birthday;not null" json:"birthday"`
	Message    string `gorm:"column:message;not null" json:"message"`
	TimeInsert int32  `gorm:"column:time_insert;not null" json:"time_insert"`
	Status     int32  `gorm:"column:status;not null" json:"status"`
}

// TableName MeetingJoin's table name
func (*MeetingJoin) TableName() string {
	return TableNameMeetingJoin
}
