// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePassage = "passage"

// Passage mapped from table <passage>
type Passage struct {
	ID                      uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Content                 string `gorm:"column:content;not null" json:"content"`
	Title                   string `gorm:"column:title;not null" json:"title"`
	Time                    string `gorm:"column:time;not null" json:"time"`
	Summary                 string `gorm:"column:summary;not null" json:"summary"`
	Icon                    string `gorm:"column:icon;not null" json:"icon"`
	AdminID                 uint32 `gorm:"column:admin_id;not null" json:"admin_id"`
	Type                    int32  `gorm:"column:type;not null;comment:0=招聘、1=求职" json:"type"` // 0=招聘、1=求职
	CityID                  uint32 `gorm:"column:city_id;not null" json:"city_id"`
	DistrictID              uint32 `gorm:"column:district_id;not null" json:"district_id"`
	SalaryID                uint32 `gorm:"column:salary_id;not null" json:"salary_id"`
	ExperienceID            uint32 `gorm:"column:experience_id;not null" json:"experience_id"`
	EducationID             uint32 `gorm:"column:education_id;not null" json:"education_id"`
	IndustryID              uint32 `gorm:"column:industry_id;not null" json:"industry_id"`
	IndustryPath            string `gorm:"column:industry_path;not null" json:"industry_path"`
	CompanyscaleID          uint32 `gorm:"column:companyscale_id;not null" json:"companyscale_id"`
	CompanystageID          uint32 `gorm:"column:companystage_id;not null" json:"companystage_id"`
	CompanyAddressID        uint32 `gorm:"column:company_address_id;not null;comment:公司地址Id（支持多地址，为0时取默认地址）" json:"company_address_id"` // 公司地址Id（支持多地址，为0时取默认地址）
	Companyname             string `gorm:"column:companyname;not null" json:"companyname"`
	Reward                  string `gorm:"column:reward;not null" json:"reward"`
	Issue                   int32  `gorm:"column:issue;not null" json:"issue"`
	PositionTagID           uint32 `gorm:"column:position_tag_id;not null" json:"position_tag_id"`
	PositionTagPath         string `gorm:"column:position_tag_path;not null" json:"position_tag_path"`
	Liangdian               string `gorm:"column:liangdian;not null" json:"liangdian"`
	EditContent             string `gorm:"column:edit_content;not null" json:"edit_content"`
	PositionQualification   string `gorm:"column:position_qualification;not null;comment:任职资格" json:"position_qualification"` // 任职资格
	PositionResearch        string `gorm:"column:position_research;not null;comment:职位调研" json:"position_research"`           // 职位调研
	Mtime                   string `gorm:"column:mtime;not null" json:"mtime"`
	Status                  uint32 `gorm:"column:status;not null;comment:0=正常、1=下架" json:"status"` // 0=正常、1=下架
	SalaryMin               uint32 `gorm:"column:salary_min" json:"salary_min"`
	SalaryMax               uint32 `gorm:"column:salary_max" json:"salary_max"`
	HeadCount               uint32 `gorm:"column:head_count;not null;comment:招聘所需人数" json:"head_count"` // 招聘所需人数
	CompanyRemark           string `gorm:"column:company_remark;not null" json:"company_remark"`
	IsTop                   int32  `gorm:"column:is_top;not null" json:"is_top"`
	IsRefined               int32  `gorm:"column:is_refined;not null;comment:是否精选" json:"is_refined"`               // 是否精选
	IsAnonymous             int32  `gorm:"column:is_anonymous;not null;default:1;comment:是否匿名" json:"is_anonymous"` // 是否匿名
	SuccessReward           string `gorm:"column:success_reward;not null;comment:推荐奖金" json:"success_reward"`       // 推荐奖金
	SuccessReward2          string `gorm:"column:success_reward2;not null" json:"success_reward2"`
	SuccessRewardRemark     string `gorm:"column:success_reward_remark;not null" json:"success_reward_remark"`
	InterviewReward         string `gorm:"column:interview_reward;not null;comment:自荐奖金" json:"interview_reward"` // 自荐奖金
	InterviewReward2        string `gorm:"column:interview_reward2;not null" json:"interview_reward2"`
	InterviewRewardRemark   string `gorm:"column:interview_reward_remark;not null" json:"interview_reward_remark"`
	ScholarshipReward       string `gorm:"column:scholarship_reward;not null" json:"scholarship_reward"`
	ScholarshipRewardRemark string `gorm:"column:scholarship_reward_remark;not null" json:"scholarship_reward_remark"`
	McAdmin                 int32  `gorm:"column:mc_admin;not null;comment:mc管理员ID" json:"mc_admin"`    // mc管理员ID
	RecAdmin                string `gorm:"column:rec_admin;not null;comment:分配顾问" json:"rec_admin"`     // 分配顾问
	PsgCompany              uint32 `gorm:"column:psg_company;not null;comment:顾客公司" json:"psg_company"` // 顾客公司
	CompanyID               uint32 `gorm:"column:company_id;not null" json:"company_id"`
	RecommendRule           string `gorm:"column:recommend_rule;not null;comment:推荐规则" json:"recommend_rule"` // 推荐规则
	Contact                 string `gorm:"column:contact;not null;comment:联系方式" json:"contact"`               // 联系方式
}

// TableName Passage's table name
func (*Passage) TableName() string {
	return TableNamePassage
}
