// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePassageProject = "passage_project"

// PassageProject mapped from table <passage_project>
type PassageProject struct {
	ID        uint32 `gorm:"column:id;primaryKey" json:"id"`
	PassageID uint32 `gorm:"column:passage_id;not null;comment:职位ID" json:"passage_id"` // 职位ID
	AdminID   uint32 `gorm:"column:admin_id;not null;comment:hr_id" json:"admin_id"`    // hr_id
	CompanyID uint32 `gorm:"column:company_id;not null;comment:公司ID" json:"company_id"` // 公司ID
	ResumeID  uint32 `gorm:"column:resume_id;not null;comment:简历ID" json:"resume_id"`   // 简历ID
	State     int32  `gorm:"column:state;not null;default:1;comment:状态" json:"state"`   // 状态
	Data      string `gorm:"column:data;not null;comment:状态json" json:"data"`           // 状态json
	AddTime   uint32 `gorm:"column:add_time;not null;comment:添加时间" json:"add_time"`     // 添加时间
	ModTime   uint32 `gorm:"column:mod_time;not null;comment:修改时间" json:"mod_time"`     // 修改时间
}

// TableName PassageProject's table name
func (*PassageProject) TableName() string {
	return TableNamePassageProject
}
