// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePassageCompanyEvent = "passage_company_event"

// PassageCompanyEvent mapped from table <passage_company_event>
type PassageCompanyEvent struct {
	ID               uint32    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RootCompanyID    uint32    `gorm:"column:root_company_id;not null" json:"root_company_id"`
	PassageCompanyID uint32    `gorm:"column:passage_company_id;not null" json:"passage_company_id"`
	EventDate        time.Time `gorm:"column:event_date;not null;comment:日期" json:"event_date"`     // 日期
	Title            string    `gorm:"column:title;not null;comment:事件标题" json:"title"`             // 事件标题
	Description      string    `gorm:"column:description;not null;comment:事件描述" json:"description"` // 事件描述
	CreatedTime      int64     `gorm:"column:created_time;not null" json:"created_time"`
	UpdatedTime      int64     `gorm:"column:updated_time;not null" json:"updated_time"`
}

// TableName PassageCompanyEvent's table name
func (*PassageCompanyEvent) TableName() string {
	return TableNamePassageCompanyEvent
}
