// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePassageRecommend = "passage_recommend"

// PassageRecommend mapped from table <passage_recommend>
type PassageRecommend struct {
	ID                       uint32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PassageID                uint32 `gorm:"column:passage_id;not null" json:"passage_id"`
	AccountID                uint32 `gorm:"column:account_id;not null" json:"account_id"`
	Path                     string `gorm:"column:path;not null;default:0;comment:传播路径" json:"path"`                // 传播路径
	PathFull                 string `gorm:"column:path_full;not null;default:0;comment:传播路径(带自己)" json:"path_full"` // 传播路径(带自己)
	ParentPassageRecommendID uint32 `gorm:"column:parent_passage_recommend_id;not null" json:"parent_passage_recommend_id"`
	RecommendCount           uint32 `gorm:"column:recommend_count;not null;comment:推荐投递次数" json:"recommend_count"`         // 推荐投递次数
	RecommendCountL2         uint32 `gorm:"column:recommend_count_l2;not null;comment:推荐投递次数二级" json:"recommend_count_l2"` // 推荐投递次数二级
	ShareCount               uint32 `gorm:"column:share_count;not null;comment:分享数量" json:"share_count"`                   // 分享数量
	ShareCountL2             uint32 `gorm:"column:share_count_l2;not null;comment:分享数量2级" json:"share_count_l2"`           // 分享数量2级
	CreatedTime              int64  `gorm:"column:created_time;not null;comment:创建时间" json:"created_time"`                 // 创建时间
	UpdatedTime              int64  `gorm:"column:updated_time;not null;comment:更新时间" json:"updated_time"`                 // 更新时间
}

// TableName PassageRecommend's table name
func (*PassageRecommend) TableName() string {
	return TableNamePassageRecommend
}
