// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameResumeRemind = "resume_remind"

// ResumeRemind mapped from table <resume_remind>
type ResumeRemind struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AdminID    int32  `gorm:"column:admin_id;not null;comment:管理员ID" json:"admin_id"`        // 管理员ID
	ResumeID   int32  `gorm:"column:resume_id;not null;comment:简历ID" json:"resume_id"`       // 简历ID
	RemindTime string `gorm:"column:remind_time;not null;comment:yymmdd" json:"remind_time"` // yymmdd
	AddTime    int32  `gorm:"column:add_time;not null;comment:添加时间" json:"add_time"`         // 添加时间
}

// TableName ResumeRemind's table name
func (*ResumeRemind) TableName() string {
	return TableNameResumeRemind
}
