// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameResumeVisitHistory = "resume_visit_history"

// ResumeVisitHistory 简历寻访表
type ResumeVisitHistory struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ResumeID   int32  `gorm:"column:resume_id;not null;comment:简历Id" json:"resume_id"`                 // 简历Id
	AdminID    int32  `gorm:"column:admin_id;not null;comment:管理者Id" json:"admin_id"`                  // 管理者Id
	Content    string `gorm:"column:content;not null;comment:寻访记录" json:"content"`                     // 寻访记录
	TimeInsert int32  `gorm:"column:time_insert;not null;comment:添加时间" json:"time_insert"`             // 添加时间
	TimeUpdate int32  `gorm:"column:time_update;not null;comment:编辑时间" json:"time_update"`             // 编辑时间
	Status     int32  `gorm:"column:status;not null;default:2;comment:0-删除，1-暂不使用，2-正常" json:"status"` // 0-删除，1-暂不使用，2-正常
}

// TableName ResumeVisitHistory's table name
func (*ResumeVisitHistory) TableName() string {
	return TableNameResumeVisitHistory
}
