// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserCenter = "user_center"

// UserCenter mapped from table <user_center>
type UserCenter struct {
	UserID           int32 `gorm:"column:user_id;primaryKey" json:"user_id"`
	PassageID        int32 `gorm:"column:passage_id;primaryKey" json:"passage_id"`
	CountRelay       int32 `gorm:"column:count_relay;not null" json:"count_relay"`
	CountApply       int32 `gorm:"column:count_apply;not null" json:"count_apply"`
	CountSecondApply int32 `gorm:"column:count_second_apply;not null" json:"count_second_apply"`
}

// TableName UserCenter's table name
func (*UserCenter) TableName() string {
	return TableNameUserCenter
}
