// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newAccountApplyResumeAuth(db *gorm.DB, opts ...gen.DOOption) accountApplyResumeAuth {
	_accountApplyResumeAuth := accountApplyResumeAuth{}

	_accountApplyResumeAuth.accountApplyResumeAuthDo.UseDB(db, opts...)
	_accountApplyResumeAuth.accountApplyResumeAuthDo.UseModel(&model.AccountApplyResumeAuth{})

	tableName := _accountApplyResumeAuth.accountApplyResumeAuthDo.TableName()
	_accountApplyResumeAuth.ALL = field.NewAsterisk(tableName)
	_accountApplyResumeAuth.ID = field.NewUint32(tableName, "id")
	_accountApplyResumeAuth.AccountApplyID = field.NewUint32(tableName, "account_apply_id")
	_accountApplyResumeAuth.RequestAccountID = field.NewUint32(tableName, "request_account_id")
	_accountApplyResumeAuth.AuthState = field.NewUint32(tableName, "auth_state")
	_accountApplyResumeAuth.CreatedTime = field.NewInt64(tableName, "created_time")
	_accountApplyResumeAuth.UpdatedTime = field.NewInt64(tableName, "updated_time")
	_accountApplyResumeAuth.Status = field.NewUint32(tableName, "status")

	_accountApplyResumeAuth.fillFieldMap()

	return _accountApplyResumeAuth
}

type accountApplyResumeAuth struct {
	accountApplyResumeAuthDo

	ALL              field.Asterisk
	ID               field.Uint32
	AccountApplyID   field.Uint32
	RequestAccountID field.Uint32
	AuthState        field.Uint32 // 0 未处理 1 通过 其他拒绝
	CreatedTime      field.Int64  // 创建时间
	UpdatedTime      field.Int64  // 更新时间
	Status           field.Uint32

	fieldMap map[string]field.Expr
}

func (a accountApplyResumeAuth) Table(newTableName string) *accountApplyResumeAuth {
	a.accountApplyResumeAuthDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a accountApplyResumeAuth) As(alias string) *accountApplyResumeAuth {
	a.accountApplyResumeAuthDo.DO = *(a.accountApplyResumeAuthDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *accountApplyResumeAuth) updateTableName(table string) *accountApplyResumeAuth {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint32(table, "id")
	a.AccountApplyID = field.NewUint32(table, "account_apply_id")
	a.RequestAccountID = field.NewUint32(table, "request_account_id")
	a.AuthState = field.NewUint32(table, "auth_state")
	a.CreatedTime = field.NewInt64(table, "created_time")
	a.UpdatedTime = field.NewInt64(table, "updated_time")
	a.Status = field.NewUint32(table, "status")

	a.fillFieldMap()

	return a
}

func (a *accountApplyResumeAuth) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *accountApplyResumeAuth) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 7)
	a.fieldMap["id"] = a.ID
	a.fieldMap["account_apply_id"] = a.AccountApplyID
	a.fieldMap["request_account_id"] = a.RequestAccountID
	a.fieldMap["auth_state"] = a.AuthState
	a.fieldMap["created_time"] = a.CreatedTime
	a.fieldMap["updated_time"] = a.UpdatedTime
	a.fieldMap["status"] = a.Status
}

func (a accountApplyResumeAuth) clone(db *gorm.DB) accountApplyResumeAuth {
	a.accountApplyResumeAuthDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a accountApplyResumeAuth) replaceDB(db *gorm.DB) accountApplyResumeAuth {
	a.accountApplyResumeAuthDo.ReplaceDB(db)
	return a
}

type accountApplyResumeAuthDo struct{ gen.DO }

type IAccountApplyResumeAuthDo interface {
	gen.SubQuery
	Debug() IAccountApplyResumeAuthDo
	WithContext(ctx context.Context) IAccountApplyResumeAuthDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAccountApplyResumeAuthDo
	WriteDB() IAccountApplyResumeAuthDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAccountApplyResumeAuthDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAccountApplyResumeAuthDo
	Not(conds ...gen.Condition) IAccountApplyResumeAuthDo
	Or(conds ...gen.Condition) IAccountApplyResumeAuthDo
	Select(conds ...field.Expr) IAccountApplyResumeAuthDo
	Where(conds ...gen.Condition) IAccountApplyResumeAuthDo
	Order(conds ...field.Expr) IAccountApplyResumeAuthDo
	Distinct(cols ...field.Expr) IAccountApplyResumeAuthDo
	Omit(cols ...field.Expr) IAccountApplyResumeAuthDo
	Join(table schema.Tabler, on ...field.Expr) IAccountApplyResumeAuthDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAccountApplyResumeAuthDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAccountApplyResumeAuthDo
	Group(cols ...field.Expr) IAccountApplyResumeAuthDo
	Having(conds ...gen.Condition) IAccountApplyResumeAuthDo
	Limit(limit int) IAccountApplyResumeAuthDo
	Offset(offset int) IAccountApplyResumeAuthDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAccountApplyResumeAuthDo
	Unscoped() IAccountApplyResumeAuthDo
	Create(values ...*model.AccountApplyResumeAuth) error
	CreateInBatches(values []*model.AccountApplyResumeAuth, batchSize int) error
	Save(values ...*model.AccountApplyResumeAuth) error
	First() (*model.AccountApplyResumeAuth, error)
	Take() (*model.AccountApplyResumeAuth, error)
	Last() (*model.AccountApplyResumeAuth, error)
	Find() ([]*model.AccountApplyResumeAuth, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AccountApplyResumeAuth, err error)
	FindInBatches(result *[]*model.AccountApplyResumeAuth, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AccountApplyResumeAuth) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAccountApplyResumeAuthDo
	Assign(attrs ...field.AssignExpr) IAccountApplyResumeAuthDo
	Joins(fields ...field.RelationField) IAccountApplyResumeAuthDo
	Preload(fields ...field.RelationField) IAccountApplyResumeAuthDo
	FirstOrInit() (*model.AccountApplyResumeAuth, error)
	FirstOrCreate() (*model.AccountApplyResumeAuth, error)
	FindByPage(offset int, limit int) (result []*model.AccountApplyResumeAuth, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAccountApplyResumeAuthDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a accountApplyResumeAuthDo) Debug() IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Debug())
}

func (a accountApplyResumeAuthDo) WithContext(ctx context.Context) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a accountApplyResumeAuthDo) ReadDB() IAccountApplyResumeAuthDo {
	return a.Clauses(dbresolver.Read)
}

func (a accountApplyResumeAuthDo) WriteDB() IAccountApplyResumeAuthDo {
	return a.Clauses(dbresolver.Write)
}

func (a accountApplyResumeAuthDo) Session(config *gorm.Session) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Session(config))
}

func (a accountApplyResumeAuthDo) Clauses(conds ...clause.Expression) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a accountApplyResumeAuthDo) Returning(value interface{}, columns ...string) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a accountApplyResumeAuthDo) Not(conds ...gen.Condition) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a accountApplyResumeAuthDo) Or(conds ...gen.Condition) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a accountApplyResumeAuthDo) Select(conds ...field.Expr) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a accountApplyResumeAuthDo) Where(conds ...gen.Condition) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a accountApplyResumeAuthDo) Order(conds ...field.Expr) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a accountApplyResumeAuthDo) Distinct(cols ...field.Expr) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a accountApplyResumeAuthDo) Omit(cols ...field.Expr) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a accountApplyResumeAuthDo) Join(table schema.Tabler, on ...field.Expr) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a accountApplyResumeAuthDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a accountApplyResumeAuthDo) RightJoin(table schema.Tabler, on ...field.Expr) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a accountApplyResumeAuthDo) Group(cols ...field.Expr) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a accountApplyResumeAuthDo) Having(conds ...gen.Condition) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a accountApplyResumeAuthDo) Limit(limit int) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a accountApplyResumeAuthDo) Offset(offset int) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a accountApplyResumeAuthDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a accountApplyResumeAuthDo) Unscoped() IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Unscoped())
}

func (a accountApplyResumeAuthDo) Create(values ...*model.AccountApplyResumeAuth) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a accountApplyResumeAuthDo) CreateInBatches(values []*model.AccountApplyResumeAuth, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a accountApplyResumeAuthDo) Save(values ...*model.AccountApplyResumeAuth) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a accountApplyResumeAuthDo) First() (*model.AccountApplyResumeAuth, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountApplyResumeAuth), nil
	}
}

func (a accountApplyResumeAuthDo) Take() (*model.AccountApplyResumeAuth, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountApplyResumeAuth), nil
	}
}

func (a accountApplyResumeAuthDo) Last() (*model.AccountApplyResumeAuth, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountApplyResumeAuth), nil
	}
}

func (a accountApplyResumeAuthDo) Find() ([]*model.AccountApplyResumeAuth, error) {
	result, err := a.DO.Find()
	return result.([]*model.AccountApplyResumeAuth), err
}

func (a accountApplyResumeAuthDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AccountApplyResumeAuth, err error) {
	buf := make([]*model.AccountApplyResumeAuth, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a accountApplyResumeAuthDo) FindInBatches(result *[]*model.AccountApplyResumeAuth, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a accountApplyResumeAuthDo) Attrs(attrs ...field.AssignExpr) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a accountApplyResumeAuthDo) Assign(attrs ...field.AssignExpr) IAccountApplyResumeAuthDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a accountApplyResumeAuthDo) Joins(fields ...field.RelationField) IAccountApplyResumeAuthDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a accountApplyResumeAuthDo) Preload(fields ...field.RelationField) IAccountApplyResumeAuthDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a accountApplyResumeAuthDo) FirstOrInit() (*model.AccountApplyResumeAuth, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountApplyResumeAuth), nil
	}
}

func (a accountApplyResumeAuthDo) FirstOrCreate() (*model.AccountApplyResumeAuth, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountApplyResumeAuth), nil
	}
}

func (a accountApplyResumeAuthDo) FindByPage(offset int, limit int) (result []*model.AccountApplyResumeAuth, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a accountApplyResumeAuthDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a accountApplyResumeAuthDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a accountApplyResumeAuthDo) Delete(models ...*model.AccountApplyResumeAuth) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *accountApplyResumeAuthDo) withDO(do gen.Dao) *accountApplyResumeAuthDo {
	a.DO = *do.(*gen.DO)
	return a
}
