// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newAccountHelp(db *gorm.DB, opts ...gen.DOOption) accountHelp {
	_accountHelp := accountHelp{}

	_accountHelp.accountHelpDo.UseDB(db, opts...)
	_accountHelp.accountHelpDo.UseModel(&model.AccountHelp{})

	tableName := _accountHelp.accountHelpDo.TableName()
	_accountHelp.ALL = field.NewAsterisk(tableName)
	_accountHelp.ID = field.NewUint32(tableName, "id")
	_accountHelp.AccountApplyID = field.NewUint32(tableName, "account_apply_id")
	_accountHelp.HelperAccountID = field.NewUint32(tableName, "helper_account_id")
	_accountHelp.Company = field.NewString(tableName, "company")
	_accountHelp.Position = field.NewString(tableName, "position")
	_accountHelp.HelpPlan = field.NewString(tableName, "help_plan")
	_accountHelp.CreatedTime = field.NewInt64(tableName, "created_time")
	_accountHelp.UpdatedTime = field.NewInt64(tableName, "updated_time")

	_accountHelp.fillFieldMap()

	return _accountHelp
}

type accountHelp struct {
	accountHelpDo

	ALL             field.Asterisk
	ID              field.Uint32
	AccountApplyID  field.Uint32 // 被协助者求职id
	HelperAccountID field.Uint32 // 协助人ID
	Company         field.String // 公司
	Position        field.String // 职位
	HelpPlan        field.String
	CreatedTime     field.Int64 // 创建时间
	UpdatedTime     field.Int64 // 更新时间

	fieldMap map[string]field.Expr
}

func (a accountHelp) Table(newTableName string) *accountHelp {
	a.accountHelpDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a accountHelp) As(alias string) *accountHelp {
	a.accountHelpDo.DO = *(a.accountHelpDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *accountHelp) updateTableName(table string) *accountHelp {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint32(table, "id")
	a.AccountApplyID = field.NewUint32(table, "account_apply_id")
	a.HelperAccountID = field.NewUint32(table, "helper_account_id")
	a.Company = field.NewString(table, "company")
	a.Position = field.NewString(table, "position")
	a.HelpPlan = field.NewString(table, "help_plan")
	a.CreatedTime = field.NewInt64(table, "created_time")
	a.UpdatedTime = field.NewInt64(table, "updated_time")

	a.fillFieldMap()

	return a
}

func (a *accountHelp) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *accountHelp) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["id"] = a.ID
	a.fieldMap["account_apply_id"] = a.AccountApplyID
	a.fieldMap["helper_account_id"] = a.HelperAccountID
	a.fieldMap["company"] = a.Company
	a.fieldMap["position"] = a.Position
	a.fieldMap["help_plan"] = a.HelpPlan
	a.fieldMap["created_time"] = a.CreatedTime
	a.fieldMap["updated_time"] = a.UpdatedTime
}

func (a accountHelp) clone(db *gorm.DB) accountHelp {
	a.accountHelpDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a accountHelp) replaceDB(db *gorm.DB) accountHelp {
	a.accountHelpDo.ReplaceDB(db)
	return a
}

type accountHelpDo struct{ gen.DO }

type IAccountHelpDo interface {
	gen.SubQuery
	Debug() IAccountHelpDo
	WithContext(ctx context.Context) IAccountHelpDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAccountHelpDo
	WriteDB() IAccountHelpDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAccountHelpDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAccountHelpDo
	Not(conds ...gen.Condition) IAccountHelpDo
	Or(conds ...gen.Condition) IAccountHelpDo
	Select(conds ...field.Expr) IAccountHelpDo
	Where(conds ...gen.Condition) IAccountHelpDo
	Order(conds ...field.Expr) IAccountHelpDo
	Distinct(cols ...field.Expr) IAccountHelpDo
	Omit(cols ...field.Expr) IAccountHelpDo
	Join(table schema.Tabler, on ...field.Expr) IAccountHelpDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAccountHelpDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAccountHelpDo
	Group(cols ...field.Expr) IAccountHelpDo
	Having(conds ...gen.Condition) IAccountHelpDo
	Limit(limit int) IAccountHelpDo
	Offset(offset int) IAccountHelpDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAccountHelpDo
	Unscoped() IAccountHelpDo
	Create(values ...*model.AccountHelp) error
	CreateInBatches(values []*model.AccountHelp, batchSize int) error
	Save(values ...*model.AccountHelp) error
	First() (*model.AccountHelp, error)
	Take() (*model.AccountHelp, error)
	Last() (*model.AccountHelp, error)
	Find() ([]*model.AccountHelp, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AccountHelp, err error)
	FindInBatches(result *[]*model.AccountHelp, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AccountHelp) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAccountHelpDo
	Assign(attrs ...field.AssignExpr) IAccountHelpDo
	Joins(fields ...field.RelationField) IAccountHelpDo
	Preload(fields ...field.RelationField) IAccountHelpDo
	FirstOrInit() (*model.AccountHelp, error)
	FirstOrCreate() (*model.AccountHelp, error)
	FindByPage(offset int, limit int) (result []*model.AccountHelp, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAccountHelpDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a accountHelpDo) Debug() IAccountHelpDo {
	return a.withDO(a.DO.Debug())
}

func (a accountHelpDo) WithContext(ctx context.Context) IAccountHelpDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a accountHelpDo) ReadDB() IAccountHelpDo {
	return a.Clauses(dbresolver.Read)
}

func (a accountHelpDo) WriteDB() IAccountHelpDo {
	return a.Clauses(dbresolver.Write)
}

func (a accountHelpDo) Session(config *gorm.Session) IAccountHelpDo {
	return a.withDO(a.DO.Session(config))
}

func (a accountHelpDo) Clauses(conds ...clause.Expression) IAccountHelpDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a accountHelpDo) Returning(value interface{}, columns ...string) IAccountHelpDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a accountHelpDo) Not(conds ...gen.Condition) IAccountHelpDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a accountHelpDo) Or(conds ...gen.Condition) IAccountHelpDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a accountHelpDo) Select(conds ...field.Expr) IAccountHelpDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a accountHelpDo) Where(conds ...gen.Condition) IAccountHelpDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a accountHelpDo) Order(conds ...field.Expr) IAccountHelpDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a accountHelpDo) Distinct(cols ...field.Expr) IAccountHelpDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a accountHelpDo) Omit(cols ...field.Expr) IAccountHelpDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a accountHelpDo) Join(table schema.Tabler, on ...field.Expr) IAccountHelpDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a accountHelpDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAccountHelpDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a accountHelpDo) RightJoin(table schema.Tabler, on ...field.Expr) IAccountHelpDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a accountHelpDo) Group(cols ...field.Expr) IAccountHelpDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a accountHelpDo) Having(conds ...gen.Condition) IAccountHelpDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a accountHelpDo) Limit(limit int) IAccountHelpDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a accountHelpDo) Offset(offset int) IAccountHelpDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a accountHelpDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAccountHelpDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a accountHelpDo) Unscoped() IAccountHelpDo {
	return a.withDO(a.DO.Unscoped())
}

func (a accountHelpDo) Create(values ...*model.AccountHelp) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a accountHelpDo) CreateInBatches(values []*model.AccountHelp, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a accountHelpDo) Save(values ...*model.AccountHelp) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a accountHelpDo) First() (*model.AccountHelp, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountHelp), nil
	}
}

func (a accountHelpDo) Take() (*model.AccountHelp, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountHelp), nil
	}
}

func (a accountHelpDo) Last() (*model.AccountHelp, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountHelp), nil
	}
}

func (a accountHelpDo) Find() ([]*model.AccountHelp, error) {
	result, err := a.DO.Find()
	return result.([]*model.AccountHelp), err
}

func (a accountHelpDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AccountHelp, err error) {
	buf := make([]*model.AccountHelp, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a accountHelpDo) FindInBatches(result *[]*model.AccountHelp, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a accountHelpDo) Attrs(attrs ...field.AssignExpr) IAccountHelpDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a accountHelpDo) Assign(attrs ...field.AssignExpr) IAccountHelpDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a accountHelpDo) Joins(fields ...field.RelationField) IAccountHelpDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a accountHelpDo) Preload(fields ...field.RelationField) IAccountHelpDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a accountHelpDo) FirstOrInit() (*model.AccountHelp, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountHelp), nil
	}
}

func (a accountHelpDo) FirstOrCreate() (*model.AccountHelp, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountHelp), nil
	}
}

func (a accountHelpDo) FindByPage(offset int, limit int) (result []*model.AccountHelp, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a accountHelpDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a accountHelpDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a accountHelpDo) Delete(models ...*model.AccountHelp) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *accountHelpDo) withDO(do gen.Dao) *accountHelpDo {
	a.DO = *do.(*gen.DO)
	return a
}
