// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newAccountEducation(db *gorm.DB, opts ...gen.DOOption) accountEducation {
	_accountEducation := accountEducation{}

	_accountEducation.accountEducationDo.UseDB(db, opts...)
	_accountEducation.accountEducationDo.UseModel(&model.AccountEducation{})

	tableName := _accountEducation.accountEducationDo.TableName()
	_accountEducation.ALL = field.NewAsterisk(tableName)
	_accountEducation.ID = field.NewUint32(tableName, "id")
	_accountEducation.AccountID = field.NewUint32(tableName, "account_id")
	_accountEducation.Name = field.NewString(tableName, "name")
	_accountEducation.Degree = field.NewString(tableName, "degree")
	_accountEducation.Profession = field.NewString(tableName, "profession")
	_accountEducation.StartTime = field.NewInt64(tableName, "start_time")
	_accountEducation.EndTime = field.NewInt64(tableName, "end_time")
	_accountEducation.Experience = field.NewString(tableName, "experience")
	_accountEducation.CreatedTime = field.NewInt64(tableName, "created_time")
	_accountEducation.UpdatedTime = field.NewInt64(tableName, "updated_time")

	_accountEducation.fillFieldMap()

	return _accountEducation
}

type accountEducation struct {
	accountEducationDo

	ALL         field.Asterisk
	ID          field.Uint32
	AccountID   field.Uint32
	Name        field.String // 学校名称
	Degree      field.String // 学历
	Profession  field.String // 专业
	StartTime   field.Int64  // 在职时间 - 开始
	EndTime     field.Int64  // 在职时间-结束
	Experience  field.String // 经历
	CreatedTime field.Int64  // 创建时间
	UpdatedTime field.Int64  // 更新时间

	fieldMap map[string]field.Expr
}

func (a accountEducation) Table(newTableName string) *accountEducation {
	a.accountEducationDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a accountEducation) As(alias string) *accountEducation {
	a.accountEducationDo.DO = *(a.accountEducationDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *accountEducation) updateTableName(table string) *accountEducation {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint32(table, "id")
	a.AccountID = field.NewUint32(table, "account_id")
	a.Name = field.NewString(table, "name")
	a.Degree = field.NewString(table, "degree")
	a.Profession = field.NewString(table, "profession")
	a.StartTime = field.NewInt64(table, "start_time")
	a.EndTime = field.NewInt64(table, "end_time")
	a.Experience = field.NewString(table, "experience")
	a.CreatedTime = field.NewInt64(table, "created_time")
	a.UpdatedTime = field.NewInt64(table, "updated_time")

	a.fillFieldMap()

	return a
}

func (a *accountEducation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *accountEducation) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 10)
	a.fieldMap["id"] = a.ID
	a.fieldMap["account_id"] = a.AccountID
	a.fieldMap["name"] = a.Name
	a.fieldMap["degree"] = a.Degree
	a.fieldMap["profession"] = a.Profession
	a.fieldMap["start_time"] = a.StartTime
	a.fieldMap["end_time"] = a.EndTime
	a.fieldMap["experience"] = a.Experience
	a.fieldMap["created_time"] = a.CreatedTime
	a.fieldMap["updated_time"] = a.UpdatedTime
}

func (a accountEducation) clone(db *gorm.DB) accountEducation {
	a.accountEducationDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a accountEducation) replaceDB(db *gorm.DB) accountEducation {
	a.accountEducationDo.ReplaceDB(db)
	return a
}

type accountEducationDo struct{ gen.DO }

type IAccountEducationDo interface {
	gen.SubQuery
	Debug() IAccountEducationDo
	WithContext(ctx context.Context) IAccountEducationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAccountEducationDo
	WriteDB() IAccountEducationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAccountEducationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAccountEducationDo
	Not(conds ...gen.Condition) IAccountEducationDo
	Or(conds ...gen.Condition) IAccountEducationDo
	Select(conds ...field.Expr) IAccountEducationDo
	Where(conds ...gen.Condition) IAccountEducationDo
	Order(conds ...field.Expr) IAccountEducationDo
	Distinct(cols ...field.Expr) IAccountEducationDo
	Omit(cols ...field.Expr) IAccountEducationDo
	Join(table schema.Tabler, on ...field.Expr) IAccountEducationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAccountEducationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAccountEducationDo
	Group(cols ...field.Expr) IAccountEducationDo
	Having(conds ...gen.Condition) IAccountEducationDo
	Limit(limit int) IAccountEducationDo
	Offset(offset int) IAccountEducationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAccountEducationDo
	Unscoped() IAccountEducationDo
	Create(values ...*model.AccountEducation) error
	CreateInBatches(values []*model.AccountEducation, batchSize int) error
	Save(values ...*model.AccountEducation) error
	First() (*model.AccountEducation, error)
	Take() (*model.AccountEducation, error)
	Last() (*model.AccountEducation, error)
	Find() ([]*model.AccountEducation, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AccountEducation, err error)
	FindInBatches(result *[]*model.AccountEducation, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AccountEducation) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAccountEducationDo
	Assign(attrs ...field.AssignExpr) IAccountEducationDo
	Joins(fields ...field.RelationField) IAccountEducationDo
	Preload(fields ...field.RelationField) IAccountEducationDo
	FirstOrInit() (*model.AccountEducation, error)
	FirstOrCreate() (*model.AccountEducation, error)
	FindByPage(offset int, limit int) (result []*model.AccountEducation, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAccountEducationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a accountEducationDo) Debug() IAccountEducationDo {
	return a.withDO(a.DO.Debug())
}

func (a accountEducationDo) WithContext(ctx context.Context) IAccountEducationDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a accountEducationDo) ReadDB() IAccountEducationDo {
	return a.Clauses(dbresolver.Read)
}

func (a accountEducationDo) WriteDB() IAccountEducationDo {
	return a.Clauses(dbresolver.Write)
}

func (a accountEducationDo) Session(config *gorm.Session) IAccountEducationDo {
	return a.withDO(a.DO.Session(config))
}

func (a accountEducationDo) Clauses(conds ...clause.Expression) IAccountEducationDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a accountEducationDo) Returning(value interface{}, columns ...string) IAccountEducationDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a accountEducationDo) Not(conds ...gen.Condition) IAccountEducationDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a accountEducationDo) Or(conds ...gen.Condition) IAccountEducationDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a accountEducationDo) Select(conds ...field.Expr) IAccountEducationDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a accountEducationDo) Where(conds ...gen.Condition) IAccountEducationDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a accountEducationDo) Order(conds ...field.Expr) IAccountEducationDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a accountEducationDo) Distinct(cols ...field.Expr) IAccountEducationDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a accountEducationDo) Omit(cols ...field.Expr) IAccountEducationDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a accountEducationDo) Join(table schema.Tabler, on ...field.Expr) IAccountEducationDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a accountEducationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAccountEducationDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a accountEducationDo) RightJoin(table schema.Tabler, on ...field.Expr) IAccountEducationDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a accountEducationDo) Group(cols ...field.Expr) IAccountEducationDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a accountEducationDo) Having(conds ...gen.Condition) IAccountEducationDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a accountEducationDo) Limit(limit int) IAccountEducationDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a accountEducationDo) Offset(offset int) IAccountEducationDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a accountEducationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAccountEducationDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a accountEducationDo) Unscoped() IAccountEducationDo {
	return a.withDO(a.DO.Unscoped())
}

func (a accountEducationDo) Create(values ...*model.AccountEducation) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a accountEducationDo) CreateInBatches(values []*model.AccountEducation, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a accountEducationDo) Save(values ...*model.AccountEducation) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a accountEducationDo) First() (*model.AccountEducation, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountEducation), nil
	}
}

func (a accountEducationDo) Take() (*model.AccountEducation, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountEducation), nil
	}
}

func (a accountEducationDo) Last() (*model.AccountEducation, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountEducation), nil
	}
}

func (a accountEducationDo) Find() ([]*model.AccountEducation, error) {
	result, err := a.DO.Find()
	return result.([]*model.AccountEducation), err
}

func (a accountEducationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AccountEducation, err error) {
	buf := make([]*model.AccountEducation, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a accountEducationDo) FindInBatches(result *[]*model.AccountEducation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a accountEducationDo) Attrs(attrs ...field.AssignExpr) IAccountEducationDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a accountEducationDo) Assign(attrs ...field.AssignExpr) IAccountEducationDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a accountEducationDo) Joins(fields ...field.RelationField) IAccountEducationDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a accountEducationDo) Preload(fields ...field.RelationField) IAccountEducationDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a accountEducationDo) FirstOrInit() (*model.AccountEducation, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountEducation), nil
	}
}

func (a accountEducationDo) FirstOrCreate() (*model.AccountEducation, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountEducation), nil
	}
}

func (a accountEducationDo) FindByPage(offset int, limit int) (result []*model.AccountEducation, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a accountEducationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a accountEducationDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a accountEducationDo) Delete(models ...*model.AccountEducation) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *accountEducationDo) withDO(do gen.Dao) *accountEducationDo {
	a.DO = *do.(*gen.DO)
	return a
}
