// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newAccountApply(db *gorm.DB, opts ...gen.DOOption) accountApply {
	_accountApply := accountApply{}

	_accountApply.accountApplyDo.UseDB(db, opts...)
	_accountApply.accountApplyDo.UseModel(&model.AccountApply{})

	tableName := _accountApply.accountApplyDo.TableName()
	_accountApply.ALL = field.NewAsterisk(tableName)
	_accountApply.ID = field.NewUint32(tableName, "id")
	_accountApply.AccountID = field.NewUint32(tableName, "account_id")
	_accountApply.IsPublic = field.NewInt32(tableName, "is_public")
	_accountApply.IsFirst = field.NewInt32(tableName, "is_first")
	_accountApply.CurrentState = field.NewString(tableName, "current_state")
	_accountApply.CurrentCity = field.NewString(tableName, "current_city")
	_accountApply.CurrentIndustry = field.NewString(tableName, "current_industry")
	_accountApply.CurrentCompany = field.NewString(tableName, "current_company")
	_accountApply.CurrentPositionTag = field.NewString(tableName, "current_position_tag")
	_accountApply.CurrentPosition = field.NewString(tableName, "current_position")
	_accountApply.DestCity = field.NewString(tableName, "dest_city")
	_accountApply.DestIndustry = field.NewString(tableName, "dest_industry")
	_accountApply.DestCompany = field.NewString(tableName, "dest_company")
	_accountApply.DestPositionTag = field.NewString(tableName, "dest_position_tag")
	_accountApply.DestPosition = field.NewString(tableName, "dest_position")
	_accountApply.DestSalary = field.NewString(tableName, "dest_salary")
	_accountApply.Education = field.NewString(tableName, "education")
	_accountApply.University = field.NewString(tableName, "university")
	_accountApply.Description = field.NewString(tableName, "description")
	_accountApply.Contact = field.NewString(tableName, "contact")
	_accountApply.HelpReward = field.NewUint32(tableName, "help_reward")
	_accountApply.HelpRewardToC = field.NewUint32(tableName, "help_reward_to_c")
	_accountApply.IsHelpRewardVisible = field.NewUint32(tableName, "is_help_reward_visible")
	_accountApply.CreatedTime = field.NewInt64(tableName, "created_time")
	_accountApply.UpdatedTime = field.NewInt64(tableName, "updated_time")
	_accountApply.Status = field.NewInt32(tableName, "status")

	_accountApply.fillFieldMap()

	return _accountApply
}

type accountApply struct {
	accountApplyDo

	ALL                 field.Asterisk
	ID                  field.Uint32
	AccountID           field.Uint32 // 用户id
	IsPublic            field.Int32  // 是否公开
	IsFirst             field.Int32  // 是否优先
	CurrentState        field.String
	CurrentCity         field.String
	CurrentIndustry     field.String
	CurrentCompany      field.String
	CurrentPositionTag  field.String // 当前职位类别
	CurrentPosition     field.String
	DestCity            field.String
	DestIndustry        field.String // 期望行业
	DestCompany         field.String
	DestPositionTag     field.String // 期望职位类别
	DestPosition        field.String
	DestSalary          field.String // 目标薪资
	Education           field.String
	University          field.String
	Description         field.String
	Contact             field.String // 联系方式
	HelpReward          field.Uint32 // 协助奖金
	HelpRewardToC       field.Uint32 // 协助奖金显示
	IsHelpRewardVisible field.Uint32 // 协助奖金是否显示
	CreatedTime         field.Int64  // 创建时间
	UpdatedTime         field.Int64  // 更新时间
	Status              field.Int32  // 求职状态

	fieldMap map[string]field.Expr
}

func (a accountApply) Table(newTableName string) *accountApply {
	a.accountApplyDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a accountApply) As(alias string) *accountApply {
	a.accountApplyDo.DO = *(a.accountApplyDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *accountApply) updateTableName(table string) *accountApply {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint32(table, "id")
	a.AccountID = field.NewUint32(table, "account_id")
	a.IsPublic = field.NewInt32(table, "is_public")
	a.IsFirst = field.NewInt32(table, "is_first")
	a.CurrentState = field.NewString(table, "current_state")
	a.CurrentCity = field.NewString(table, "current_city")
	a.CurrentIndustry = field.NewString(table, "current_industry")
	a.CurrentCompany = field.NewString(table, "current_company")
	a.CurrentPositionTag = field.NewString(table, "current_position_tag")
	a.CurrentPosition = field.NewString(table, "current_position")
	a.DestCity = field.NewString(table, "dest_city")
	a.DestIndustry = field.NewString(table, "dest_industry")
	a.DestCompany = field.NewString(table, "dest_company")
	a.DestPositionTag = field.NewString(table, "dest_position_tag")
	a.DestPosition = field.NewString(table, "dest_position")
	a.DestSalary = field.NewString(table, "dest_salary")
	a.Education = field.NewString(table, "education")
	a.University = field.NewString(table, "university")
	a.Description = field.NewString(table, "description")
	a.Contact = field.NewString(table, "contact")
	a.HelpReward = field.NewUint32(table, "help_reward")
	a.HelpRewardToC = field.NewUint32(table, "help_reward_to_c")
	a.IsHelpRewardVisible = field.NewUint32(table, "is_help_reward_visible")
	a.CreatedTime = field.NewInt64(table, "created_time")
	a.UpdatedTime = field.NewInt64(table, "updated_time")
	a.Status = field.NewInt32(table, "status")

	a.fillFieldMap()

	return a
}

func (a *accountApply) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *accountApply) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 26)
	a.fieldMap["id"] = a.ID
	a.fieldMap["account_id"] = a.AccountID
	a.fieldMap["is_public"] = a.IsPublic
	a.fieldMap["is_first"] = a.IsFirst
	a.fieldMap["current_state"] = a.CurrentState
	a.fieldMap["current_city"] = a.CurrentCity
	a.fieldMap["current_industry"] = a.CurrentIndustry
	a.fieldMap["current_company"] = a.CurrentCompany
	a.fieldMap["current_position_tag"] = a.CurrentPositionTag
	a.fieldMap["current_position"] = a.CurrentPosition
	a.fieldMap["dest_city"] = a.DestCity
	a.fieldMap["dest_industry"] = a.DestIndustry
	a.fieldMap["dest_company"] = a.DestCompany
	a.fieldMap["dest_position_tag"] = a.DestPositionTag
	a.fieldMap["dest_position"] = a.DestPosition
	a.fieldMap["dest_salary"] = a.DestSalary
	a.fieldMap["education"] = a.Education
	a.fieldMap["university"] = a.University
	a.fieldMap["description"] = a.Description
	a.fieldMap["contact"] = a.Contact
	a.fieldMap["help_reward"] = a.HelpReward
	a.fieldMap["help_reward_to_c"] = a.HelpRewardToC
	a.fieldMap["is_help_reward_visible"] = a.IsHelpRewardVisible
	a.fieldMap["created_time"] = a.CreatedTime
	a.fieldMap["updated_time"] = a.UpdatedTime
	a.fieldMap["status"] = a.Status
}

func (a accountApply) clone(db *gorm.DB) accountApply {
	a.accountApplyDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a accountApply) replaceDB(db *gorm.DB) accountApply {
	a.accountApplyDo.ReplaceDB(db)
	return a
}

type accountApplyDo struct{ gen.DO }

type IAccountApplyDo interface {
	gen.SubQuery
	Debug() IAccountApplyDo
	WithContext(ctx context.Context) IAccountApplyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAccountApplyDo
	WriteDB() IAccountApplyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAccountApplyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAccountApplyDo
	Not(conds ...gen.Condition) IAccountApplyDo
	Or(conds ...gen.Condition) IAccountApplyDo
	Select(conds ...field.Expr) IAccountApplyDo
	Where(conds ...gen.Condition) IAccountApplyDo
	Order(conds ...field.Expr) IAccountApplyDo
	Distinct(cols ...field.Expr) IAccountApplyDo
	Omit(cols ...field.Expr) IAccountApplyDo
	Join(table schema.Tabler, on ...field.Expr) IAccountApplyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAccountApplyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAccountApplyDo
	Group(cols ...field.Expr) IAccountApplyDo
	Having(conds ...gen.Condition) IAccountApplyDo
	Limit(limit int) IAccountApplyDo
	Offset(offset int) IAccountApplyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAccountApplyDo
	Unscoped() IAccountApplyDo
	Create(values ...*model.AccountApply) error
	CreateInBatches(values []*model.AccountApply, batchSize int) error
	Save(values ...*model.AccountApply) error
	First() (*model.AccountApply, error)
	Take() (*model.AccountApply, error)
	Last() (*model.AccountApply, error)
	Find() ([]*model.AccountApply, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AccountApply, err error)
	FindInBatches(result *[]*model.AccountApply, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AccountApply) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAccountApplyDo
	Assign(attrs ...field.AssignExpr) IAccountApplyDo
	Joins(fields ...field.RelationField) IAccountApplyDo
	Preload(fields ...field.RelationField) IAccountApplyDo
	FirstOrInit() (*model.AccountApply, error)
	FirstOrCreate() (*model.AccountApply, error)
	FindByPage(offset int, limit int) (result []*model.AccountApply, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAccountApplyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a accountApplyDo) Debug() IAccountApplyDo {
	return a.withDO(a.DO.Debug())
}

func (a accountApplyDo) WithContext(ctx context.Context) IAccountApplyDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a accountApplyDo) ReadDB() IAccountApplyDo {
	return a.Clauses(dbresolver.Read)
}

func (a accountApplyDo) WriteDB() IAccountApplyDo {
	return a.Clauses(dbresolver.Write)
}

func (a accountApplyDo) Session(config *gorm.Session) IAccountApplyDo {
	return a.withDO(a.DO.Session(config))
}

func (a accountApplyDo) Clauses(conds ...clause.Expression) IAccountApplyDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a accountApplyDo) Returning(value interface{}, columns ...string) IAccountApplyDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a accountApplyDo) Not(conds ...gen.Condition) IAccountApplyDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a accountApplyDo) Or(conds ...gen.Condition) IAccountApplyDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a accountApplyDo) Select(conds ...field.Expr) IAccountApplyDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a accountApplyDo) Where(conds ...gen.Condition) IAccountApplyDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a accountApplyDo) Order(conds ...field.Expr) IAccountApplyDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a accountApplyDo) Distinct(cols ...field.Expr) IAccountApplyDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a accountApplyDo) Omit(cols ...field.Expr) IAccountApplyDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a accountApplyDo) Join(table schema.Tabler, on ...field.Expr) IAccountApplyDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a accountApplyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAccountApplyDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a accountApplyDo) RightJoin(table schema.Tabler, on ...field.Expr) IAccountApplyDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a accountApplyDo) Group(cols ...field.Expr) IAccountApplyDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a accountApplyDo) Having(conds ...gen.Condition) IAccountApplyDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a accountApplyDo) Limit(limit int) IAccountApplyDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a accountApplyDo) Offset(offset int) IAccountApplyDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a accountApplyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAccountApplyDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a accountApplyDo) Unscoped() IAccountApplyDo {
	return a.withDO(a.DO.Unscoped())
}

func (a accountApplyDo) Create(values ...*model.AccountApply) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a accountApplyDo) CreateInBatches(values []*model.AccountApply, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a accountApplyDo) Save(values ...*model.AccountApply) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a accountApplyDo) First() (*model.AccountApply, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountApply), nil
	}
}

func (a accountApplyDo) Take() (*model.AccountApply, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountApply), nil
	}
}

func (a accountApplyDo) Last() (*model.AccountApply, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountApply), nil
	}
}

func (a accountApplyDo) Find() ([]*model.AccountApply, error) {
	result, err := a.DO.Find()
	return result.([]*model.AccountApply), err
}

func (a accountApplyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AccountApply, err error) {
	buf := make([]*model.AccountApply, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a accountApplyDo) FindInBatches(result *[]*model.AccountApply, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a accountApplyDo) Attrs(attrs ...field.AssignExpr) IAccountApplyDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a accountApplyDo) Assign(attrs ...field.AssignExpr) IAccountApplyDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a accountApplyDo) Joins(fields ...field.RelationField) IAccountApplyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a accountApplyDo) Preload(fields ...field.RelationField) IAccountApplyDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a accountApplyDo) FirstOrInit() (*model.AccountApply, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountApply), nil
	}
}

func (a accountApplyDo) FirstOrCreate() (*model.AccountApply, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountApply), nil
	}
}

func (a accountApplyDo) FindByPage(offset int, limit int) (result []*model.AccountApply, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a accountApplyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a accountApplyDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a accountApplyDo) Delete(models ...*model.AccountApply) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *accountApplyDo) withDO(do gen.Dao) *accountApplyDo {
	a.DO = *do.(*gen.DO)
	return a
}
