// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newAccountProject(db *gorm.DB, opts ...gen.DOOption) accountProject {
	_accountProject := accountProject{}

	_accountProject.accountProjectDo.UseDB(db, opts...)
	_accountProject.accountProjectDo.UseModel(&model.AccountProject{})

	tableName := _accountProject.accountProjectDo.TableName()
	_accountProject.ALL = field.NewAsterisk(tableName)
	_accountProject.ID = field.NewUint32(tableName, "id")
	_accountProject.AccountID = field.NewUint32(tableName, "account_id")
	_accountProject.Name = field.NewString(tableName, "name")
	_accountProject.Role = field.NewString(tableName, "role")
	_accountProject.StartTime = field.NewInt64(tableName, "start_time")
	_accountProject.EndTime = field.NewInt64(tableName, "end_time")
	_accountProject.Description = field.NewString(tableName, "description")
	_accountProject.Performance = field.NewString(tableName, "performance")
	_accountProject.Link = field.NewString(tableName, "link")
	_accountProject.CreatedTime = field.NewInt64(tableName, "created_time")
	_accountProject.UpdatedTime = field.NewInt64(tableName, "updated_time")

	_accountProject.fillFieldMap()

	return _accountProject
}

type accountProject struct {
	accountProjectDo

	ALL         field.Asterisk
	ID          field.Uint32
	AccountID   field.Uint32
	Name        field.String // 项目名称
	Role        field.String // 角色
	StartTime   field.Int64  // 项目时间 - 开始
	EndTime     field.Int64  // 项目时间-结束
	Description field.String // 描述
	Performance field.String // 业绩
	Link        field.String // 项目连接
	CreatedTime field.Int64  // 创建时间
	UpdatedTime field.Int64  // 更新时间

	fieldMap map[string]field.Expr
}

func (a accountProject) Table(newTableName string) *accountProject {
	a.accountProjectDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a accountProject) As(alias string) *accountProject {
	a.accountProjectDo.DO = *(a.accountProjectDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *accountProject) updateTableName(table string) *accountProject {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint32(table, "id")
	a.AccountID = field.NewUint32(table, "account_id")
	a.Name = field.NewString(table, "name")
	a.Role = field.NewString(table, "role")
	a.StartTime = field.NewInt64(table, "start_time")
	a.EndTime = field.NewInt64(table, "end_time")
	a.Description = field.NewString(table, "description")
	a.Performance = field.NewString(table, "performance")
	a.Link = field.NewString(table, "link")
	a.CreatedTime = field.NewInt64(table, "created_time")
	a.UpdatedTime = field.NewInt64(table, "updated_time")

	a.fillFieldMap()

	return a
}

func (a *accountProject) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *accountProject) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 11)
	a.fieldMap["id"] = a.ID
	a.fieldMap["account_id"] = a.AccountID
	a.fieldMap["name"] = a.Name
	a.fieldMap["role"] = a.Role
	a.fieldMap["start_time"] = a.StartTime
	a.fieldMap["end_time"] = a.EndTime
	a.fieldMap["description"] = a.Description
	a.fieldMap["performance"] = a.Performance
	a.fieldMap["link"] = a.Link
	a.fieldMap["created_time"] = a.CreatedTime
	a.fieldMap["updated_time"] = a.UpdatedTime
}

func (a accountProject) clone(db *gorm.DB) accountProject {
	a.accountProjectDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a accountProject) replaceDB(db *gorm.DB) accountProject {
	a.accountProjectDo.ReplaceDB(db)
	return a
}

type accountProjectDo struct{ gen.DO }

type IAccountProjectDo interface {
	gen.SubQuery
	Debug() IAccountProjectDo
	WithContext(ctx context.Context) IAccountProjectDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAccountProjectDo
	WriteDB() IAccountProjectDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAccountProjectDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAccountProjectDo
	Not(conds ...gen.Condition) IAccountProjectDo
	Or(conds ...gen.Condition) IAccountProjectDo
	Select(conds ...field.Expr) IAccountProjectDo
	Where(conds ...gen.Condition) IAccountProjectDo
	Order(conds ...field.Expr) IAccountProjectDo
	Distinct(cols ...field.Expr) IAccountProjectDo
	Omit(cols ...field.Expr) IAccountProjectDo
	Join(table schema.Tabler, on ...field.Expr) IAccountProjectDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAccountProjectDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAccountProjectDo
	Group(cols ...field.Expr) IAccountProjectDo
	Having(conds ...gen.Condition) IAccountProjectDo
	Limit(limit int) IAccountProjectDo
	Offset(offset int) IAccountProjectDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAccountProjectDo
	Unscoped() IAccountProjectDo
	Create(values ...*model.AccountProject) error
	CreateInBatches(values []*model.AccountProject, batchSize int) error
	Save(values ...*model.AccountProject) error
	First() (*model.AccountProject, error)
	Take() (*model.AccountProject, error)
	Last() (*model.AccountProject, error)
	Find() ([]*model.AccountProject, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AccountProject, err error)
	FindInBatches(result *[]*model.AccountProject, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AccountProject) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAccountProjectDo
	Assign(attrs ...field.AssignExpr) IAccountProjectDo
	Joins(fields ...field.RelationField) IAccountProjectDo
	Preload(fields ...field.RelationField) IAccountProjectDo
	FirstOrInit() (*model.AccountProject, error)
	FirstOrCreate() (*model.AccountProject, error)
	FindByPage(offset int, limit int) (result []*model.AccountProject, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAccountProjectDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a accountProjectDo) Debug() IAccountProjectDo {
	return a.withDO(a.DO.Debug())
}

func (a accountProjectDo) WithContext(ctx context.Context) IAccountProjectDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a accountProjectDo) ReadDB() IAccountProjectDo {
	return a.Clauses(dbresolver.Read)
}

func (a accountProjectDo) WriteDB() IAccountProjectDo {
	return a.Clauses(dbresolver.Write)
}

func (a accountProjectDo) Session(config *gorm.Session) IAccountProjectDo {
	return a.withDO(a.DO.Session(config))
}

func (a accountProjectDo) Clauses(conds ...clause.Expression) IAccountProjectDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a accountProjectDo) Returning(value interface{}, columns ...string) IAccountProjectDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a accountProjectDo) Not(conds ...gen.Condition) IAccountProjectDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a accountProjectDo) Or(conds ...gen.Condition) IAccountProjectDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a accountProjectDo) Select(conds ...field.Expr) IAccountProjectDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a accountProjectDo) Where(conds ...gen.Condition) IAccountProjectDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a accountProjectDo) Order(conds ...field.Expr) IAccountProjectDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a accountProjectDo) Distinct(cols ...field.Expr) IAccountProjectDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a accountProjectDo) Omit(cols ...field.Expr) IAccountProjectDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a accountProjectDo) Join(table schema.Tabler, on ...field.Expr) IAccountProjectDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a accountProjectDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAccountProjectDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a accountProjectDo) RightJoin(table schema.Tabler, on ...field.Expr) IAccountProjectDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a accountProjectDo) Group(cols ...field.Expr) IAccountProjectDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a accountProjectDo) Having(conds ...gen.Condition) IAccountProjectDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a accountProjectDo) Limit(limit int) IAccountProjectDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a accountProjectDo) Offset(offset int) IAccountProjectDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a accountProjectDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAccountProjectDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a accountProjectDo) Unscoped() IAccountProjectDo {
	return a.withDO(a.DO.Unscoped())
}

func (a accountProjectDo) Create(values ...*model.AccountProject) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a accountProjectDo) CreateInBatches(values []*model.AccountProject, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a accountProjectDo) Save(values ...*model.AccountProject) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a accountProjectDo) First() (*model.AccountProject, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountProject), nil
	}
}

func (a accountProjectDo) Take() (*model.AccountProject, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountProject), nil
	}
}

func (a accountProjectDo) Last() (*model.AccountProject, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountProject), nil
	}
}

func (a accountProjectDo) Find() ([]*model.AccountProject, error) {
	result, err := a.DO.Find()
	return result.([]*model.AccountProject), err
}

func (a accountProjectDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AccountProject, err error) {
	buf := make([]*model.AccountProject, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a accountProjectDo) FindInBatches(result *[]*model.AccountProject, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a accountProjectDo) Attrs(attrs ...field.AssignExpr) IAccountProjectDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a accountProjectDo) Assign(attrs ...field.AssignExpr) IAccountProjectDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a accountProjectDo) Joins(fields ...field.RelationField) IAccountProjectDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a accountProjectDo) Preload(fields ...field.RelationField) IAccountProjectDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a accountProjectDo) FirstOrInit() (*model.AccountProject, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountProject), nil
	}
}

func (a accountProjectDo) FirstOrCreate() (*model.AccountProject, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountProject), nil
	}
}

func (a accountProjectDo) FindByPage(offset int, limit int) (result []*model.AccountProject, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a accountProjectDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a accountProjectDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a accountProjectDo) Delete(models ...*model.AccountProject) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *accountProjectDo) withDO(do gen.Dao) *accountProjectDo {
	a.DO = *do.(*gen.DO)
	return a
}
