// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newAccountWork(db *gorm.DB, opts ...gen.DOOption) accountWork {
	_accountWork := accountWork{}

	_accountWork.accountWorkDo.UseDB(db, opts...)
	_accountWork.accountWorkDo.UseModel(&model.AccountWork{})

	tableName := _accountWork.accountWorkDo.TableName()
	_accountWork.ALL = field.NewAsterisk(tableName)
	_accountWork.ID = field.NewUint32(tableName, "id")
	_accountWork.AccountID = field.NewUint32(tableName, "account_id")
	_accountWork.Company = field.NewString(tableName, "company")
	_accountWork.Industry = field.NewString(tableName, "industry")
	_accountWork.StartTime = field.NewInt64(tableName, "start_time")
	_accountWork.EndTime = field.NewInt64(tableName, "end_time")
	_accountWork.Position = field.NewString(tableName, "position")
	_accountWork.Content = field.NewString(tableName, "content")
	_accountWork.Performance = field.NewString(tableName, "performance")
	_accountWork.Skills = field.NewString(tableName, "skills")
	_accountWork.CreatedTime = field.NewInt64(tableName, "created_time")
	_accountWork.UpdatedTime = field.NewInt64(tableName, "updated_time")

	_accountWork.fillFieldMap()

	return _accountWork
}

type accountWork struct {
	accountWorkDo

	ALL         field.Asterisk
	ID          field.Uint32
	AccountID   field.Uint32
	Company     field.String // 公司
	Industry    field.String // 行业
	StartTime   field.Int64  // 在职时间 - 开始
	EndTime     field.Int64  // 在职时间-结束
	Position    field.String
	Content     field.String // 工作内容
	Performance field.String // 工作业绩
	Skills      field.String // 技能
	CreatedTime field.Int64  // 创建时间
	UpdatedTime field.Int64  // 更新时间

	fieldMap map[string]field.Expr
}

func (a accountWork) Table(newTableName string) *accountWork {
	a.accountWorkDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a accountWork) As(alias string) *accountWork {
	a.accountWorkDo.DO = *(a.accountWorkDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *accountWork) updateTableName(table string) *accountWork {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint32(table, "id")
	a.AccountID = field.NewUint32(table, "account_id")
	a.Company = field.NewString(table, "company")
	a.Industry = field.NewString(table, "industry")
	a.StartTime = field.NewInt64(table, "start_time")
	a.EndTime = field.NewInt64(table, "end_time")
	a.Position = field.NewString(table, "position")
	a.Content = field.NewString(table, "content")
	a.Performance = field.NewString(table, "performance")
	a.Skills = field.NewString(table, "skills")
	a.CreatedTime = field.NewInt64(table, "created_time")
	a.UpdatedTime = field.NewInt64(table, "updated_time")

	a.fillFieldMap()

	return a
}

func (a *accountWork) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *accountWork) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 12)
	a.fieldMap["id"] = a.ID
	a.fieldMap["account_id"] = a.AccountID
	a.fieldMap["company"] = a.Company
	a.fieldMap["industry"] = a.Industry
	a.fieldMap["start_time"] = a.StartTime
	a.fieldMap["end_time"] = a.EndTime
	a.fieldMap["position"] = a.Position
	a.fieldMap["content"] = a.Content
	a.fieldMap["performance"] = a.Performance
	a.fieldMap["skills"] = a.Skills
	a.fieldMap["created_time"] = a.CreatedTime
	a.fieldMap["updated_time"] = a.UpdatedTime
}

func (a accountWork) clone(db *gorm.DB) accountWork {
	a.accountWorkDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a accountWork) replaceDB(db *gorm.DB) accountWork {
	a.accountWorkDo.ReplaceDB(db)
	return a
}

type accountWorkDo struct{ gen.DO }

type IAccountWorkDo interface {
	gen.SubQuery
	Debug() IAccountWorkDo
	WithContext(ctx context.Context) IAccountWorkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAccountWorkDo
	WriteDB() IAccountWorkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAccountWorkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAccountWorkDo
	Not(conds ...gen.Condition) IAccountWorkDo
	Or(conds ...gen.Condition) IAccountWorkDo
	Select(conds ...field.Expr) IAccountWorkDo
	Where(conds ...gen.Condition) IAccountWorkDo
	Order(conds ...field.Expr) IAccountWorkDo
	Distinct(cols ...field.Expr) IAccountWorkDo
	Omit(cols ...field.Expr) IAccountWorkDo
	Join(table schema.Tabler, on ...field.Expr) IAccountWorkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAccountWorkDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAccountWorkDo
	Group(cols ...field.Expr) IAccountWorkDo
	Having(conds ...gen.Condition) IAccountWorkDo
	Limit(limit int) IAccountWorkDo
	Offset(offset int) IAccountWorkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAccountWorkDo
	Unscoped() IAccountWorkDo
	Create(values ...*model.AccountWork) error
	CreateInBatches(values []*model.AccountWork, batchSize int) error
	Save(values ...*model.AccountWork) error
	First() (*model.AccountWork, error)
	Take() (*model.AccountWork, error)
	Last() (*model.AccountWork, error)
	Find() ([]*model.AccountWork, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AccountWork, err error)
	FindInBatches(result *[]*model.AccountWork, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AccountWork) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAccountWorkDo
	Assign(attrs ...field.AssignExpr) IAccountWorkDo
	Joins(fields ...field.RelationField) IAccountWorkDo
	Preload(fields ...field.RelationField) IAccountWorkDo
	FirstOrInit() (*model.AccountWork, error)
	FirstOrCreate() (*model.AccountWork, error)
	FindByPage(offset int, limit int) (result []*model.AccountWork, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAccountWorkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a accountWorkDo) Debug() IAccountWorkDo {
	return a.withDO(a.DO.Debug())
}

func (a accountWorkDo) WithContext(ctx context.Context) IAccountWorkDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a accountWorkDo) ReadDB() IAccountWorkDo {
	return a.Clauses(dbresolver.Read)
}

func (a accountWorkDo) WriteDB() IAccountWorkDo {
	return a.Clauses(dbresolver.Write)
}

func (a accountWorkDo) Session(config *gorm.Session) IAccountWorkDo {
	return a.withDO(a.DO.Session(config))
}

func (a accountWorkDo) Clauses(conds ...clause.Expression) IAccountWorkDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a accountWorkDo) Returning(value interface{}, columns ...string) IAccountWorkDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a accountWorkDo) Not(conds ...gen.Condition) IAccountWorkDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a accountWorkDo) Or(conds ...gen.Condition) IAccountWorkDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a accountWorkDo) Select(conds ...field.Expr) IAccountWorkDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a accountWorkDo) Where(conds ...gen.Condition) IAccountWorkDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a accountWorkDo) Order(conds ...field.Expr) IAccountWorkDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a accountWorkDo) Distinct(cols ...field.Expr) IAccountWorkDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a accountWorkDo) Omit(cols ...field.Expr) IAccountWorkDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a accountWorkDo) Join(table schema.Tabler, on ...field.Expr) IAccountWorkDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a accountWorkDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAccountWorkDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a accountWorkDo) RightJoin(table schema.Tabler, on ...field.Expr) IAccountWorkDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a accountWorkDo) Group(cols ...field.Expr) IAccountWorkDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a accountWorkDo) Having(conds ...gen.Condition) IAccountWorkDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a accountWorkDo) Limit(limit int) IAccountWorkDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a accountWorkDo) Offset(offset int) IAccountWorkDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a accountWorkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAccountWorkDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a accountWorkDo) Unscoped() IAccountWorkDo {
	return a.withDO(a.DO.Unscoped())
}

func (a accountWorkDo) Create(values ...*model.AccountWork) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a accountWorkDo) CreateInBatches(values []*model.AccountWork, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a accountWorkDo) Save(values ...*model.AccountWork) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a accountWorkDo) First() (*model.AccountWork, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountWork), nil
	}
}

func (a accountWorkDo) Take() (*model.AccountWork, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountWork), nil
	}
}

func (a accountWorkDo) Last() (*model.AccountWork, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountWork), nil
	}
}

func (a accountWorkDo) Find() ([]*model.AccountWork, error) {
	result, err := a.DO.Find()
	return result.([]*model.AccountWork), err
}

func (a accountWorkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AccountWork, err error) {
	buf := make([]*model.AccountWork, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a accountWorkDo) FindInBatches(result *[]*model.AccountWork, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a accountWorkDo) Attrs(attrs ...field.AssignExpr) IAccountWorkDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a accountWorkDo) Assign(attrs ...field.AssignExpr) IAccountWorkDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a accountWorkDo) Joins(fields ...field.RelationField) IAccountWorkDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a accountWorkDo) Preload(fields ...field.RelationField) IAccountWorkDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a accountWorkDo) FirstOrInit() (*model.AccountWork, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountWork), nil
	}
}

func (a accountWorkDo) FirstOrCreate() (*model.AccountWork, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AccountWork), nil
	}
}

func (a accountWorkDo) FindByPage(offset int, limit int) (result []*model.AccountWork, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a accountWorkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a accountWorkDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a accountWorkDo) Delete(models ...*model.AccountWork) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *accountWorkDo) withDO(do gen.Dao) *accountWorkDo {
	a.DO = *do.(*gen.DO)
	return a
}
