// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newApplyNoDirect(db *gorm.DB, opts ...gen.DOOption) applyNoDirect {
	_applyNoDirect := applyNoDirect{}

	_applyNoDirect.applyNoDirectDo.UseDB(db, opts...)
	_applyNoDirect.applyNoDirectDo.UseModel(&model.ApplyNoDirect{})

	tableName := _applyNoDirect.applyNoDirectDo.TableName()
	_applyNoDirect.ALL = field.NewAsterisk(tableName)
	_applyNoDirect.UserID = field.NewInt32(tableName, "user_id")
	_applyNoDirect.ApplyID = field.NewInt32(tableName, "apply_id")

	_applyNoDirect.fillFieldMap()

	return _applyNoDirect
}

type applyNoDirect struct {
	applyNoDirectDo

	ALL     field.Asterisk
	UserID  field.Int32
	ApplyID field.Int32

	fieldMap map[string]field.Expr
}

func (a applyNoDirect) Table(newTableName string) *applyNoDirect {
	a.applyNoDirectDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a applyNoDirect) As(alias string) *applyNoDirect {
	a.applyNoDirectDo.DO = *(a.applyNoDirectDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *applyNoDirect) updateTableName(table string) *applyNoDirect {
	a.ALL = field.NewAsterisk(table)
	a.UserID = field.NewInt32(table, "user_id")
	a.ApplyID = field.NewInt32(table, "apply_id")

	a.fillFieldMap()

	return a
}

func (a *applyNoDirect) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *applyNoDirect) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 2)
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["apply_id"] = a.ApplyID
}

func (a applyNoDirect) clone(db *gorm.DB) applyNoDirect {
	a.applyNoDirectDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a applyNoDirect) replaceDB(db *gorm.DB) applyNoDirect {
	a.applyNoDirectDo.ReplaceDB(db)
	return a
}

type applyNoDirectDo struct{ gen.DO }

type IApplyNoDirectDo interface {
	gen.SubQuery
	Debug() IApplyNoDirectDo
	WithContext(ctx context.Context) IApplyNoDirectDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IApplyNoDirectDo
	WriteDB() IApplyNoDirectDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IApplyNoDirectDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IApplyNoDirectDo
	Not(conds ...gen.Condition) IApplyNoDirectDo
	Or(conds ...gen.Condition) IApplyNoDirectDo
	Select(conds ...field.Expr) IApplyNoDirectDo
	Where(conds ...gen.Condition) IApplyNoDirectDo
	Order(conds ...field.Expr) IApplyNoDirectDo
	Distinct(cols ...field.Expr) IApplyNoDirectDo
	Omit(cols ...field.Expr) IApplyNoDirectDo
	Join(table schema.Tabler, on ...field.Expr) IApplyNoDirectDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IApplyNoDirectDo
	RightJoin(table schema.Tabler, on ...field.Expr) IApplyNoDirectDo
	Group(cols ...field.Expr) IApplyNoDirectDo
	Having(conds ...gen.Condition) IApplyNoDirectDo
	Limit(limit int) IApplyNoDirectDo
	Offset(offset int) IApplyNoDirectDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IApplyNoDirectDo
	Unscoped() IApplyNoDirectDo
	Create(values ...*model.ApplyNoDirect) error
	CreateInBatches(values []*model.ApplyNoDirect, batchSize int) error
	Save(values ...*model.ApplyNoDirect) error
	First() (*model.ApplyNoDirect, error)
	Take() (*model.ApplyNoDirect, error)
	Last() (*model.ApplyNoDirect, error)
	Find() ([]*model.ApplyNoDirect, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ApplyNoDirect, err error)
	FindInBatches(result *[]*model.ApplyNoDirect, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ApplyNoDirect) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IApplyNoDirectDo
	Assign(attrs ...field.AssignExpr) IApplyNoDirectDo
	Joins(fields ...field.RelationField) IApplyNoDirectDo
	Preload(fields ...field.RelationField) IApplyNoDirectDo
	FirstOrInit() (*model.ApplyNoDirect, error)
	FirstOrCreate() (*model.ApplyNoDirect, error)
	FindByPage(offset int, limit int) (result []*model.ApplyNoDirect, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IApplyNoDirectDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a applyNoDirectDo) Debug() IApplyNoDirectDo {
	return a.withDO(a.DO.Debug())
}

func (a applyNoDirectDo) WithContext(ctx context.Context) IApplyNoDirectDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a applyNoDirectDo) ReadDB() IApplyNoDirectDo {
	return a.Clauses(dbresolver.Read)
}

func (a applyNoDirectDo) WriteDB() IApplyNoDirectDo {
	return a.Clauses(dbresolver.Write)
}

func (a applyNoDirectDo) Session(config *gorm.Session) IApplyNoDirectDo {
	return a.withDO(a.DO.Session(config))
}

func (a applyNoDirectDo) Clauses(conds ...clause.Expression) IApplyNoDirectDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a applyNoDirectDo) Returning(value interface{}, columns ...string) IApplyNoDirectDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a applyNoDirectDo) Not(conds ...gen.Condition) IApplyNoDirectDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a applyNoDirectDo) Or(conds ...gen.Condition) IApplyNoDirectDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a applyNoDirectDo) Select(conds ...field.Expr) IApplyNoDirectDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a applyNoDirectDo) Where(conds ...gen.Condition) IApplyNoDirectDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a applyNoDirectDo) Order(conds ...field.Expr) IApplyNoDirectDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a applyNoDirectDo) Distinct(cols ...field.Expr) IApplyNoDirectDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a applyNoDirectDo) Omit(cols ...field.Expr) IApplyNoDirectDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a applyNoDirectDo) Join(table schema.Tabler, on ...field.Expr) IApplyNoDirectDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a applyNoDirectDo) LeftJoin(table schema.Tabler, on ...field.Expr) IApplyNoDirectDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a applyNoDirectDo) RightJoin(table schema.Tabler, on ...field.Expr) IApplyNoDirectDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a applyNoDirectDo) Group(cols ...field.Expr) IApplyNoDirectDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a applyNoDirectDo) Having(conds ...gen.Condition) IApplyNoDirectDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a applyNoDirectDo) Limit(limit int) IApplyNoDirectDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a applyNoDirectDo) Offset(offset int) IApplyNoDirectDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a applyNoDirectDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IApplyNoDirectDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a applyNoDirectDo) Unscoped() IApplyNoDirectDo {
	return a.withDO(a.DO.Unscoped())
}

func (a applyNoDirectDo) Create(values ...*model.ApplyNoDirect) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a applyNoDirectDo) CreateInBatches(values []*model.ApplyNoDirect, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a applyNoDirectDo) Save(values ...*model.ApplyNoDirect) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a applyNoDirectDo) First() (*model.ApplyNoDirect, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApplyNoDirect), nil
	}
}

func (a applyNoDirectDo) Take() (*model.ApplyNoDirect, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApplyNoDirect), nil
	}
}

func (a applyNoDirectDo) Last() (*model.ApplyNoDirect, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApplyNoDirect), nil
	}
}

func (a applyNoDirectDo) Find() ([]*model.ApplyNoDirect, error) {
	result, err := a.DO.Find()
	return result.([]*model.ApplyNoDirect), err
}

func (a applyNoDirectDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ApplyNoDirect, err error) {
	buf := make([]*model.ApplyNoDirect, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a applyNoDirectDo) FindInBatches(result *[]*model.ApplyNoDirect, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a applyNoDirectDo) Attrs(attrs ...field.AssignExpr) IApplyNoDirectDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a applyNoDirectDo) Assign(attrs ...field.AssignExpr) IApplyNoDirectDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a applyNoDirectDo) Joins(fields ...field.RelationField) IApplyNoDirectDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a applyNoDirectDo) Preload(fields ...field.RelationField) IApplyNoDirectDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a applyNoDirectDo) FirstOrInit() (*model.ApplyNoDirect, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApplyNoDirect), nil
	}
}

func (a applyNoDirectDo) FirstOrCreate() (*model.ApplyNoDirect, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ApplyNoDirect), nil
	}
}

func (a applyNoDirectDo) FindByPage(offset int, limit int) (result []*model.ApplyNoDirect, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a applyNoDirectDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a applyNoDirectDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a applyNoDirectDo) Delete(models ...*model.ApplyNoDirect) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *applyNoDirectDo) withDO(do gen.Dao) *applyNoDirectDo {
	a.DO = *do.(*gen.DO)
	return a
}
