// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newCompanyInfo(db *gorm.DB, opts ...gen.DOOption) companyInfo {
	_companyInfo := companyInfo{}

	_companyInfo.companyInfoDo.UseDB(db, opts...)
	_companyInfo.companyInfoDo.UseModel(&model.CompanyInfo{})

	tableName := _companyInfo.companyInfoDo.TableName()
	_companyInfo.ALL = field.NewAsterisk(tableName)
	_companyInfo.ID = field.NewUint32(tableName, "id")
	_companyInfo.AdminID = field.NewUint32(tableName, "admin_id")
	_companyInfo.Name = field.NewString(tableName, "name")
	_companyInfo.FakeName = field.NewString(tableName, "fake_name")
	_companyInfo.Linkman = field.NewString(tableName, "linkman")
	_companyInfo.LinkmanPosition = field.NewString(tableName, "linkman_position")
	_companyInfo.LinkmanPhone = field.NewString(tableName, "linkman_phone")
	_companyInfo.Email = field.NewString(tableName, "email")
	_companyInfo.CityID = field.NewUint32(tableName, "city_id")
	_companyInfo.DistrictID = field.NewUint32(tableName, "district_id")
	_companyInfo.IndustryPath = field.NewString(tableName, "industry_path")
	_companyInfo.IndustryID = field.NewUint32(tableName, "industry_id")
	_companyInfo.CompanyscaleID = field.NewUint32(tableName, "companyscale_id")
	_companyInfo.CompanystageID = field.NewUint32(tableName, "companystage_id")
	_companyInfo.Companysynopsis = field.NewString(tableName, "companysynopsis")
	_companyInfo.Icon = field.NewString(tableName, "icon")
	_companyInfo.SimpleName = field.NewString(tableName, "simple_name")
	_companyInfo.EditCompanysynopsis = field.NewString(tableName, "edit_companysynopsis")
	_companyInfo.Address = field.NewString(tableName, "address")
	_companyInfo.Website = field.NewString(tableName, "website")
	_companyInfo.Summary = field.NewString(tableName, "summary")
	_companyInfo.IsTop = field.NewUint32(tableName, "is_top")
	_companyInfo.Tags = field.NewString(tableName, "tags")
	_companyInfo.IsOpen = field.NewUint32(tableName, "is_open")
	_companyInfo.Articles = field.NewString(tableName, "articles")
	_companyInfo.Sort = field.NewUint32(tableName, "sort")

	_companyInfo.fillFieldMap()

	return _companyInfo
}

type companyInfo struct {
	companyInfoDo

	ALL                 field.Asterisk
	ID                  field.Uint32
	AdminID             field.Uint32
	Name                field.String
	FakeName            field.String // 假名字
	Linkman             field.String
	LinkmanPosition     field.String
	LinkmanPhone        field.String
	Email               field.String
	CityID              field.Uint32
	DistrictID          field.Uint32
	IndustryPath        field.String
	IndustryID          field.Uint32
	CompanyscaleID      field.Uint32
	CompanystageID      field.Uint32
	Companysynopsis     field.String
	Icon                field.String
	SimpleName          field.String
	EditCompanysynopsis field.String
	Address             field.String
	Website             field.String
	Summary             field.String // 用于微信分享的摘要
	IsTop               field.Uint32
	Tags                field.String // 标签
	IsOpen              field.Uint32
	Articles            field.String
	Sort                field.Uint32

	fieldMap map[string]field.Expr
}

func (c companyInfo) Table(newTableName string) *companyInfo {
	c.companyInfoDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c companyInfo) As(alias string) *companyInfo {
	c.companyInfoDo.DO = *(c.companyInfoDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *companyInfo) updateTableName(table string) *companyInfo {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint32(table, "id")
	c.AdminID = field.NewUint32(table, "admin_id")
	c.Name = field.NewString(table, "name")
	c.FakeName = field.NewString(table, "fake_name")
	c.Linkman = field.NewString(table, "linkman")
	c.LinkmanPosition = field.NewString(table, "linkman_position")
	c.LinkmanPhone = field.NewString(table, "linkman_phone")
	c.Email = field.NewString(table, "email")
	c.CityID = field.NewUint32(table, "city_id")
	c.DistrictID = field.NewUint32(table, "district_id")
	c.IndustryPath = field.NewString(table, "industry_path")
	c.IndustryID = field.NewUint32(table, "industry_id")
	c.CompanyscaleID = field.NewUint32(table, "companyscale_id")
	c.CompanystageID = field.NewUint32(table, "companystage_id")
	c.Companysynopsis = field.NewString(table, "companysynopsis")
	c.Icon = field.NewString(table, "icon")
	c.SimpleName = field.NewString(table, "simple_name")
	c.EditCompanysynopsis = field.NewString(table, "edit_companysynopsis")
	c.Address = field.NewString(table, "address")
	c.Website = field.NewString(table, "website")
	c.Summary = field.NewString(table, "summary")
	c.IsTop = field.NewUint32(table, "is_top")
	c.Tags = field.NewString(table, "tags")
	c.IsOpen = field.NewUint32(table, "is_open")
	c.Articles = field.NewString(table, "articles")
	c.Sort = field.NewUint32(table, "sort")

	c.fillFieldMap()

	return c
}

func (c *companyInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *companyInfo) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 26)
	c.fieldMap["id"] = c.ID
	c.fieldMap["admin_id"] = c.AdminID
	c.fieldMap["name"] = c.Name
	c.fieldMap["fake_name"] = c.FakeName
	c.fieldMap["linkman"] = c.Linkman
	c.fieldMap["linkman_position"] = c.LinkmanPosition
	c.fieldMap["linkman_phone"] = c.LinkmanPhone
	c.fieldMap["email"] = c.Email
	c.fieldMap["city_id"] = c.CityID
	c.fieldMap["district_id"] = c.DistrictID
	c.fieldMap["industry_path"] = c.IndustryPath
	c.fieldMap["industry_id"] = c.IndustryID
	c.fieldMap["companyscale_id"] = c.CompanyscaleID
	c.fieldMap["companystage_id"] = c.CompanystageID
	c.fieldMap["companysynopsis"] = c.Companysynopsis
	c.fieldMap["icon"] = c.Icon
	c.fieldMap["simple_name"] = c.SimpleName
	c.fieldMap["edit_companysynopsis"] = c.EditCompanysynopsis
	c.fieldMap["address"] = c.Address
	c.fieldMap["website"] = c.Website
	c.fieldMap["summary"] = c.Summary
	c.fieldMap["is_top"] = c.IsTop
	c.fieldMap["tags"] = c.Tags
	c.fieldMap["is_open"] = c.IsOpen
	c.fieldMap["articles"] = c.Articles
	c.fieldMap["sort"] = c.Sort
}

func (c companyInfo) clone(db *gorm.DB) companyInfo {
	c.companyInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c companyInfo) replaceDB(db *gorm.DB) companyInfo {
	c.companyInfoDo.ReplaceDB(db)
	return c
}

type companyInfoDo struct{ gen.DO }

type ICompanyInfoDo interface {
	gen.SubQuery
	Debug() ICompanyInfoDo
	WithContext(ctx context.Context) ICompanyInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICompanyInfoDo
	WriteDB() ICompanyInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICompanyInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICompanyInfoDo
	Not(conds ...gen.Condition) ICompanyInfoDo
	Or(conds ...gen.Condition) ICompanyInfoDo
	Select(conds ...field.Expr) ICompanyInfoDo
	Where(conds ...gen.Condition) ICompanyInfoDo
	Order(conds ...field.Expr) ICompanyInfoDo
	Distinct(cols ...field.Expr) ICompanyInfoDo
	Omit(cols ...field.Expr) ICompanyInfoDo
	Join(table schema.Tabler, on ...field.Expr) ICompanyInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICompanyInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICompanyInfoDo
	Group(cols ...field.Expr) ICompanyInfoDo
	Having(conds ...gen.Condition) ICompanyInfoDo
	Limit(limit int) ICompanyInfoDo
	Offset(offset int) ICompanyInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICompanyInfoDo
	Unscoped() ICompanyInfoDo
	Create(values ...*model.CompanyInfo) error
	CreateInBatches(values []*model.CompanyInfo, batchSize int) error
	Save(values ...*model.CompanyInfo) error
	First() (*model.CompanyInfo, error)
	Take() (*model.CompanyInfo, error)
	Last() (*model.CompanyInfo, error)
	Find() ([]*model.CompanyInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CompanyInfo, err error)
	FindInBatches(result *[]*model.CompanyInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CompanyInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICompanyInfoDo
	Assign(attrs ...field.AssignExpr) ICompanyInfoDo
	Joins(fields ...field.RelationField) ICompanyInfoDo
	Preload(fields ...field.RelationField) ICompanyInfoDo
	FirstOrInit() (*model.CompanyInfo, error)
	FirstOrCreate() (*model.CompanyInfo, error)
	FindByPage(offset int, limit int) (result []*model.CompanyInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICompanyInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c companyInfoDo) Debug() ICompanyInfoDo {
	return c.withDO(c.DO.Debug())
}

func (c companyInfoDo) WithContext(ctx context.Context) ICompanyInfoDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c companyInfoDo) ReadDB() ICompanyInfoDo {
	return c.Clauses(dbresolver.Read)
}

func (c companyInfoDo) WriteDB() ICompanyInfoDo {
	return c.Clauses(dbresolver.Write)
}

func (c companyInfoDo) Session(config *gorm.Session) ICompanyInfoDo {
	return c.withDO(c.DO.Session(config))
}

func (c companyInfoDo) Clauses(conds ...clause.Expression) ICompanyInfoDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c companyInfoDo) Returning(value interface{}, columns ...string) ICompanyInfoDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c companyInfoDo) Not(conds ...gen.Condition) ICompanyInfoDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c companyInfoDo) Or(conds ...gen.Condition) ICompanyInfoDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c companyInfoDo) Select(conds ...field.Expr) ICompanyInfoDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c companyInfoDo) Where(conds ...gen.Condition) ICompanyInfoDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c companyInfoDo) Order(conds ...field.Expr) ICompanyInfoDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c companyInfoDo) Distinct(cols ...field.Expr) ICompanyInfoDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c companyInfoDo) Omit(cols ...field.Expr) ICompanyInfoDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c companyInfoDo) Join(table schema.Tabler, on ...field.Expr) ICompanyInfoDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c companyInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICompanyInfoDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c companyInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) ICompanyInfoDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c companyInfoDo) Group(cols ...field.Expr) ICompanyInfoDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c companyInfoDo) Having(conds ...gen.Condition) ICompanyInfoDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c companyInfoDo) Limit(limit int) ICompanyInfoDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c companyInfoDo) Offset(offset int) ICompanyInfoDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c companyInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICompanyInfoDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c companyInfoDo) Unscoped() ICompanyInfoDo {
	return c.withDO(c.DO.Unscoped())
}

func (c companyInfoDo) Create(values ...*model.CompanyInfo) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c companyInfoDo) CreateInBatches(values []*model.CompanyInfo, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c companyInfoDo) Save(values ...*model.CompanyInfo) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c companyInfoDo) First() (*model.CompanyInfo, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CompanyInfo), nil
	}
}

func (c companyInfoDo) Take() (*model.CompanyInfo, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CompanyInfo), nil
	}
}

func (c companyInfoDo) Last() (*model.CompanyInfo, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CompanyInfo), nil
	}
}

func (c companyInfoDo) Find() ([]*model.CompanyInfo, error) {
	result, err := c.DO.Find()
	return result.([]*model.CompanyInfo), err
}

func (c companyInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CompanyInfo, err error) {
	buf := make([]*model.CompanyInfo, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c companyInfoDo) FindInBatches(result *[]*model.CompanyInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c companyInfoDo) Attrs(attrs ...field.AssignExpr) ICompanyInfoDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c companyInfoDo) Assign(attrs ...field.AssignExpr) ICompanyInfoDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c companyInfoDo) Joins(fields ...field.RelationField) ICompanyInfoDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c companyInfoDo) Preload(fields ...field.RelationField) ICompanyInfoDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c companyInfoDo) FirstOrInit() (*model.CompanyInfo, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CompanyInfo), nil
	}
}

func (c companyInfoDo) FirstOrCreate() (*model.CompanyInfo, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CompanyInfo), nil
	}
}

func (c companyInfoDo) FindByPage(offset int, limit int) (result []*model.CompanyInfo, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c companyInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c companyInfoDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c companyInfoDo) Delete(models ...*model.CompanyInfo) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *companyInfoDo) withDO(do gen.Dao) *companyInfoDo {
	c.DO = *do.(*gen.DO)
	return c
}
