// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newDataPositionTag(db *gorm.DB, opts ...gen.DOOption) dataPositionTag {
	_dataPositionTag := dataPositionTag{}

	_dataPositionTag.dataPositionTagDo.UseDB(db, opts...)
	_dataPositionTag.dataPositionTagDo.UseModel(&model.DataPositionTag{})

	tableName := _dataPositionTag.dataPositionTagDo.TableName()
	_dataPositionTag.ALL = field.NewAsterisk(tableName)
	_dataPositionTag.ID = field.NewUint32(tableName, "id")
	_dataPositionTag.Pid = field.NewUint32(tableName, "pid")
	_dataPositionTag.Level = field.NewUint32(tableName, "level")
	_dataPositionTag.Name = field.NewString(tableName, "name")
	_dataPositionTag.Path = field.NewString(tableName, "path")
	_dataPositionTag.Sort = field.NewUint32(tableName, "sort")

	_dataPositionTag.fillFieldMap()

	return _dataPositionTag
}

type dataPositionTag struct {
	dataPositionTagDo

	ALL   field.Asterisk
	ID    field.Uint32
	Pid   field.Uint32
	Level field.Uint32
	Name  field.String
	Path  field.String
	Sort  field.Uint32

	fieldMap map[string]field.Expr
}

func (d dataPositionTag) Table(newTableName string) *dataPositionTag {
	d.dataPositionTagDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dataPositionTag) As(alias string) *dataPositionTag {
	d.dataPositionTagDo.DO = *(d.dataPositionTagDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dataPositionTag) updateTableName(table string) *dataPositionTag {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint32(table, "id")
	d.Pid = field.NewUint32(table, "pid")
	d.Level = field.NewUint32(table, "level")
	d.Name = field.NewString(table, "name")
	d.Path = field.NewString(table, "path")
	d.Sort = field.NewUint32(table, "sort")

	d.fillFieldMap()

	return d
}

func (d *dataPositionTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dataPositionTag) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 6)
	d.fieldMap["id"] = d.ID
	d.fieldMap["pid"] = d.Pid
	d.fieldMap["level"] = d.Level
	d.fieldMap["name"] = d.Name
	d.fieldMap["path"] = d.Path
	d.fieldMap["sort"] = d.Sort
}

func (d dataPositionTag) clone(db *gorm.DB) dataPositionTag {
	d.dataPositionTagDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dataPositionTag) replaceDB(db *gorm.DB) dataPositionTag {
	d.dataPositionTagDo.ReplaceDB(db)
	return d
}

type dataPositionTagDo struct{ gen.DO }

type IDataPositionTagDo interface {
	gen.SubQuery
	Debug() IDataPositionTagDo
	WithContext(ctx context.Context) IDataPositionTagDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDataPositionTagDo
	WriteDB() IDataPositionTagDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDataPositionTagDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDataPositionTagDo
	Not(conds ...gen.Condition) IDataPositionTagDo
	Or(conds ...gen.Condition) IDataPositionTagDo
	Select(conds ...field.Expr) IDataPositionTagDo
	Where(conds ...gen.Condition) IDataPositionTagDo
	Order(conds ...field.Expr) IDataPositionTagDo
	Distinct(cols ...field.Expr) IDataPositionTagDo
	Omit(cols ...field.Expr) IDataPositionTagDo
	Join(table schema.Tabler, on ...field.Expr) IDataPositionTagDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDataPositionTagDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDataPositionTagDo
	Group(cols ...field.Expr) IDataPositionTagDo
	Having(conds ...gen.Condition) IDataPositionTagDo
	Limit(limit int) IDataPositionTagDo
	Offset(offset int) IDataPositionTagDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDataPositionTagDo
	Unscoped() IDataPositionTagDo
	Create(values ...*model.DataPositionTag) error
	CreateInBatches(values []*model.DataPositionTag, batchSize int) error
	Save(values ...*model.DataPositionTag) error
	First() (*model.DataPositionTag, error)
	Take() (*model.DataPositionTag, error)
	Last() (*model.DataPositionTag, error)
	Find() ([]*model.DataPositionTag, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DataPositionTag, err error)
	FindInBatches(result *[]*model.DataPositionTag, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DataPositionTag) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDataPositionTagDo
	Assign(attrs ...field.AssignExpr) IDataPositionTagDo
	Joins(fields ...field.RelationField) IDataPositionTagDo
	Preload(fields ...field.RelationField) IDataPositionTagDo
	FirstOrInit() (*model.DataPositionTag, error)
	FirstOrCreate() (*model.DataPositionTag, error)
	FindByPage(offset int, limit int) (result []*model.DataPositionTag, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDataPositionTagDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dataPositionTagDo) Debug() IDataPositionTagDo {
	return d.withDO(d.DO.Debug())
}

func (d dataPositionTagDo) WithContext(ctx context.Context) IDataPositionTagDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dataPositionTagDo) ReadDB() IDataPositionTagDo {
	return d.Clauses(dbresolver.Read)
}

func (d dataPositionTagDo) WriteDB() IDataPositionTagDo {
	return d.Clauses(dbresolver.Write)
}

func (d dataPositionTagDo) Session(config *gorm.Session) IDataPositionTagDo {
	return d.withDO(d.DO.Session(config))
}

func (d dataPositionTagDo) Clauses(conds ...clause.Expression) IDataPositionTagDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dataPositionTagDo) Returning(value interface{}, columns ...string) IDataPositionTagDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dataPositionTagDo) Not(conds ...gen.Condition) IDataPositionTagDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dataPositionTagDo) Or(conds ...gen.Condition) IDataPositionTagDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dataPositionTagDo) Select(conds ...field.Expr) IDataPositionTagDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dataPositionTagDo) Where(conds ...gen.Condition) IDataPositionTagDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dataPositionTagDo) Order(conds ...field.Expr) IDataPositionTagDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dataPositionTagDo) Distinct(cols ...field.Expr) IDataPositionTagDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dataPositionTagDo) Omit(cols ...field.Expr) IDataPositionTagDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dataPositionTagDo) Join(table schema.Tabler, on ...field.Expr) IDataPositionTagDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dataPositionTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDataPositionTagDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dataPositionTagDo) RightJoin(table schema.Tabler, on ...field.Expr) IDataPositionTagDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dataPositionTagDo) Group(cols ...field.Expr) IDataPositionTagDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dataPositionTagDo) Having(conds ...gen.Condition) IDataPositionTagDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dataPositionTagDo) Limit(limit int) IDataPositionTagDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dataPositionTagDo) Offset(offset int) IDataPositionTagDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dataPositionTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDataPositionTagDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dataPositionTagDo) Unscoped() IDataPositionTagDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dataPositionTagDo) Create(values ...*model.DataPositionTag) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dataPositionTagDo) CreateInBatches(values []*model.DataPositionTag, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dataPositionTagDo) Save(values ...*model.DataPositionTag) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dataPositionTagDo) First() (*model.DataPositionTag, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataPositionTag), nil
	}
}

func (d dataPositionTagDo) Take() (*model.DataPositionTag, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataPositionTag), nil
	}
}

func (d dataPositionTagDo) Last() (*model.DataPositionTag, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataPositionTag), nil
	}
}

func (d dataPositionTagDo) Find() ([]*model.DataPositionTag, error) {
	result, err := d.DO.Find()
	return result.([]*model.DataPositionTag), err
}

func (d dataPositionTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DataPositionTag, err error) {
	buf := make([]*model.DataPositionTag, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dataPositionTagDo) FindInBatches(result *[]*model.DataPositionTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dataPositionTagDo) Attrs(attrs ...field.AssignExpr) IDataPositionTagDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dataPositionTagDo) Assign(attrs ...field.AssignExpr) IDataPositionTagDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dataPositionTagDo) Joins(fields ...field.RelationField) IDataPositionTagDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dataPositionTagDo) Preload(fields ...field.RelationField) IDataPositionTagDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dataPositionTagDo) FirstOrInit() (*model.DataPositionTag, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataPositionTag), nil
	}
}

func (d dataPositionTagDo) FirstOrCreate() (*model.DataPositionTag, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataPositionTag), nil
	}
}

func (d dataPositionTagDo) FindByPage(offset int, limit int) (result []*model.DataPositionTag, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dataPositionTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dataPositionTagDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dataPositionTagDo) Delete(models ...*model.DataPositionTag) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dataPositionTagDo) withDO(do gen.Dao) *dataPositionTagDo {
	d.DO = *do.(*gen.DO)
	return d
}
