// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newDataDictionary(db *gorm.DB, opts ...gen.DOOption) dataDictionary {
	_dataDictionary := dataDictionary{}

	_dataDictionary.dataDictionaryDo.UseDB(db, opts...)
	_dataDictionary.dataDictionaryDo.UseModel(&model.DataDictionary{})

	tableName := _dataDictionary.dataDictionaryDo.TableName()
	_dataDictionary.ALL = field.NewAsterisk(tableName)
	_dataDictionary.ID = field.NewUint32(tableName, "id")
	_dataDictionary.Fid = field.NewUint32(tableName, "fid")
	_dataDictionary.Eid = field.NewUint32(tableName, "eid")
	_dataDictionary.Sort = field.NewInt32(tableName, "sort")
	_dataDictionary.Remark = field.NewString(tableName, "remark")

	_dataDictionary.fillFieldMap()

	return _dataDictionary
}

type dataDictionary struct {
	dataDictionaryDo

	ALL    field.Asterisk
	ID     field.Uint32
	Fid    field.Uint32
	Eid    field.Uint32 // 枚举值
	Sort   field.Int32
	Remark field.String

	fieldMap map[string]field.Expr
}

func (d dataDictionary) Table(newTableName string) *dataDictionary {
	d.dataDictionaryDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dataDictionary) As(alias string) *dataDictionary {
	d.dataDictionaryDo.DO = *(d.dataDictionaryDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dataDictionary) updateTableName(table string) *dataDictionary {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint32(table, "id")
	d.Fid = field.NewUint32(table, "fid")
	d.Eid = field.NewUint32(table, "eid")
	d.Sort = field.NewInt32(table, "sort")
	d.Remark = field.NewString(table, "remark")

	d.fillFieldMap()

	return d
}

func (d *dataDictionary) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dataDictionary) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 5)
	d.fieldMap["id"] = d.ID
	d.fieldMap["fid"] = d.Fid
	d.fieldMap["eid"] = d.Eid
	d.fieldMap["sort"] = d.Sort
	d.fieldMap["remark"] = d.Remark
}

func (d dataDictionary) clone(db *gorm.DB) dataDictionary {
	d.dataDictionaryDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dataDictionary) replaceDB(db *gorm.DB) dataDictionary {
	d.dataDictionaryDo.ReplaceDB(db)
	return d
}

type dataDictionaryDo struct{ gen.DO }

type IDataDictionaryDo interface {
	gen.SubQuery
	Debug() IDataDictionaryDo
	WithContext(ctx context.Context) IDataDictionaryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDataDictionaryDo
	WriteDB() IDataDictionaryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDataDictionaryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDataDictionaryDo
	Not(conds ...gen.Condition) IDataDictionaryDo
	Or(conds ...gen.Condition) IDataDictionaryDo
	Select(conds ...field.Expr) IDataDictionaryDo
	Where(conds ...gen.Condition) IDataDictionaryDo
	Order(conds ...field.Expr) IDataDictionaryDo
	Distinct(cols ...field.Expr) IDataDictionaryDo
	Omit(cols ...field.Expr) IDataDictionaryDo
	Join(table schema.Tabler, on ...field.Expr) IDataDictionaryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDataDictionaryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDataDictionaryDo
	Group(cols ...field.Expr) IDataDictionaryDo
	Having(conds ...gen.Condition) IDataDictionaryDo
	Limit(limit int) IDataDictionaryDo
	Offset(offset int) IDataDictionaryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDataDictionaryDo
	Unscoped() IDataDictionaryDo
	Create(values ...*model.DataDictionary) error
	CreateInBatches(values []*model.DataDictionary, batchSize int) error
	Save(values ...*model.DataDictionary) error
	First() (*model.DataDictionary, error)
	Take() (*model.DataDictionary, error)
	Last() (*model.DataDictionary, error)
	Find() ([]*model.DataDictionary, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DataDictionary, err error)
	FindInBatches(result *[]*model.DataDictionary, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DataDictionary) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDataDictionaryDo
	Assign(attrs ...field.AssignExpr) IDataDictionaryDo
	Joins(fields ...field.RelationField) IDataDictionaryDo
	Preload(fields ...field.RelationField) IDataDictionaryDo
	FirstOrInit() (*model.DataDictionary, error)
	FirstOrCreate() (*model.DataDictionary, error)
	FindByPage(offset int, limit int) (result []*model.DataDictionary, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDataDictionaryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dataDictionaryDo) Debug() IDataDictionaryDo {
	return d.withDO(d.DO.Debug())
}

func (d dataDictionaryDo) WithContext(ctx context.Context) IDataDictionaryDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dataDictionaryDo) ReadDB() IDataDictionaryDo {
	return d.Clauses(dbresolver.Read)
}

func (d dataDictionaryDo) WriteDB() IDataDictionaryDo {
	return d.Clauses(dbresolver.Write)
}

func (d dataDictionaryDo) Session(config *gorm.Session) IDataDictionaryDo {
	return d.withDO(d.DO.Session(config))
}

func (d dataDictionaryDo) Clauses(conds ...clause.Expression) IDataDictionaryDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dataDictionaryDo) Returning(value interface{}, columns ...string) IDataDictionaryDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dataDictionaryDo) Not(conds ...gen.Condition) IDataDictionaryDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dataDictionaryDo) Or(conds ...gen.Condition) IDataDictionaryDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dataDictionaryDo) Select(conds ...field.Expr) IDataDictionaryDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dataDictionaryDo) Where(conds ...gen.Condition) IDataDictionaryDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dataDictionaryDo) Order(conds ...field.Expr) IDataDictionaryDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dataDictionaryDo) Distinct(cols ...field.Expr) IDataDictionaryDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dataDictionaryDo) Omit(cols ...field.Expr) IDataDictionaryDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dataDictionaryDo) Join(table schema.Tabler, on ...field.Expr) IDataDictionaryDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dataDictionaryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDataDictionaryDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dataDictionaryDo) RightJoin(table schema.Tabler, on ...field.Expr) IDataDictionaryDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dataDictionaryDo) Group(cols ...field.Expr) IDataDictionaryDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dataDictionaryDo) Having(conds ...gen.Condition) IDataDictionaryDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dataDictionaryDo) Limit(limit int) IDataDictionaryDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dataDictionaryDo) Offset(offset int) IDataDictionaryDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dataDictionaryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDataDictionaryDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dataDictionaryDo) Unscoped() IDataDictionaryDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dataDictionaryDo) Create(values ...*model.DataDictionary) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dataDictionaryDo) CreateInBatches(values []*model.DataDictionary, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dataDictionaryDo) Save(values ...*model.DataDictionary) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dataDictionaryDo) First() (*model.DataDictionary, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDictionary), nil
	}
}

func (d dataDictionaryDo) Take() (*model.DataDictionary, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDictionary), nil
	}
}

func (d dataDictionaryDo) Last() (*model.DataDictionary, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDictionary), nil
	}
}

func (d dataDictionaryDo) Find() ([]*model.DataDictionary, error) {
	result, err := d.DO.Find()
	return result.([]*model.DataDictionary), err
}

func (d dataDictionaryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DataDictionary, err error) {
	buf := make([]*model.DataDictionary, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dataDictionaryDo) FindInBatches(result *[]*model.DataDictionary, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dataDictionaryDo) Attrs(attrs ...field.AssignExpr) IDataDictionaryDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dataDictionaryDo) Assign(attrs ...field.AssignExpr) IDataDictionaryDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dataDictionaryDo) Joins(fields ...field.RelationField) IDataDictionaryDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dataDictionaryDo) Preload(fields ...field.RelationField) IDataDictionaryDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dataDictionaryDo) FirstOrInit() (*model.DataDictionary, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDictionary), nil
	}
}

func (d dataDictionaryDo) FirstOrCreate() (*model.DataDictionary, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDictionary), nil
	}
}

func (d dataDictionaryDo) FindByPage(offset int, limit int) (result []*model.DataDictionary, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dataDictionaryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dataDictionaryDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dataDictionaryDo) Delete(models ...*model.DataDictionary) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dataDictionaryDo) withDO(do gen.Dao) *dataDictionaryDo {
	d.DO = *do.(*gen.DO)
	return d
}
