// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newDataDictionaryConfig(db *gorm.DB, opts ...gen.DOOption) dataDictionaryConfig {
	_dataDictionaryConfig := dataDictionaryConfig{}

	_dataDictionaryConfig.dataDictionaryConfigDo.UseDB(db, opts...)
	_dataDictionaryConfig.dataDictionaryConfigDo.UseModel(&model.DataDictionaryConfig{})

	tableName := _dataDictionaryConfig.dataDictionaryConfigDo.TableName()
	_dataDictionaryConfig.ALL = field.NewAsterisk(tableName)
	_dataDictionaryConfig.ID = field.NewUint32(tableName, "id")
	_dataDictionaryConfig.Fid = field.NewUint32(tableName, "fid")
	_dataDictionaryConfig.Name = field.NewString(tableName, "name")
	_dataDictionaryConfig.Key = field.NewString(tableName, "key")

	_dataDictionaryConfig.fillFieldMap()

	return _dataDictionaryConfig
}

type dataDictionaryConfig struct {
	dataDictionaryConfigDo

	ALL  field.Asterisk
	ID   field.Uint32 // 主键
	Fid  field.Uint32 // 类型
	Name field.String // 类型名称
	Key  field.String

	fieldMap map[string]field.Expr
}

func (d dataDictionaryConfig) Table(newTableName string) *dataDictionaryConfig {
	d.dataDictionaryConfigDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dataDictionaryConfig) As(alias string) *dataDictionaryConfig {
	d.dataDictionaryConfigDo.DO = *(d.dataDictionaryConfigDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dataDictionaryConfig) updateTableName(table string) *dataDictionaryConfig {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint32(table, "id")
	d.Fid = field.NewUint32(table, "fid")
	d.Name = field.NewString(table, "name")
	d.Key = field.NewString(table, "key")

	d.fillFieldMap()

	return d
}

func (d *dataDictionaryConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dataDictionaryConfig) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 4)
	d.fieldMap["id"] = d.ID
	d.fieldMap["fid"] = d.Fid
	d.fieldMap["name"] = d.Name
	d.fieldMap["key"] = d.Key
}

func (d dataDictionaryConfig) clone(db *gorm.DB) dataDictionaryConfig {
	d.dataDictionaryConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dataDictionaryConfig) replaceDB(db *gorm.DB) dataDictionaryConfig {
	d.dataDictionaryConfigDo.ReplaceDB(db)
	return d
}

type dataDictionaryConfigDo struct{ gen.DO }

type IDataDictionaryConfigDo interface {
	gen.SubQuery
	Debug() IDataDictionaryConfigDo
	WithContext(ctx context.Context) IDataDictionaryConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDataDictionaryConfigDo
	WriteDB() IDataDictionaryConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDataDictionaryConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDataDictionaryConfigDo
	Not(conds ...gen.Condition) IDataDictionaryConfigDo
	Or(conds ...gen.Condition) IDataDictionaryConfigDo
	Select(conds ...field.Expr) IDataDictionaryConfigDo
	Where(conds ...gen.Condition) IDataDictionaryConfigDo
	Order(conds ...field.Expr) IDataDictionaryConfigDo
	Distinct(cols ...field.Expr) IDataDictionaryConfigDo
	Omit(cols ...field.Expr) IDataDictionaryConfigDo
	Join(table schema.Tabler, on ...field.Expr) IDataDictionaryConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDataDictionaryConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDataDictionaryConfigDo
	Group(cols ...field.Expr) IDataDictionaryConfigDo
	Having(conds ...gen.Condition) IDataDictionaryConfigDo
	Limit(limit int) IDataDictionaryConfigDo
	Offset(offset int) IDataDictionaryConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDataDictionaryConfigDo
	Unscoped() IDataDictionaryConfigDo
	Create(values ...*model.DataDictionaryConfig) error
	CreateInBatches(values []*model.DataDictionaryConfig, batchSize int) error
	Save(values ...*model.DataDictionaryConfig) error
	First() (*model.DataDictionaryConfig, error)
	Take() (*model.DataDictionaryConfig, error)
	Last() (*model.DataDictionaryConfig, error)
	Find() ([]*model.DataDictionaryConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DataDictionaryConfig, err error)
	FindInBatches(result *[]*model.DataDictionaryConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DataDictionaryConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDataDictionaryConfigDo
	Assign(attrs ...field.AssignExpr) IDataDictionaryConfigDo
	Joins(fields ...field.RelationField) IDataDictionaryConfigDo
	Preload(fields ...field.RelationField) IDataDictionaryConfigDo
	FirstOrInit() (*model.DataDictionaryConfig, error)
	FirstOrCreate() (*model.DataDictionaryConfig, error)
	FindByPage(offset int, limit int) (result []*model.DataDictionaryConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDataDictionaryConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dataDictionaryConfigDo) Debug() IDataDictionaryConfigDo {
	return d.withDO(d.DO.Debug())
}

func (d dataDictionaryConfigDo) WithContext(ctx context.Context) IDataDictionaryConfigDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dataDictionaryConfigDo) ReadDB() IDataDictionaryConfigDo {
	return d.Clauses(dbresolver.Read)
}

func (d dataDictionaryConfigDo) WriteDB() IDataDictionaryConfigDo {
	return d.Clauses(dbresolver.Write)
}

func (d dataDictionaryConfigDo) Session(config *gorm.Session) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Session(config))
}

func (d dataDictionaryConfigDo) Clauses(conds ...clause.Expression) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dataDictionaryConfigDo) Returning(value interface{}, columns ...string) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dataDictionaryConfigDo) Not(conds ...gen.Condition) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dataDictionaryConfigDo) Or(conds ...gen.Condition) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dataDictionaryConfigDo) Select(conds ...field.Expr) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dataDictionaryConfigDo) Where(conds ...gen.Condition) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dataDictionaryConfigDo) Order(conds ...field.Expr) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dataDictionaryConfigDo) Distinct(cols ...field.Expr) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dataDictionaryConfigDo) Omit(cols ...field.Expr) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dataDictionaryConfigDo) Join(table schema.Tabler, on ...field.Expr) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dataDictionaryConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDataDictionaryConfigDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dataDictionaryConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IDataDictionaryConfigDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dataDictionaryConfigDo) Group(cols ...field.Expr) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dataDictionaryConfigDo) Having(conds ...gen.Condition) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dataDictionaryConfigDo) Limit(limit int) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dataDictionaryConfigDo) Offset(offset int) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dataDictionaryConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dataDictionaryConfigDo) Unscoped() IDataDictionaryConfigDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dataDictionaryConfigDo) Create(values ...*model.DataDictionaryConfig) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dataDictionaryConfigDo) CreateInBatches(values []*model.DataDictionaryConfig, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dataDictionaryConfigDo) Save(values ...*model.DataDictionaryConfig) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dataDictionaryConfigDo) First() (*model.DataDictionaryConfig, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDictionaryConfig), nil
	}
}

func (d dataDictionaryConfigDo) Take() (*model.DataDictionaryConfig, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDictionaryConfig), nil
	}
}

func (d dataDictionaryConfigDo) Last() (*model.DataDictionaryConfig, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDictionaryConfig), nil
	}
}

func (d dataDictionaryConfigDo) Find() ([]*model.DataDictionaryConfig, error) {
	result, err := d.DO.Find()
	return result.([]*model.DataDictionaryConfig), err
}

func (d dataDictionaryConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DataDictionaryConfig, err error) {
	buf := make([]*model.DataDictionaryConfig, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dataDictionaryConfigDo) FindInBatches(result *[]*model.DataDictionaryConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dataDictionaryConfigDo) Attrs(attrs ...field.AssignExpr) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dataDictionaryConfigDo) Assign(attrs ...field.AssignExpr) IDataDictionaryConfigDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dataDictionaryConfigDo) Joins(fields ...field.RelationField) IDataDictionaryConfigDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dataDictionaryConfigDo) Preload(fields ...field.RelationField) IDataDictionaryConfigDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dataDictionaryConfigDo) FirstOrInit() (*model.DataDictionaryConfig, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDictionaryConfig), nil
	}
}

func (d dataDictionaryConfigDo) FirstOrCreate() (*model.DataDictionaryConfig, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDictionaryConfig), nil
	}
}

func (d dataDictionaryConfigDo) FindByPage(offset int, limit int) (result []*model.DataDictionaryConfig, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dataDictionaryConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dataDictionaryConfigDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dataDictionaryConfigDo) Delete(models ...*model.DataDictionaryConfig) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dataDictionaryConfigDo) withDO(do gen.Dao) *dataDictionaryConfigDo {
	d.DO = *do.(*gen.DO)
	return d
}
