// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newDataDistrict(db *gorm.DB, opts ...gen.DOOption) dataDistrict {
	_dataDistrict := dataDistrict{}

	_dataDistrict.dataDistrictDo.UseDB(db, opts...)
	_dataDistrict.dataDistrictDo.UseModel(&model.DataDistrict{})

	tableName := _dataDistrict.dataDistrictDo.TableName()
	_dataDistrict.ALL = field.NewAsterisk(tableName)
	_dataDistrict.ID = field.NewUint32(tableName, "id")
	_dataDistrict.CityID = field.NewUint32(tableName, "city_id")
	_dataDistrict.Sort = field.NewInt32(tableName, "sort")
	_dataDistrict.Name = field.NewString(tableName, "name")

	_dataDistrict.fillFieldMap()

	return _dataDistrict
}

type dataDistrict struct {
	dataDistrictDo

	ALL    field.Asterisk
	ID     field.Uint32
	CityID field.Uint32
	Sort   field.Int32
	Name   field.String

	fieldMap map[string]field.Expr
}

func (d dataDistrict) Table(newTableName string) *dataDistrict {
	d.dataDistrictDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dataDistrict) As(alias string) *dataDistrict {
	d.dataDistrictDo.DO = *(d.dataDistrictDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dataDistrict) updateTableName(table string) *dataDistrict {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint32(table, "id")
	d.CityID = field.NewUint32(table, "city_id")
	d.Sort = field.NewInt32(table, "sort")
	d.Name = field.NewString(table, "name")

	d.fillFieldMap()

	return d
}

func (d *dataDistrict) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dataDistrict) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 4)
	d.fieldMap["id"] = d.ID
	d.fieldMap["city_id"] = d.CityID
	d.fieldMap["sort"] = d.Sort
	d.fieldMap["name"] = d.Name
}

func (d dataDistrict) clone(db *gorm.DB) dataDistrict {
	d.dataDistrictDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dataDistrict) replaceDB(db *gorm.DB) dataDistrict {
	d.dataDistrictDo.ReplaceDB(db)
	return d
}

type dataDistrictDo struct{ gen.DO }

type IDataDistrictDo interface {
	gen.SubQuery
	Debug() IDataDistrictDo
	WithContext(ctx context.Context) IDataDistrictDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDataDistrictDo
	WriteDB() IDataDistrictDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDataDistrictDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDataDistrictDo
	Not(conds ...gen.Condition) IDataDistrictDo
	Or(conds ...gen.Condition) IDataDistrictDo
	Select(conds ...field.Expr) IDataDistrictDo
	Where(conds ...gen.Condition) IDataDistrictDo
	Order(conds ...field.Expr) IDataDistrictDo
	Distinct(cols ...field.Expr) IDataDistrictDo
	Omit(cols ...field.Expr) IDataDistrictDo
	Join(table schema.Tabler, on ...field.Expr) IDataDistrictDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDataDistrictDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDataDistrictDo
	Group(cols ...field.Expr) IDataDistrictDo
	Having(conds ...gen.Condition) IDataDistrictDo
	Limit(limit int) IDataDistrictDo
	Offset(offset int) IDataDistrictDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDataDistrictDo
	Unscoped() IDataDistrictDo
	Create(values ...*model.DataDistrict) error
	CreateInBatches(values []*model.DataDistrict, batchSize int) error
	Save(values ...*model.DataDistrict) error
	First() (*model.DataDistrict, error)
	Take() (*model.DataDistrict, error)
	Last() (*model.DataDistrict, error)
	Find() ([]*model.DataDistrict, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DataDistrict, err error)
	FindInBatches(result *[]*model.DataDistrict, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DataDistrict) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDataDistrictDo
	Assign(attrs ...field.AssignExpr) IDataDistrictDo
	Joins(fields ...field.RelationField) IDataDistrictDo
	Preload(fields ...field.RelationField) IDataDistrictDo
	FirstOrInit() (*model.DataDistrict, error)
	FirstOrCreate() (*model.DataDistrict, error)
	FindByPage(offset int, limit int) (result []*model.DataDistrict, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDataDistrictDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dataDistrictDo) Debug() IDataDistrictDo {
	return d.withDO(d.DO.Debug())
}

func (d dataDistrictDo) WithContext(ctx context.Context) IDataDistrictDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dataDistrictDo) ReadDB() IDataDistrictDo {
	return d.Clauses(dbresolver.Read)
}

func (d dataDistrictDo) WriteDB() IDataDistrictDo {
	return d.Clauses(dbresolver.Write)
}

func (d dataDistrictDo) Session(config *gorm.Session) IDataDistrictDo {
	return d.withDO(d.DO.Session(config))
}

func (d dataDistrictDo) Clauses(conds ...clause.Expression) IDataDistrictDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dataDistrictDo) Returning(value interface{}, columns ...string) IDataDistrictDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dataDistrictDo) Not(conds ...gen.Condition) IDataDistrictDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dataDistrictDo) Or(conds ...gen.Condition) IDataDistrictDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dataDistrictDo) Select(conds ...field.Expr) IDataDistrictDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dataDistrictDo) Where(conds ...gen.Condition) IDataDistrictDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dataDistrictDo) Order(conds ...field.Expr) IDataDistrictDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dataDistrictDo) Distinct(cols ...field.Expr) IDataDistrictDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dataDistrictDo) Omit(cols ...field.Expr) IDataDistrictDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dataDistrictDo) Join(table schema.Tabler, on ...field.Expr) IDataDistrictDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dataDistrictDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDataDistrictDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dataDistrictDo) RightJoin(table schema.Tabler, on ...field.Expr) IDataDistrictDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dataDistrictDo) Group(cols ...field.Expr) IDataDistrictDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dataDistrictDo) Having(conds ...gen.Condition) IDataDistrictDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dataDistrictDo) Limit(limit int) IDataDistrictDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dataDistrictDo) Offset(offset int) IDataDistrictDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dataDistrictDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDataDistrictDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dataDistrictDo) Unscoped() IDataDistrictDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dataDistrictDo) Create(values ...*model.DataDistrict) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dataDistrictDo) CreateInBatches(values []*model.DataDistrict, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dataDistrictDo) Save(values ...*model.DataDistrict) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dataDistrictDo) First() (*model.DataDistrict, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDistrict), nil
	}
}

func (d dataDistrictDo) Take() (*model.DataDistrict, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDistrict), nil
	}
}

func (d dataDistrictDo) Last() (*model.DataDistrict, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDistrict), nil
	}
}

func (d dataDistrictDo) Find() ([]*model.DataDistrict, error) {
	result, err := d.DO.Find()
	return result.([]*model.DataDistrict), err
}

func (d dataDistrictDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DataDistrict, err error) {
	buf := make([]*model.DataDistrict, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dataDistrictDo) FindInBatches(result *[]*model.DataDistrict, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dataDistrictDo) Attrs(attrs ...field.AssignExpr) IDataDistrictDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dataDistrictDo) Assign(attrs ...field.AssignExpr) IDataDistrictDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dataDistrictDo) Joins(fields ...field.RelationField) IDataDistrictDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dataDistrictDo) Preload(fields ...field.RelationField) IDataDistrictDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dataDistrictDo) FirstOrInit() (*model.DataDistrict, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDistrict), nil
	}
}

func (d dataDistrictDo) FirstOrCreate() (*model.DataDistrict, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataDistrict), nil
	}
}

func (d dataDistrictDo) FindByPage(offset int, limit int) (result []*model.DataDistrict, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dataDistrictDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dataDistrictDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dataDistrictDo) Delete(models ...*model.DataDistrict) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dataDistrictDo) withDO(do gen.Dao) *dataDistrictDo {
	d.DO = *do.(*gen.DO)
	return d
}
