// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newDataProvince(db *gorm.DB, opts ...gen.DOOption) dataProvince {
	_dataProvince := dataProvince{}

	_dataProvince.dataProvinceDo.UseDB(db, opts...)
	_dataProvince.dataProvinceDo.UseModel(&model.DataProvince{})

	tableName := _dataProvince.dataProvinceDo.TableName()
	_dataProvince.ALL = field.NewAsterisk(tableName)
	_dataProvince.ID = field.NewUint32(tableName, "id")
	_dataProvince.Name = field.NewString(tableName, "name")

	_dataProvince.fillFieldMap()

	return _dataProvince
}

type dataProvince struct {
	dataProvinceDo

	ALL  field.Asterisk
	ID   field.Uint32
	Name field.String

	fieldMap map[string]field.Expr
}

func (d dataProvince) Table(newTableName string) *dataProvince {
	d.dataProvinceDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dataProvince) As(alias string) *dataProvince {
	d.dataProvinceDo.DO = *(d.dataProvinceDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dataProvince) updateTableName(table string) *dataProvince {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint32(table, "id")
	d.Name = field.NewString(table, "name")

	d.fillFieldMap()

	return d
}

func (d *dataProvince) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dataProvince) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 2)
	d.fieldMap["id"] = d.ID
	d.fieldMap["name"] = d.Name
}

func (d dataProvince) clone(db *gorm.DB) dataProvince {
	d.dataProvinceDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dataProvince) replaceDB(db *gorm.DB) dataProvince {
	d.dataProvinceDo.ReplaceDB(db)
	return d
}

type dataProvinceDo struct{ gen.DO }

type IDataProvinceDo interface {
	gen.SubQuery
	Debug() IDataProvinceDo
	WithContext(ctx context.Context) IDataProvinceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDataProvinceDo
	WriteDB() IDataProvinceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDataProvinceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDataProvinceDo
	Not(conds ...gen.Condition) IDataProvinceDo
	Or(conds ...gen.Condition) IDataProvinceDo
	Select(conds ...field.Expr) IDataProvinceDo
	Where(conds ...gen.Condition) IDataProvinceDo
	Order(conds ...field.Expr) IDataProvinceDo
	Distinct(cols ...field.Expr) IDataProvinceDo
	Omit(cols ...field.Expr) IDataProvinceDo
	Join(table schema.Tabler, on ...field.Expr) IDataProvinceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDataProvinceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDataProvinceDo
	Group(cols ...field.Expr) IDataProvinceDo
	Having(conds ...gen.Condition) IDataProvinceDo
	Limit(limit int) IDataProvinceDo
	Offset(offset int) IDataProvinceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDataProvinceDo
	Unscoped() IDataProvinceDo
	Create(values ...*model.DataProvince) error
	CreateInBatches(values []*model.DataProvince, batchSize int) error
	Save(values ...*model.DataProvince) error
	First() (*model.DataProvince, error)
	Take() (*model.DataProvince, error)
	Last() (*model.DataProvince, error)
	Find() ([]*model.DataProvince, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DataProvince, err error)
	FindInBatches(result *[]*model.DataProvince, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DataProvince) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDataProvinceDo
	Assign(attrs ...field.AssignExpr) IDataProvinceDo
	Joins(fields ...field.RelationField) IDataProvinceDo
	Preload(fields ...field.RelationField) IDataProvinceDo
	FirstOrInit() (*model.DataProvince, error)
	FirstOrCreate() (*model.DataProvince, error)
	FindByPage(offset int, limit int) (result []*model.DataProvince, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDataProvinceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dataProvinceDo) Debug() IDataProvinceDo {
	return d.withDO(d.DO.Debug())
}

func (d dataProvinceDo) WithContext(ctx context.Context) IDataProvinceDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dataProvinceDo) ReadDB() IDataProvinceDo {
	return d.Clauses(dbresolver.Read)
}

func (d dataProvinceDo) WriteDB() IDataProvinceDo {
	return d.Clauses(dbresolver.Write)
}

func (d dataProvinceDo) Session(config *gorm.Session) IDataProvinceDo {
	return d.withDO(d.DO.Session(config))
}

func (d dataProvinceDo) Clauses(conds ...clause.Expression) IDataProvinceDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dataProvinceDo) Returning(value interface{}, columns ...string) IDataProvinceDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dataProvinceDo) Not(conds ...gen.Condition) IDataProvinceDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dataProvinceDo) Or(conds ...gen.Condition) IDataProvinceDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dataProvinceDo) Select(conds ...field.Expr) IDataProvinceDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dataProvinceDo) Where(conds ...gen.Condition) IDataProvinceDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dataProvinceDo) Order(conds ...field.Expr) IDataProvinceDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dataProvinceDo) Distinct(cols ...field.Expr) IDataProvinceDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dataProvinceDo) Omit(cols ...field.Expr) IDataProvinceDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dataProvinceDo) Join(table schema.Tabler, on ...field.Expr) IDataProvinceDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dataProvinceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDataProvinceDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dataProvinceDo) RightJoin(table schema.Tabler, on ...field.Expr) IDataProvinceDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dataProvinceDo) Group(cols ...field.Expr) IDataProvinceDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dataProvinceDo) Having(conds ...gen.Condition) IDataProvinceDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dataProvinceDo) Limit(limit int) IDataProvinceDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dataProvinceDo) Offset(offset int) IDataProvinceDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dataProvinceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDataProvinceDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dataProvinceDo) Unscoped() IDataProvinceDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dataProvinceDo) Create(values ...*model.DataProvince) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dataProvinceDo) CreateInBatches(values []*model.DataProvince, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dataProvinceDo) Save(values ...*model.DataProvince) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dataProvinceDo) First() (*model.DataProvince, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataProvince), nil
	}
}

func (d dataProvinceDo) Take() (*model.DataProvince, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataProvince), nil
	}
}

func (d dataProvinceDo) Last() (*model.DataProvince, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataProvince), nil
	}
}

func (d dataProvinceDo) Find() ([]*model.DataProvince, error) {
	result, err := d.DO.Find()
	return result.([]*model.DataProvince), err
}

func (d dataProvinceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DataProvince, err error) {
	buf := make([]*model.DataProvince, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dataProvinceDo) FindInBatches(result *[]*model.DataProvince, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dataProvinceDo) Attrs(attrs ...field.AssignExpr) IDataProvinceDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dataProvinceDo) Assign(attrs ...field.AssignExpr) IDataProvinceDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dataProvinceDo) Joins(fields ...field.RelationField) IDataProvinceDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dataProvinceDo) Preload(fields ...field.RelationField) IDataProvinceDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dataProvinceDo) FirstOrInit() (*model.DataProvince, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataProvince), nil
	}
}

func (d dataProvinceDo) FirstOrCreate() (*model.DataProvince, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataProvince), nil
	}
}

func (d dataProvinceDo) FindByPage(offset int, limit int) (result []*model.DataProvince, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dataProvinceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dataProvinceDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dataProvinceDo) Delete(models ...*model.DataProvince) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dataProvinceDo) withDO(do gen.Dao) *dataProvinceDo {
	d.DO = *do.(*gen.DO)
	return d
}
