// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newDataCityOld2(db *gorm.DB, opts ...gen.DOOption) dataCityOld2 {
	_dataCityOld2 := dataCityOld2{}

	_dataCityOld2.dataCityOld2Do.UseDB(db, opts...)
	_dataCityOld2.dataCityOld2Do.UseModel(&model.DataCityOld2{})

	tableName := _dataCityOld2.dataCityOld2Do.TableName()
	_dataCityOld2.ALL = field.NewAsterisk(tableName)
	_dataCityOld2.ID = field.NewInt32(tableName, "id")
	_dataCityOld2.CityIndex = field.NewInt32(tableName, "city_index")
	_dataCityOld2.ProvinceID = field.NewInt32(tableName, "province_id")
	_dataCityOld2.Sort = field.NewInt32(tableName, "sort")
	_dataCityOld2.Name = field.NewString(tableName, "name")

	_dataCityOld2.fillFieldMap()

	return _dataCityOld2
}

type dataCityOld2 struct {
	dataCityOld2Do

	ALL        field.Asterisk
	ID         field.Int32
	CityIndex  field.Int32
	ProvinceID field.Int32
	Sort       field.Int32 // 排序
	Name       field.String

	fieldMap map[string]field.Expr
}

func (d dataCityOld2) Table(newTableName string) *dataCityOld2 {
	d.dataCityOld2Do.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dataCityOld2) As(alias string) *dataCityOld2 {
	d.dataCityOld2Do.DO = *(d.dataCityOld2Do.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dataCityOld2) updateTableName(table string) *dataCityOld2 {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt32(table, "id")
	d.CityIndex = field.NewInt32(table, "city_index")
	d.ProvinceID = field.NewInt32(table, "province_id")
	d.Sort = field.NewInt32(table, "sort")
	d.Name = field.NewString(table, "name")

	d.fillFieldMap()

	return d
}

func (d *dataCityOld2) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dataCityOld2) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 5)
	d.fieldMap["id"] = d.ID
	d.fieldMap["city_index"] = d.CityIndex
	d.fieldMap["province_id"] = d.ProvinceID
	d.fieldMap["sort"] = d.Sort
	d.fieldMap["name"] = d.Name
}

func (d dataCityOld2) clone(db *gorm.DB) dataCityOld2 {
	d.dataCityOld2Do.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dataCityOld2) replaceDB(db *gorm.DB) dataCityOld2 {
	d.dataCityOld2Do.ReplaceDB(db)
	return d
}

type dataCityOld2Do struct{ gen.DO }

type IDataCityOld2Do interface {
	gen.SubQuery
	Debug() IDataCityOld2Do
	WithContext(ctx context.Context) IDataCityOld2Do
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDataCityOld2Do
	WriteDB() IDataCityOld2Do
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDataCityOld2Do
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDataCityOld2Do
	Not(conds ...gen.Condition) IDataCityOld2Do
	Or(conds ...gen.Condition) IDataCityOld2Do
	Select(conds ...field.Expr) IDataCityOld2Do
	Where(conds ...gen.Condition) IDataCityOld2Do
	Order(conds ...field.Expr) IDataCityOld2Do
	Distinct(cols ...field.Expr) IDataCityOld2Do
	Omit(cols ...field.Expr) IDataCityOld2Do
	Join(table schema.Tabler, on ...field.Expr) IDataCityOld2Do
	LeftJoin(table schema.Tabler, on ...field.Expr) IDataCityOld2Do
	RightJoin(table schema.Tabler, on ...field.Expr) IDataCityOld2Do
	Group(cols ...field.Expr) IDataCityOld2Do
	Having(conds ...gen.Condition) IDataCityOld2Do
	Limit(limit int) IDataCityOld2Do
	Offset(offset int) IDataCityOld2Do
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDataCityOld2Do
	Unscoped() IDataCityOld2Do
	Create(values ...*model.DataCityOld2) error
	CreateInBatches(values []*model.DataCityOld2, batchSize int) error
	Save(values ...*model.DataCityOld2) error
	First() (*model.DataCityOld2, error)
	Take() (*model.DataCityOld2, error)
	Last() (*model.DataCityOld2, error)
	Find() ([]*model.DataCityOld2, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DataCityOld2, err error)
	FindInBatches(result *[]*model.DataCityOld2, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DataCityOld2) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDataCityOld2Do
	Assign(attrs ...field.AssignExpr) IDataCityOld2Do
	Joins(fields ...field.RelationField) IDataCityOld2Do
	Preload(fields ...field.RelationField) IDataCityOld2Do
	FirstOrInit() (*model.DataCityOld2, error)
	FirstOrCreate() (*model.DataCityOld2, error)
	FindByPage(offset int, limit int) (result []*model.DataCityOld2, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDataCityOld2Do
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dataCityOld2Do) Debug() IDataCityOld2Do {
	return d.withDO(d.DO.Debug())
}

func (d dataCityOld2Do) WithContext(ctx context.Context) IDataCityOld2Do {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dataCityOld2Do) ReadDB() IDataCityOld2Do {
	return d.Clauses(dbresolver.Read)
}

func (d dataCityOld2Do) WriteDB() IDataCityOld2Do {
	return d.Clauses(dbresolver.Write)
}

func (d dataCityOld2Do) Session(config *gorm.Session) IDataCityOld2Do {
	return d.withDO(d.DO.Session(config))
}

func (d dataCityOld2Do) Clauses(conds ...clause.Expression) IDataCityOld2Do {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dataCityOld2Do) Returning(value interface{}, columns ...string) IDataCityOld2Do {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dataCityOld2Do) Not(conds ...gen.Condition) IDataCityOld2Do {
	return d.withDO(d.DO.Not(conds...))
}

func (d dataCityOld2Do) Or(conds ...gen.Condition) IDataCityOld2Do {
	return d.withDO(d.DO.Or(conds...))
}

func (d dataCityOld2Do) Select(conds ...field.Expr) IDataCityOld2Do {
	return d.withDO(d.DO.Select(conds...))
}

func (d dataCityOld2Do) Where(conds ...gen.Condition) IDataCityOld2Do {
	return d.withDO(d.DO.Where(conds...))
}

func (d dataCityOld2Do) Order(conds ...field.Expr) IDataCityOld2Do {
	return d.withDO(d.DO.Order(conds...))
}

func (d dataCityOld2Do) Distinct(cols ...field.Expr) IDataCityOld2Do {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dataCityOld2Do) Omit(cols ...field.Expr) IDataCityOld2Do {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dataCityOld2Do) Join(table schema.Tabler, on ...field.Expr) IDataCityOld2Do {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dataCityOld2Do) LeftJoin(table schema.Tabler, on ...field.Expr) IDataCityOld2Do {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dataCityOld2Do) RightJoin(table schema.Tabler, on ...field.Expr) IDataCityOld2Do {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dataCityOld2Do) Group(cols ...field.Expr) IDataCityOld2Do {
	return d.withDO(d.DO.Group(cols...))
}

func (d dataCityOld2Do) Having(conds ...gen.Condition) IDataCityOld2Do {
	return d.withDO(d.DO.Having(conds...))
}

func (d dataCityOld2Do) Limit(limit int) IDataCityOld2Do {
	return d.withDO(d.DO.Limit(limit))
}

func (d dataCityOld2Do) Offset(offset int) IDataCityOld2Do {
	return d.withDO(d.DO.Offset(offset))
}

func (d dataCityOld2Do) Scopes(funcs ...func(gen.Dao) gen.Dao) IDataCityOld2Do {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dataCityOld2Do) Unscoped() IDataCityOld2Do {
	return d.withDO(d.DO.Unscoped())
}

func (d dataCityOld2Do) Create(values ...*model.DataCityOld2) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dataCityOld2Do) CreateInBatches(values []*model.DataCityOld2, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dataCityOld2Do) Save(values ...*model.DataCityOld2) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dataCityOld2Do) First() (*model.DataCityOld2, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataCityOld2), nil
	}
}

func (d dataCityOld2Do) Take() (*model.DataCityOld2, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataCityOld2), nil
	}
}

func (d dataCityOld2Do) Last() (*model.DataCityOld2, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataCityOld2), nil
	}
}

func (d dataCityOld2Do) Find() ([]*model.DataCityOld2, error) {
	result, err := d.DO.Find()
	return result.([]*model.DataCityOld2), err
}

func (d dataCityOld2Do) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DataCityOld2, err error) {
	buf := make([]*model.DataCityOld2, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dataCityOld2Do) FindInBatches(result *[]*model.DataCityOld2, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dataCityOld2Do) Attrs(attrs ...field.AssignExpr) IDataCityOld2Do {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dataCityOld2Do) Assign(attrs ...field.AssignExpr) IDataCityOld2Do {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dataCityOld2Do) Joins(fields ...field.RelationField) IDataCityOld2Do {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dataCityOld2Do) Preload(fields ...field.RelationField) IDataCityOld2Do {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dataCityOld2Do) FirstOrInit() (*model.DataCityOld2, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataCityOld2), nil
	}
}

func (d dataCityOld2Do) FirstOrCreate() (*model.DataCityOld2, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DataCityOld2), nil
	}
}

func (d dataCityOld2Do) FindByPage(offset int, limit int) (result []*model.DataCityOld2, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dataCityOld2Do) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dataCityOld2Do) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dataCityOld2Do) Delete(models ...*model.DataCityOld2) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dataCityOld2Do) withDO(do gen.Dao) *dataCityOld2Do {
	d.DO = *do.(*gen.DO)
	return d
}
