// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newDeliver(db *gorm.DB, opts ...gen.DOOption) deliver {
	_deliver := deliver{}

	_deliver.deliverDo.UseDB(db, opts...)
	_deliver.deliverDo.UseModel(&model.Deliver{})

	tableName := _deliver.deliverDo.TableName()
	_deliver.ALL = field.NewAsterisk(tableName)
	_deliver.ID = field.NewUint32(tableName, "id")
	_deliver.Type = field.NewUint32(tableName, "type")
	_deliver.AccountID = field.NewUint32(tableName, "account_id")
	_deliver.AccountName = field.NewString(tableName, "account_name")
	_deliver.AccountMobile = field.NewString(tableName, "account_mobile")
	_deliver.Name = field.NewString(tableName, "name")
	_deliver.Mobile = field.NewString(tableName, "mobile")
	_deliver.Email = field.NewString(tableName, "email")
	_deliver.PassageID = field.NewUint32(tableName, "passage_id")
	_deliver.PassageRecommendID = field.NewUint32(tableName, "passage_recommend_id")
	_deliver.PassageRecommendPath = field.NewString(tableName, "passage_recommend_path")
	_deliver.PassageRecommendPathFull = field.NewString(tableName, "passage_recommend_path_full")
	_deliver.RecommendAccountID = field.NewUint32(tableName, "recommend_account_id")
	_deliver.RecommendComment = field.NewString(tableName, "recommend_comment")
	_deliver.ResumeURL = field.NewString(tableName, "resume_url")
	_deliver.ProgressEid = field.NewUint32(tableName, "progress_eid")
	_deliver.Progress = field.NewString(tableName, "progress")
	_deliver.IsReal = field.NewUint32(tableName, "is_real")
	_deliver.DeliverTime = field.NewUint64(tableName, "deliver_time")
	_deliver.CreatedTime = field.NewInt64(tableName, "created_time")
	_deliver.UpdatedTime = field.NewInt64(tableName, "updated_time")

	_deliver.fillFieldMap()

	return _deliver
}

type deliver struct {
	deliverDo

	ALL                      field.Asterisk
	ID                       field.Uint32
	Type                     field.Uint32 // 投递类型: 1. 自己投递，2. 手动推荐
	AccountID                field.Uint32
	AccountName              field.String // 账号名称
	AccountMobile            field.String // 账号手机号
	Name                     field.String // 候选人姓名
	Mobile                   field.String // 候选人手机号
	Email                    field.String // 候选人邮箱
	PassageID                field.Uint32
	PassageRecommendID       field.Uint32
	PassageRecommendPath     field.String // 职位推荐路径
	PassageRecommendPathFull field.String // 职位推荐路径，带上自己
	RecommendAccountID       field.Uint32
	RecommendComment         field.String // 推荐评价
	ResumeURL                field.String // 简历地址
	ProgressEid              field.Uint32 // 投递状态
	Progress                 field.String // 投递状态
	IsReal                   field.Uint32 // 是否已经投递
	DeliverTime              field.Uint64 // 投递时间
	CreatedTime              field.Int64  // 创建时间
	UpdatedTime              field.Int64  // 更新时间

	fieldMap map[string]field.Expr
}

func (d deliver) Table(newTableName string) *deliver {
	d.deliverDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deliver) As(alias string) *deliver {
	d.deliverDo.DO = *(d.deliverDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deliver) updateTableName(table string) *deliver {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint32(table, "id")
	d.Type = field.NewUint32(table, "type")
	d.AccountID = field.NewUint32(table, "account_id")
	d.AccountName = field.NewString(table, "account_name")
	d.AccountMobile = field.NewString(table, "account_mobile")
	d.Name = field.NewString(table, "name")
	d.Mobile = field.NewString(table, "mobile")
	d.Email = field.NewString(table, "email")
	d.PassageID = field.NewUint32(table, "passage_id")
	d.PassageRecommendID = field.NewUint32(table, "passage_recommend_id")
	d.PassageRecommendPath = field.NewString(table, "passage_recommend_path")
	d.PassageRecommendPathFull = field.NewString(table, "passage_recommend_path_full")
	d.RecommendAccountID = field.NewUint32(table, "recommend_account_id")
	d.RecommendComment = field.NewString(table, "recommend_comment")
	d.ResumeURL = field.NewString(table, "resume_url")
	d.ProgressEid = field.NewUint32(table, "progress_eid")
	d.Progress = field.NewString(table, "progress")
	d.IsReal = field.NewUint32(table, "is_real")
	d.DeliverTime = field.NewUint64(table, "deliver_time")
	d.CreatedTime = field.NewInt64(table, "created_time")
	d.UpdatedTime = field.NewInt64(table, "updated_time")

	d.fillFieldMap()

	return d
}

func (d *deliver) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deliver) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 21)
	d.fieldMap["id"] = d.ID
	d.fieldMap["type"] = d.Type
	d.fieldMap["account_id"] = d.AccountID
	d.fieldMap["account_name"] = d.AccountName
	d.fieldMap["account_mobile"] = d.AccountMobile
	d.fieldMap["name"] = d.Name
	d.fieldMap["mobile"] = d.Mobile
	d.fieldMap["email"] = d.Email
	d.fieldMap["passage_id"] = d.PassageID
	d.fieldMap["passage_recommend_id"] = d.PassageRecommendID
	d.fieldMap["passage_recommend_path"] = d.PassageRecommendPath
	d.fieldMap["passage_recommend_path_full"] = d.PassageRecommendPathFull
	d.fieldMap["recommend_account_id"] = d.RecommendAccountID
	d.fieldMap["recommend_comment"] = d.RecommendComment
	d.fieldMap["resume_url"] = d.ResumeURL
	d.fieldMap["progress_eid"] = d.ProgressEid
	d.fieldMap["progress"] = d.Progress
	d.fieldMap["is_real"] = d.IsReal
	d.fieldMap["deliver_time"] = d.DeliverTime
	d.fieldMap["created_time"] = d.CreatedTime
	d.fieldMap["updated_time"] = d.UpdatedTime
}

func (d deliver) clone(db *gorm.DB) deliver {
	d.deliverDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deliver) replaceDB(db *gorm.DB) deliver {
	d.deliverDo.ReplaceDB(db)
	return d
}

type deliverDo struct{ gen.DO }

type IDeliverDo interface {
	gen.SubQuery
	Debug() IDeliverDo
	WithContext(ctx context.Context) IDeliverDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeliverDo
	WriteDB() IDeliverDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeliverDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeliverDo
	Not(conds ...gen.Condition) IDeliverDo
	Or(conds ...gen.Condition) IDeliverDo
	Select(conds ...field.Expr) IDeliverDo
	Where(conds ...gen.Condition) IDeliverDo
	Order(conds ...field.Expr) IDeliverDo
	Distinct(cols ...field.Expr) IDeliverDo
	Omit(cols ...field.Expr) IDeliverDo
	Join(table schema.Tabler, on ...field.Expr) IDeliverDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeliverDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeliverDo
	Group(cols ...field.Expr) IDeliverDo
	Having(conds ...gen.Condition) IDeliverDo
	Limit(limit int) IDeliverDo
	Offset(offset int) IDeliverDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeliverDo
	Unscoped() IDeliverDo
	Create(values ...*model.Deliver) error
	CreateInBatches(values []*model.Deliver, batchSize int) error
	Save(values ...*model.Deliver) error
	First() (*model.Deliver, error)
	Take() (*model.Deliver, error)
	Last() (*model.Deliver, error)
	Find() ([]*model.Deliver, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Deliver, err error)
	FindInBatches(result *[]*model.Deliver, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Deliver) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeliverDo
	Assign(attrs ...field.AssignExpr) IDeliverDo
	Joins(fields ...field.RelationField) IDeliverDo
	Preload(fields ...field.RelationField) IDeliverDo
	FirstOrInit() (*model.Deliver, error)
	FirstOrCreate() (*model.Deliver, error)
	FindByPage(offset int, limit int) (result []*model.Deliver, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeliverDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deliverDo) Debug() IDeliverDo {
	return d.withDO(d.DO.Debug())
}

func (d deliverDo) WithContext(ctx context.Context) IDeliverDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deliverDo) ReadDB() IDeliverDo {
	return d.Clauses(dbresolver.Read)
}

func (d deliverDo) WriteDB() IDeliverDo {
	return d.Clauses(dbresolver.Write)
}

func (d deliverDo) Session(config *gorm.Session) IDeliverDo {
	return d.withDO(d.DO.Session(config))
}

func (d deliverDo) Clauses(conds ...clause.Expression) IDeliverDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deliverDo) Returning(value interface{}, columns ...string) IDeliverDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deliverDo) Not(conds ...gen.Condition) IDeliverDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deliverDo) Or(conds ...gen.Condition) IDeliverDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deliverDo) Select(conds ...field.Expr) IDeliverDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deliverDo) Where(conds ...gen.Condition) IDeliverDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deliverDo) Order(conds ...field.Expr) IDeliverDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deliverDo) Distinct(cols ...field.Expr) IDeliverDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deliverDo) Omit(cols ...field.Expr) IDeliverDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deliverDo) Join(table schema.Tabler, on ...field.Expr) IDeliverDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deliverDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeliverDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deliverDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeliverDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deliverDo) Group(cols ...field.Expr) IDeliverDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deliverDo) Having(conds ...gen.Condition) IDeliverDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deliverDo) Limit(limit int) IDeliverDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deliverDo) Offset(offset int) IDeliverDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deliverDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeliverDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deliverDo) Unscoped() IDeliverDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deliverDo) Create(values ...*model.Deliver) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deliverDo) CreateInBatches(values []*model.Deliver, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deliverDo) Save(values ...*model.Deliver) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deliverDo) First() (*model.Deliver, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Deliver), nil
	}
}

func (d deliverDo) Take() (*model.Deliver, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Deliver), nil
	}
}

func (d deliverDo) Last() (*model.Deliver, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Deliver), nil
	}
}

func (d deliverDo) Find() ([]*model.Deliver, error) {
	result, err := d.DO.Find()
	return result.([]*model.Deliver), err
}

func (d deliverDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Deliver, err error) {
	buf := make([]*model.Deliver, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deliverDo) FindInBatches(result *[]*model.Deliver, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deliverDo) Attrs(attrs ...field.AssignExpr) IDeliverDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deliverDo) Assign(attrs ...field.AssignExpr) IDeliverDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deliverDo) Joins(fields ...field.RelationField) IDeliverDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deliverDo) Preload(fields ...field.RelationField) IDeliverDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deliverDo) FirstOrInit() (*model.Deliver, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Deliver), nil
	}
}

func (d deliverDo) FirstOrCreate() (*model.Deliver, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Deliver), nil
	}
}

func (d deliverDo) FindByPage(offset int, limit int) (result []*model.Deliver, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deliverDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deliverDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deliverDo) Delete(models ...*model.Deliver) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deliverDo) withDO(do gen.Dao) *deliverDo {
	d.DO = *do.(*gen.DO)
	return d
}
