// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newFinancingDemand(db *gorm.DB, opts ...gen.DOOption) financingDemand {
	_financingDemand := financingDemand{}

	_financingDemand.financingDemandDo.UseDB(db, opts...)
	_financingDemand.financingDemandDo.UseModel(&model.FinancingDemand{})

	tableName := _financingDemand.financingDemandDo.TableName()
	_financingDemand.ALL = field.NewAsterisk(tableName)
	_financingDemand.ID = field.NewInt32(tableName, "id")
	_financingDemand.Type = field.NewString(tableName, "type")
	_financingDemand.Title = field.NewString(tableName, "title")
	_financingDemand.Digest = field.NewString(tableName, "digest")
	_financingDemand.ImageURL = field.NewString(tableName, "image_url")
	_financingDemand.TimeBegin = field.NewInt32(tableName, "time_begin")
	_financingDemand.TimeEnd = field.NewInt32(tableName, "time_end")
	_financingDemand.PeopleDemand = field.NewString(tableName, "people_demand")
	_financingDemand.Cost = field.NewString(tableName, "cost")
	_financingDemand.Address = field.NewString(tableName, "address")
	_financingDemand.Content = field.NewString(tableName, "content")
	_financingDemand.Requirement = field.NewString(tableName, "requirement")
	_financingDemand.Attention = field.NewString(tableName, "attention")
	_financingDemand.AdminID = field.NewInt32(tableName, "admin_id")
	_financingDemand.CompanyID = field.NewInt32(tableName, "company_id")
	_financingDemand.City = field.NewString(tableName, "city")
	_financingDemand.MeetingCategory = field.NewString(tableName, "meeting_category")
	_financingDemand.PositionTag = field.NewString(tableName, "position_tag")
	_financingDemand.Experience = field.NewString(tableName, "experience")
	_financingDemand.Salary = field.NewString(tableName, "salary")
	_financingDemand.PassageIds = field.NewString(tableName, "passage_ids")
	_financingDemand.AccountID = field.NewUint32(tableName, "account_id")
	_financingDemand.SourceURL = field.NewString(tableName, "source_url")
	_financingDemand.IsTop = field.NewInt32(tableName, "is_top")
	_financingDemand.Pulisher = field.NewString(tableName, "pulisher")
	_financingDemand.ViewCount = field.NewInt32(tableName, "view_count")
	_financingDemand.LikeCount = field.NewUint32(tableName, "like_count")
	_financingDemand.TimeInsert = field.NewInt32(tableName, "time_insert")
	_financingDemand.TimeUpdate = field.NewInt32(tableName, "time_update")
	_financingDemand.Status = field.NewInt32(tableName, "status")

	_financingDemand.fillFieldMap()

	return _financingDemand
}

type financingDemand struct {
	financingDemandDo

	ALL             field.Asterisk
	ID              field.Int32
	Type            field.String
	Title           field.String
	Digest          field.String
	ImageURL        field.String
	TimeBegin       field.Int32
	TimeEnd         field.Int32
	PeopleDemand    field.String
	Cost            field.String
	Address         field.String
	Content         field.String
	Requirement     field.String // 参与条件
	Attention       field.String // 注意事项
	AdminID         field.Int32
	CompanyID       field.Int32
	City            field.String
	MeetingCategory field.String
	PositionTag     field.String
	Experience      field.String
	Salary          field.String
	PassageIds      field.String // 关联的职位id列表
	AccountID       field.Uint32 // 文章account_id
	SourceURL       field.String // 原文地址
	IsTop           field.Int32  // 是否置顶
	Pulisher        field.String // 发布者
	ViewCount       field.Int32  // 阅读数量
	LikeCount       field.Uint32 // 点赞量
	TimeInsert      field.Int32
	TimeUpdate      field.Int32
	Status          field.Int32

	fieldMap map[string]field.Expr
}

func (f financingDemand) Table(newTableName string) *financingDemand {
	f.financingDemandDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f financingDemand) As(alias string) *financingDemand {
	f.financingDemandDo.DO = *(f.financingDemandDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *financingDemand) updateTableName(table string) *financingDemand {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt32(table, "id")
	f.Type = field.NewString(table, "type")
	f.Title = field.NewString(table, "title")
	f.Digest = field.NewString(table, "digest")
	f.ImageURL = field.NewString(table, "image_url")
	f.TimeBegin = field.NewInt32(table, "time_begin")
	f.TimeEnd = field.NewInt32(table, "time_end")
	f.PeopleDemand = field.NewString(table, "people_demand")
	f.Cost = field.NewString(table, "cost")
	f.Address = field.NewString(table, "address")
	f.Content = field.NewString(table, "content")
	f.Requirement = field.NewString(table, "requirement")
	f.Attention = field.NewString(table, "attention")
	f.AdminID = field.NewInt32(table, "admin_id")
	f.CompanyID = field.NewInt32(table, "company_id")
	f.City = field.NewString(table, "city")
	f.MeetingCategory = field.NewString(table, "meeting_category")
	f.PositionTag = field.NewString(table, "position_tag")
	f.Experience = field.NewString(table, "experience")
	f.Salary = field.NewString(table, "salary")
	f.PassageIds = field.NewString(table, "passage_ids")
	f.AccountID = field.NewUint32(table, "account_id")
	f.SourceURL = field.NewString(table, "source_url")
	f.IsTop = field.NewInt32(table, "is_top")
	f.Pulisher = field.NewString(table, "pulisher")
	f.ViewCount = field.NewInt32(table, "view_count")
	f.LikeCount = field.NewUint32(table, "like_count")
	f.TimeInsert = field.NewInt32(table, "time_insert")
	f.TimeUpdate = field.NewInt32(table, "time_update")
	f.Status = field.NewInt32(table, "status")

	f.fillFieldMap()

	return f
}

func (f *financingDemand) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *financingDemand) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 30)
	f.fieldMap["id"] = f.ID
	f.fieldMap["type"] = f.Type
	f.fieldMap["title"] = f.Title
	f.fieldMap["digest"] = f.Digest
	f.fieldMap["image_url"] = f.ImageURL
	f.fieldMap["time_begin"] = f.TimeBegin
	f.fieldMap["time_end"] = f.TimeEnd
	f.fieldMap["people_demand"] = f.PeopleDemand
	f.fieldMap["cost"] = f.Cost
	f.fieldMap["address"] = f.Address
	f.fieldMap["content"] = f.Content
	f.fieldMap["requirement"] = f.Requirement
	f.fieldMap["attention"] = f.Attention
	f.fieldMap["admin_id"] = f.AdminID
	f.fieldMap["company_id"] = f.CompanyID
	f.fieldMap["city"] = f.City
	f.fieldMap["meeting_category"] = f.MeetingCategory
	f.fieldMap["position_tag"] = f.PositionTag
	f.fieldMap["experience"] = f.Experience
	f.fieldMap["salary"] = f.Salary
	f.fieldMap["passage_ids"] = f.PassageIds
	f.fieldMap["account_id"] = f.AccountID
	f.fieldMap["source_url"] = f.SourceURL
	f.fieldMap["is_top"] = f.IsTop
	f.fieldMap["pulisher"] = f.Pulisher
	f.fieldMap["view_count"] = f.ViewCount
	f.fieldMap["like_count"] = f.LikeCount
	f.fieldMap["time_insert"] = f.TimeInsert
	f.fieldMap["time_update"] = f.TimeUpdate
	f.fieldMap["status"] = f.Status
}

func (f financingDemand) clone(db *gorm.DB) financingDemand {
	f.financingDemandDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f financingDemand) replaceDB(db *gorm.DB) financingDemand {
	f.financingDemandDo.ReplaceDB(db)
	return f
}

type financingDemandDo struct{ gen.DO }

type IFinancingDemandDo interface {
	gen.SubQuery
	Debug() IFinancingDemandDo
	WithContext(ctx context.Context) IFinancingDemandDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFinancingDemandDo
	WriteDB() IFinancingDemandDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFinancingDemandDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFinancingDemandDo
	Not(conds ...gen.Condition) IFinancingDemandDo
	Or(conds ...gen.Condition) IFinancingDemandDo
	Select(conds ...field.Expr) IFinancingDemandDo
	Where(conds ...gen.Condition) IFinancingDemandDo
	Order(conds ...field.Expr) IFinancingDemandDo
	Distinct(cols ...field.Expr) IFinancingDemandDo
	Omit(cols ...field.Expr) IFinancingDemandDo
	Join(table schema.Tabler, on ...field.Expr) IFinancingDemandDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFinancingDemandDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFinancingDemandDo
	Group(cols ...field.Expr) IFinancingDemandDo
	Having(conds ...gen.Condition) IFinancingDemandDo
	Limit(limit int) IFinancingDemandDo
	Offset(offset int) IFinancingDemandDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFinancingDemandDo
	Unscoped() IFinancingDemandDo
	Create(values ...*model.FinancingDemand) error
	CreateInBatches(values []*model.FinancingDemand, batchSize int) error
	Save(values ...*model.FinancingDemand) error
	First() (*model.FinancingDemand, error)
	Take() (*model.FinancingDemand, error)
	Last() (*model.FinancingDemand, error)
	Find() ([]*model.FinancingDemand, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FinancingDemand, err error)
	FindInBatches(result *[]*model.FinancingDemand, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FinancingDemand) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFinancingDemandDo
	Assign(attrs ...field.AssignExpr) IFinancingDemandDo
	Joins(fields ...field.RelationField) IFinancingDemandDo
	Preload(fields ...field.RelationField) IFinancingDemandDo
	FirstOrInit() (*model.FinancingDemand, error)
	FirstOrCreate() (*model.FinancingDemand, error)
	FindByPage(offset int, limit int) (result []*model.FinancingDemand, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFinancingDemandDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f financingDemandDo) Debug() IFinancingDemandDo {
	return f.withDO(f.DO.Debug())
}

func (f financingDemandDo) WithContext(ctx context.Context) IFinancingDemandDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f financingDemandDo) ReadDB() IFinancingDemandDo {
	return f.Clauses(dbresolver.Read)
}

func (f financingDemandDo) WriteDB() IFinancingDemandDo {
	return f.Clauses(dbresolver.Write)
}

func (f financingDemandDo) Session(config *gorm.Session) IFinancingDemandDo {
	return f.withDO(f.DO.Session(config))
}

func (f financingDemandDo) Clauses(conds ...clause.Expression) IFinancingDemandDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f financingDemandDo) Returning(value interface{}, columns ...string) IFinancingDemandDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f financingDemandDo) Not(conds ...gen.Condition) IFinancingDemandDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f financingDemandDo) Or(conds ...gen.Condition) IFinancingDemandDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f financingDemandDo) Select(conds ...field.Expr) IFinancingDemandDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f financingDemandDo) Where(conds ...gen.Condition) IFinancingDemandDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f financingDemandDo) Order(conds ...field.Expr) IFinancingDemandDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f financingDemandDo) Distinct(cols ...field.Expr) IFinancingDemandDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f financingDemandDo) Omit(cols ...field.Expr) IFinancingDemandDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f financingDemandDo) Join(table schema.Tabler, on ...field.Expr) IFinancingDemandDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f financingDemandDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFinancingDemandDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f financingDemandDo) RightJoin(table schema.Tabler, on ...field.Expr) IFinancingDemandDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f financingDemandDo) Group(cols ...field.Expr) IFinancingDemandDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f financingDemandDo) Having(conds ...gen.Condition) IFinancingDemandDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f financingDemandDo) Limit(limit int) IFinancingDemandDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f financingDemandDo) Offset(offset int) IFinancingDemandDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f financingDemandDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFinancingDemandDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f financingDemandDo) Unscoped() IFinancingDemandDo {
	return f.withDO(f.DO.Unscoped())
}

func (f financingDemandDo) Create(values ...*model.FinancingDemand) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f financingDemandDo) CreateInBatches(values []*model.FinancingDemand, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f financingDemandDo) Save(values ...*model.FinancingDemand) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f financingDemandDo) First() (*model.FinancingDemand, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FinancingDemand), nil
	}
}

func (f financingDemandDo) Take() (*model.FinancingDemand, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FinancingDemand), nil
	}
}

func (f financingDemandDo) Last() (*model.FinancingDemand, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FinancingDemand), nil
	}
}

func (f financingDemandDo) Find() ([]*model.FinancingDemand, error) {
	result, err := f.DO.Find()
	return result.([]*model.FinancingDemand), err
}

func (f financingDemandDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FinancingDemand, err error) {
	buf := make([]*model.FinancingDemand, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f financingDemandDo) FindInBatches(result *[]*model.FinancingDemand, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f financingDemandDo) Attrs(attrs ...field.AssignExpr) IFinancingDemandDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f financingDemandDo) Assign(attrs ...field.AssignExpr) IFinancingDemandDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f financingDemandDo) Joins(fields ...field.RelationField) IFinancingDemandDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f financingDemandDo) Preload(fields ...field.RelationField) IFinancingDemandDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f financingDemandDo) FirstOrInit() (*model.FinancingDemand, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FinancingDemand), nil
	}
}

func (f financingDemandDo) FirstOrCreate() (*model.FinancingDemand, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FinancingDemand), nil
	}
}

func (f financingDemandDo) FindByPage(offset int, limit int) (result []*model.FinancingDemand, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f financingDemandDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f financingDemandDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f financingDemandDo) Delete(models ...*model.FinancingDemand) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *financingDemandDo) withDO(do gen.Dao) *financingDemandDo {
	f.DO = *do.(*gen.DO)
	return f
}
