// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newIndustryInfo(db *gorm.DB, opts ...gen.DOOption) industryInfo {
	_industryInfo := industryInfo{}

	_industryInfo.industryInfoDo.UseDB(db, opts...)
	_industryInfo.industryInfoDo.UseModel(&model.IndustryInfo{})

	tableName := _industryInfo.industryInfoDo.TableName()
	_industryInfo.ALL = field.NewAsterisk(tableName)
	_industryInfo.ID = field.NewInt32(tableName, "id")
	_industryInfo.Type = field.NewString(tableName, "type")
	_industryInfo.Title = field.NewString(tableName, "title")
	_industryInfo.Digest = field.NewString(tableName, "digest")
	_industryInfo.ImageURL = field.NewString(tableName, "image_url")
	_industryInfo.TimeBegin = field.NewInt32(tableName, "time_begin")
	_industryInfo.TimeEnd = field.NewInt32(tableName, "time_end")
	_industryInfo.PeopleDemand = field.NewString(tableName, "people_demand")
	_industryInfo.Cost = field.NewString(tableName, "cost")
	_industryInfo.Address = field.NewString(tableName, "address")
	_industryInfo.Content = field.NewString(tableName, "content")
	_industryInfo.Requirement = field.NewString(tableName, "requirement")
	_industryInfo.Attention = field.NewString(tableName, "attention")
	_industryInfo.AdminID = field.NewInt32(tableName, "admin_id")
	_industryInfo.CompanyID = field.NewInt32(tableName, "company_id")
	_industryInfo.City = field.NewString(tableName, "city")
	_industryInfo.MeetingCategory = field.NewString(tableName, "meeting_category")
	_industryInfo.PositionTag = field.NewString(tableName, "position_tag")
	_industryInfo.Experience = field.NewString(tableName, "experience")
	_industryInfo.Salary = field.NewString(tableName, "salary")
	_industryInfo.PassageIds = field.NewString(tableName, "passage_ids")
	_industryInfo.AccountID = field.NewUint32(tableName, "account_id")
	_industryInfo.SourceURL = field.NewString(tableName, "source_url")
	_industryInfo.IsTop = field.NewInt32(tableName, "is_top")
	_industryInfo.Pulisher = field.NewString(tableName, "pulisher")
	_industryInfo.ViewCount = field.NewInt32(tableName, "view_count")
	_industryInfo.LikeCount = field.NewUint32(tableName, "like_count")
	_industryInfo.TimeInsert = field.NewInt32(tableName, "time_insert")
	_industryInfo.TimeUpdate = field.NewInt32(tableName, "time_update")
	_industryInfo.Status = field.NewInt32(tableName, "status")

	_industryInfo.fillFieldMap()

	return _industryInfo
}

type industryInfo struct {
	industryInfoDo

	ALL             field.Asterisk
	ID              field.Int32
	Type            field.String
	Title           field.String
	Digest          field.String
	ImageURL        field.String
	TimeBegin       field.Int32
	TimeEnd         field.Int32
	PeopleDemand    field.String
	Cost            field.String
	Address         field.String
	Content         field.String
	Requirement     field.String // 参与条件
	Attention       field.String // 注意事项
	AdminID         field.Int32
	CompanyID       field.Int32
	City            field.String
	MeetingCategory field.String
	PositionTag     field.String
	Experience      field.String
	Salary          field.String
	PassageIds      field.String // 关联的职位id列表
	AccountID       field.Uint32 // 文章account_id
	SourceURL       field.String // 原文地址
	IsTop           field.Int32  // 是否置顶
	Pulisher        field.String // 发布者
	ViewCount       field.Int32  // 阅读数量
	LikeCount       field.Uint32 // 点赞量
	TimeInsert      field.Int32
	TimeUpdate      field.Int32
	Status          field.Int32

	fieldMap map[string]field.Expr
}

func (i industryInfo) Table(newTableName string) *industryInfo {
	i.industryInfoDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i industryInfo) As(alias string) *industryInfo {
	i.industryInfoDo.DO = *(i.industryInfoDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *industryInfo) updateTableName(table string) *industryInfo {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt32(table, "id")
	i.Type = field.NewString(table, "type")
	i.Title = field.NewString(table, "title")
	i.Digest = field.NewString(table, "digest")
	i.ImageURL = field.NewString(table, "image_url")
	i.TimeBegin = field.NewInt32(table, "time_begin")
	i.TimeEnd = field.NewInt32(table, "time_end")
	i.PeopleDemand = field.NewString(table, "people_demand")
	i.Cost = field.NewString(table, "cost")
	i.Address = field.NewString(table, "address")
	i.Content = field.NewString(table, "content")
	i.Requirement = field.NewString(table, "requirement")
	i.Attention = field.NewString(table, "attention")
	i.AdminID = field.NewInt32(table, "admin_id")
	i.CompanyID = field.NewInt32(table, "company_id")
	i.City = field.NewString(table, "city")
	i.MeetingCategory = field.NewString(table, "meeting_category")
	i.PositionTag = field.NewString(table, "position_tag")
	i.Experience = field.NewString(table, "experience")
	i.Salary = field.NewString(table, "salary")
	i.PassageIds = field.NewString(table, "passage_ids")
	i.AccountID = field.NewUint32(table, "account_id")
	i.SourceURL = field.NewString(table, "source_url")
	i.IsTop = field.NewInt32(table, "is_top")
	i.Pulisher = field.NewString(table, "pulisher")
	i.ViewCount = field.NewInt32(table, "view_count")
	i.LikeCount = field.NewUint32(table, "like_count")
	i.TimeInsert = field.NewInt32(table, "time_insert")
	i.TimeUpdate = field.NewInt32(table, "time_update")
	i.Status = field.NewInt32(table, "status")

	i.fillFieldMap()

	return i
}

func (i *industryInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *industryInfo) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 30)
	i.fieldMap["id"] = i.ID
	i.fieldMap["type"] = i.Type
	i.fieldMap["title"] = i.Title
	i.fieldMap["digest"] = i.Digest
	i.fieldMap["image_url"] = i.ImageURL
	i.fieldMap["time_begin"] = i.TimeBegin
	i.fieldMap["time_end"] = i.TimeEnd
	i.fieldMap["people_demand"] = i.PeopleDemand
	i.fieldMap["cost"] = i.Cost
	i.fieldMap["address"] = i.Address
	i.fieldMap["content"] = i.Content
	i.fieldMap["requirement"] = i.Requirement
	i.fieldMap["attention"] = i.Attention
	i.fieldMap["admin_id"] = i.AdminID
	i.fieldMap["company_id"] = i.CompanyID
	i.fieldMap["city"] = i.City
	i.fieldMap["meeting_category"] = i.MeetingCategory
	i.fieldMap["position_tag"] = i.PositionTag
	i.fieldMap["experience"] = i.Experience
	i.fieldMap["salary"] = i.Salary
	i.fieldMap["passage_ids"] = i.PassageIds
	i.fieldMap["account_id"] = i.AccountID
	i.fieldMap["source_url"] = i.SourceURL
	i.fieldMap["is_top"] = i.IsTop
	i.fieldMap["pulisher"] = i.Pulisher
	i.fieldMap["view_count"] = i.ViewCount
	i.fieldMap["like_count"] = i.LikeCount
	i.fieldMap["time_insert"] = i.TimeInsert
	i.fieldMap["time_update"] = i.TimeUpdate
	i.fieldMap["status"] = i.Status
}

func (i industryInfo) clone(db *gorm.DB) industryInfo {
	i.industryInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i industryInfo) replaceDB(db *gorm.DB) industryInfo {
	i.industryInfoDo.ReplaceDB(db)
	return i
}

type industryInfoDo struct{ gen.DO }

type IIndustryInfoDo interface {
	gen.SubQuery
	Debug() IIndustryInfoDo
	WithContext(ctx context.Context) IIndustryInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIndustryInfoDo
	WriteDB() IIndustryInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIndustryInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIndustryInfoDo
	Not(conds ...gen.Condition) IIndustryInfoDo
	Or(conds ...gen.Condition) IIndustryInfoDo
	Select(conds ...field.Expr) IIndustryInfoDo
	Where(conds ...gen.Condition) IIndustryInfoDo
	Order(conds ...field.Expr) IIndustryInfoDo
	Distinct(cols ...field.Expr) IIndustryInfoDo
	Omit(cols ...field.Expr) IIndustryInfoDo
	Join(table schema.Tabler, on ...field.Expr) IIndustryInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIndustryInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIndustryInfoDo
	Group(cols ...field.Expr) IIndustryInfoDo
	Having(conds ...gen.Condition) IIndustryInfoDo
	Limit(limit int) IIndustryInfoDo
	Offset(offset int) IIndustryInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIndustryInfoDo
	Unscoped() IIndustryInfoDo
	Create(values ...*model.IndustryInfo) error
	CreateInBatches(values []*model.IndustryInfo, batchSize int) error
	Save(values ...*model.IndustryInfo) error
	First() (*model.IndustryInfo, error)
	Take() (*model.IndustryInfo, error)
	Last() (*model.IndustryInfo, error)
	Find() ([]*model.IndustryInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IndustryInfo, err error)
	FindInBatches(result *[]*model.IndustryInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IndustryInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIndustryInfoDo
	Assign(attrs ...field.AssignExpr) IIndustryInfoDo
	Joins(fields ...field.RelationField) IIndustryInfoDo
	Preload(fields ...field.RelationField) IIndustryInfoDo
	FirstOrInit() (*model.IndustryInfo, error)
	FirstOrCreate() (*model.IndustryInfo, error)
	FindByPage(offset int, limit int) (result []*model.IndustryInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIndustryInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i industryInfoDo) Debug() IIndustryInfoDo {
	return i.withDO(i.DO.Debug())
}

func (i industryInfoDo) WithContext(ctx context.Context) IIndustryInfoDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i industryInfoDo) ReadDB() IIndustryInfoDo {
	return i.Clauses(dbresolver.Read)
}

func (i industryInfoDo) WriteDB() IIndustryInfoDo {
	return i.Clauses(dbresolver.Write)
}

func (i industryInfoDo) Session(config *gorm.Session) IIndustryInfoDo {
	return i.withDO(i.DO.Session(config))
}

func (i industryInfoDo) Clauses(conds ...clause.Expression) IIndustryInfoDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i industryInfoDo) Returning(value interface{}, columns ...string) IIndustryInfoDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i industryInfoDo) Not(conds ...gen.Condition) IIndustryInfoDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i industryInfoDo) Or(conds ...gen.Condition) IIndustryInfoDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i industryInfoDo) Select(conds ...field.Expr) IIndustryInfoDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i industryInfoDo) Where(conds ...gen.Condition) IIndustryInfoDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i industryInfoDo) Order(conds ...field.Expr) IIndustryInfoDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i industryInfoDo) Distinct(cols ...field.Expr) IIndustryInfoDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i industryInfoDo) Omit(cols ...field.Expr) IIndustryInfoDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i industryInfoDo) Join(table schema.Tabler, on ...field.Expr) IIndustryInfoDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i industryInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIndustryInfoDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i industryInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) IIndustryInfoDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i industryInfoDo) Group(cols ...field.Expr) IIndustryInfoDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i industryInfoDo) Having(conds ...gen.Condition) IIndustryInfoDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i industryInfoDo) Limit(limit int) IIndustryInfoDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i industryInfoDo) Offset(offset int) IIndustryInfoDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i industryInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIndustryInfoDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i industryInfoDo) Unscoped() IIndustryInfoDo {
	return i.withDO(i.DO.Unscoped())
}

func (i industryInfoDo) Create(values ...*model.IndustryInfo) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i industryInfoDo) CreateInBatches(values []*model.IndustryInfo, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i industryInfoDo) Save(values ...*model.IndustryInfo) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i industryInfoDo) First() (*model.IndustryInfo, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IndustryInfo), nil
	}
}

func (i industryInfoDo) Take() (*model.IndustryInfo, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IndustryInfo), nil
	}
}

func (i industryInfoDo) Last() (*model.IndustryInfo, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IndustryInfo), nil
	}
}

func (i industryInfoDo) Find() ([]*model.IndustryInfo, error) {
	result, err := i.DO.Find()
	return result.([]*model.IndustryInfo), err
}

func (i industryInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IndustryInfo, err error) {
	buf := make([]*model.IndustryInfo, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i industryInfoDo) FindInBatches(result *[]*model.IndustryInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i industryInfoDo) Attrs(attrs ...field.AssignExpr) IIndustryInfoDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i industryInfoDo) Assign(attrs ...field.AssignExpr) IIndustryInfoDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i industryInfoDo) Joins(fields ...field.RelationField) IIndustryInfoDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i industryInfoDo) Preload(fields ...field.RelationField) IIndustryInfoDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i industryInfoDo) FirstOrInit() (*model.IndustryInfo, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IndustryInfo), nil
	}
}

func (i industryInfoDo) FirstOrCreate() (*model.IndustryInfo, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IndustryInfo), nil
	}
}

func (i industryInfoDo) FindByPage(offset int, limit int) (result []*model.IndustryInfo, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i industryInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i industryInfoDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i industryInfoDo) Delete(models ...*model.IndustryInfo) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *industryInfoDo) withDO(do gen.Dao) *industryInfoDo {
	i.DO = *do.(*gen.DO)
	return i
}
