// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newMeetingJoin(db *gorm.DB, opts ...gen.DOOption) meetingJoin {
	_meetingJoin := meetingJoin{}

	_meetingJoin.meetingJoinDo.UseDB(db, opts...)
	_meetingJoin.meetingJoinDo.UseModel(&model.MeetingJoin{})

	tableName := _meetingJoin.meetingJoinDo.TableName()
	_meetingJoin.ALL = field.NewAsterisk(tableName)
	_meetingJoin.ID = field.NewInt32(tableName, "id")
	_meetingJoin.UserID = field.NewInt32(tableName, "user_id")
	_meetingJoin.MeetingID = field.NewInt32(tableName, "meeting_id")
	_meetingJoin.Name = field.NewString(tableName, "name")
	_meetingJoin.Company = field.NewString(tableName, "company")
	_meetingJoin.Position = field.NewString(tableName, "position")
	_meetingJoin.WechatID = field.NewString(tableName, "wechat_id")
	_meetingJoin.Birthday = field.NewString(tableName, "birthday")
	_meetingJoin.Message = field.NewString(tableName, "message")
	_meetingJoin.TimeInsert = field.NewInt32(tableName, "time_insert")
	_meetingJoin.Status = field.NewInt32(tableName, "status")

	_meetingJoin.fillFieldMap()

	return _meetingJoin
}

type meetingJoin struct {
	meetingJoinDo

	ALL        field.Asterisk
	ID         field.Int32
	UserID     field.Int32
	MeetingID  field.Int32
	Name       field.String
	Company    field.String
	Position   field.String
	WechatID   field.String // 微信号
	Birthday   field.String
	Message    field.String
	TimeInsert field.Int32
	Status     field.Int32

	fieldMap map[string]field.Expr
}

func (m meetingJoin) Table(newTableName string) *meetingJoin {
	m.meetingJoinDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m meetingJoin) As(alias string) *meetingJoin {
	m.meetingJoinDo.DO = *(m.meetingJoinDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *meetingJoin) updateTableName(table string) *meetingJoin {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt32(table, "id")
	m.UserID = field.NewInt32(table, "user_id")
	m.MeetingID = field.NewInt32(table, "meeting_id")
	m.Name = field.NewString(table, "name")
	m.Company = field.NewString(table, "company")
	m.Position = field.NewString(table, "position")
	m.WechatID = field.NewString(table, "wechat_id")
	m.Birthday = field.NewString(table, "birthday")
	m.Message = field.NewString(table, "message")
	m.TimeInsert = field.NewInt32(table, "time_insert")
	m.Status = field.NewInt32(table, "status")

	m.fillFieldMap()

	return m
}

func (m *meetingJoin) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *meetingJoin) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 11)
	m.fieldMap["id"] = m.ID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["meeting_id"] = m.MeetingID
	m.fieldMap["name"] = m.Name
	m.fieldMap["company"] = m.Company
	m.fieldMap["position"] = m.Position
	m.fieldMap["wechat_id"] = m.WechatID
	m.fieldMap["birthday"] = m.Birthday
	m.fieldMap["message"] = m.Message
	m.fieldMap["time_insert"] = m.TimeInsert
	m.fieldMap["status"] = m.Status
}

func (m meetingJoin) clone(db *gorm.DB) meetingJoin {
	m.meetingJoinDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m meetingJoin) replaceDB(db *gorm.DB) meetingJoin {
	m.meetingJoinDo.ReplaceDB(db)
	return m
}

type meetingJoinDo struct{ gen.DO }

type IMeetingJoinDo interface {
	gen.SubQuery
	Debug() IMeetingJoinDo
	WithContext(ctx context.Context) IMeetingJoinDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMeetingJoinDo
	WriteDB() IMeetingJoinDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMeetingJoinDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMeetingJoinDo
	Not(conds ...gen.Condition) IMeetingJoinDo
	Or(conds ...gen.Condition) IMeetingJoinDo
	Select(conds ...field.Expr) IMeetingJoinDo
	Where(conds ...gen.Condition) IMeetingJoinDo
	Order(conds ...field.Expr) IMeetingJoinDo
	Distinct(cols ...field.Expr) IMeetingJoinDo
	Omit(cols ...field.Expr) IMeetingJoinDo
	Join(table schema.Tabler, on ...field.Expr) IMeetingJoinDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingJoinDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMeetingJoinDo
	Group(cols ...field.Expr) IMeetingJoinDo
	Having(conds ...gen.Condition) IMeetingJoinDo
	Limit(limit int) IMeetingJoinDo
	Offset(offset int) IMeetingJoinDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingJoinDo
	Unscoped() IMeetingJoinDo
	Create(values ...*model.MeetingJoin) error
	CreateInBatches(values []*model.MeetingJoin, batchSize int) error
	Save(values ...*model.MeetingJoin) error
	First() (*model.MeetingJoin, error)
	Take() (*model.MeetingJoin, error)
	Last() (*model.MeetingJoin, error)
	Find() ([]*model.MeetingJoin, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MeetingJoin, err error)
	FindInBatches(result *[]*model.MeetingJoin, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MeetingJoin) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMeetingJoinDo
	Assign(attrs ...field.AssignExpr) IMeetingJoinDo
	Joins(fields ...field.RelationField) IMeetingJoinDo
	Preload(fields ...field.RelationField) IMeetingJoinDo
	FirstOrInit() (*model.MeetingJoin, error)
	FirstOrCreate() (*model.MeetingJoin, error)
	FindByPage(offset int, limit int) (result []*model.MeetingJoin, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMeetingJoinDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m meetingJoinDo) Debug() IMeetingJoinDo {
	return m.withDO(m.DO.Debug())
}

func (m meetingJoinDo) WithContext(ctx context.Context) IMeetingJoinDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m meetingJoinDo) ReadDB() IMeetingJoinDo {
	return m.Clauses(dbresolver.Read)
}

func (m meetingJoinDo) WriteDB() IMeetingJoinDo {
	return m.Clauses(dbresolver.Write)
}

func (m meetingJoinDo) Session(config *gorm.Session) IMeetingJoinDo {
	return m.withDO(m.DO.Session(config))
}

func (m meetingJoinDo) Clauses(conds ...clause.Expression) IMeetingJoinDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m meetingJoinDo) Returning(value interface{}, columns ...string) IMeetingJoinDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m meetingJoinDo) Not(conds ...gen.Condition) IMeetingJoinDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m meetingJoinDo) Or(conds ...gen.Condition) IMeetingJoinDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m meetingJoinDo) Select(conds ...field.Expr) IMeetingJoinDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m meetingJoinDo) Where(conds ...gen.Condition) IMeetingJoinDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m meetingJoinDo) Order(conds ...field.Expr) IMeetingJoinDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m meetingJoinDo) Distinct(cols ...field.Expr) IMeetingJoinDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m meetingJoinDo) Omit(cols ...field.Expr) IMeetingJoinDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m meetingJoinDo) Join(table schema.Tabler, on ...field.Expr) IMeetingJoinDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m meetingJoinDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMeetingJoinDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m meetingJoinDo) RightJoin(table schema.Tabler, on ...field.Expr) IMeetingJoinDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m meetingJoinDo) Group(cols ...field.Expr) IMeetingJoinDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m meetingJoinDo) Having(conds ...gen.Condition) IMeetingJoinDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m meetingJoinDo) Limit(limit int) IMeetingJoinDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m meetingJoinDo) Offset(offset int) IMeetingJoinDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m meetingJoinDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMeetingJoinDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m meetingJoinDo) Unscoped() IMeetingJoinDo {
	return m.withDO(m.DO.Unscoped())
}

func (m meetingJoinDo) Create(values ...*model.MeetingJoin) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m meetingJoinDo) CreateInBatches(values []*model.MeetingJoin, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m meetingJoinDo) Save(values ...*model.MeetingJoin) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m meetingJoinDo) First() (*model.MeetingJoin, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MeetingJoin), nil
	}
}

func (m meetingJoinDo) Take() (*model.MeetingJoin, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MeetingJoin), nil
	}
}

func (m meetingJoinDo) Last() (*model.MeetingJoin, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MeetingJoin), nil
	}
}

func (m meetingJoinDo) Find() ([]*model.MeetingJoin, error) {
	result, err := m.DO.Find()
	return result.([]*model.MeetingJoin), err
}

func (m meetingJoinDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MeetingJoin, err error) {
	buf := make([]*model.MeetingJoin, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m meetingJoinDo) FindInBatches(result *[]*model.MeetingJoin, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m meetingJoinDo) Attrs(attrs ...field.AssignExpr) IMeetingJoinDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m meetingJoinDo) Assign(attrs ...field.AssignExpr) IMeetingJoinDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m meetingJoinDo) Joins(fields ...field.RelationField) IMeetingJoinDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m meetingJoinDo) Preload(fields ...field.RelationField) IMeetingJoinDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m meetingJoinDo) FirstOrInit() (*model.MeetingJoin, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MeetingJoin), nil
	}
}

func (m meetingJoinDo) FirstOrCreate() (*model.MeetingJoin, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MeetingJoin), nil
	}
}

func (m meetingJoinDo) FindByPage(offset int, limit int) (result []*model.MeetingJoin, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m meetingJoinDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m meetingJoinDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m meetingJoinDo) Delete(models ...*model.MeetingJoin) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *meetingJoinDo) withDO(do gen.Dao) *meetingJoinDo {
	m.DO = *do.(*gen.DO)
	return m
}
