// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newPassageCompany(db *gorm.DB, opts ...gen.DOOption) passageCompany {
	_passageCompany := passageCompany{}

	_passageCompany.passageCompanyDo.UseDB(db, opts...)
	_passageCompany.passageCompanyDo.UseModel(&model.PassageCompany{})

	tableName := _passageCompany.passageCompanyDo.TableName()
	_passageCompany.ALL = field.NewAsterisk(tableName)
	_passageCompany.ID = field.NewUint32(tableName, "id")
	_passageCompany.Icon = field.NewString(tableName, "icon")
	_passageCompany.Name = field.NewString(tableName, "name")
	_passageCompany.OutName = field.NewString(tableName, "out_name")
	_passageCompany.CityID = field.NewUint32(tableName, "city_id")
	_passageCompany.DistrictID = field.NewUint32(tableName, "district_id")
	_passageCompany.IndustryID = field.NewUint32(tableName, "industry_id")
	_passageCompany.IndustryPath = field.NewString(tableName, "industry_path")
	_passageCompany.Scale = field.NewUint32(tableName, "scale")
	_passageCompany.Stage = field.NewUint32(tableName, "stage")
	_passageCompany.Address = field.NewString(tableName, "address")
	_passageCompany.AddressID = field.NewUint32(tableName, "address_id")
	_passageCompany.Remark = field.NewString(tableName, "remark")
	_passageCompany.CompanyID = field.NewUint32(tableName, "company_id")
	_passageCompany.AdminID = field.NewUint32(tableName, "admin_id")
	_passageCompany.ModTime = field.NewUint32(tableName, "mod_time")
	_passageCompany.IsTop = field.NewUint32(tableName, "is_top")
	_passageCompany.Tags = field.NewString(tableName, "tags")
	_passageCompany.Sort = field.NewUint32(tableName, "sort")

	_passageCompany.fillFieldMap()

	return _passageCompany
}

type passageCompany struct {
	passageCompanyDo

	ALL          field.Asterisk
	ID           field.Uint32 // 主键
	Icon         field.String
	Name         field.String // 公司名称
	OutName      field.String // 对外简称
	CityID       field.Uint32
	DistrictID   field.Uint32
	IndustryID   field.Uint32 // 行业ID
	IndustryPath field.String
	Scale        field.Uint32 // 规模
	Stage        field.Uint32 // 阶段
	Address      field.String // 地址
	AddressID    field.Uint32 // 地址ID
	Remark       field.String // 公司简介
	CompanyID    field.Uint32 // 管理员企业
	AdminID      field.Uint32 // 更新adminID
	ModTime      field.Uint32 // 修改时间
	IsTop        field.Uint32
	Tags         field.String // 标签
	Sort         field.Uint32

	fieldMap map[string]field.Expr
}

func (p passageCompany) Table(newTableName string) *passageCompany {
	p.passageCompanyDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p passageCompany) As(alias string) *passageCompany {
	p.passageCompanyDo.DO = *(p.passageCompanyDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *passageCompany) updateTableName(table string) *passageCompany {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint32(table, "id")
	p.Icon = field.NewString(table, "icon")
	p.Name = field.NewString(table, "name")
	p.OutName = field.NewString(table, "out_name")
	p.CityID = field.NewUint32(table, "city_id")
	p.DistrictID = field.NewUint32(table, "district_id")
	p.IndustryID = field.NewUint32(table, "industry_id")
	p.IndustryPath = field.NewString(table, "industry_path")
	p.Scale = field.NewUint32(table, "scale")
	p.Stage = field.NewUint32(table, "stage")
	p.Address = field.NewString(table, "address")
	p.AddressID = field.NewUint32(table, "address_id")
	p.Remark = field.NewString(table, "remark")
	p.CompanyID = field.NewUint32(table, "company_id")
	p.AdminID = field.NewUint32(table, "admin_id")
	p.ModTime = field.NewUint32(table, "mod_time")
	p.IsTop = field.NewUint32(table, "is_top")
	p.Tags = field.NewString(table, "tags")
	p.Sort = field.NewUint32(table, "sort")

	p.fillFieldMap()

	return p
}

func (p *passageCompany) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *passageCompany) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 19)
	p.fieldMap["id"] = p.ID
	p.fieldMap["icon"] = p.Icon
	p.fieldMap["name"] = p.Name
	p.fieldMap["out_name"] = p.OutName
	p.fieldMap["city_id"] = p.CityID
	p.fieldMap["district_id"] = p.DistrictID
	p.fieldMap["industry_id"] = p.IndustryID
	p.fieldMap["industry_path"] = p.IndustryPath
	p.fieldMap["scale"] = p.Scale
	p.fieldMap["stage"] = p.Stage
	p.fieldMap["address"] = p.Address
	p.fieldMap["address_id"] = p.AddressID
	p.fieldMap["remark"] = p.Remark
	p.fieldMap["company_id"] = p.CompanyID
	p.fieldMap["admin_id"] = p.AdminID
	p.fieldMap["mod_time"] = p.ModTime
	p.fieldMap["is_top"] = p.IsTop
	p.fieldMap["tags"] = p.Tags
	p.fieldMap["sort"] = p.Sort
}

func (p passageCompany) clone(db *gorm.DB) passageCompany {
	p.passageCompanyDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p passageCompany) replaceDB(db *gorm.DB) passageCompany {
	p.passageCompanyDo.ReplaceDB(db)
	return p
}

type passageCompanyDo struct{ gen.DO }

type IPassageCompanyDo interface {
	gen.SubQuery
	Debug() IPassageCompanyDo
	WithContext(ctx context.Context) IPassageCompanyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPassageCompanyDo
	WriteDB() IPassageCompanyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPassageCompanyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPassageCompanyDo
	Not(conds ...gen.Condition) IPassageCompanyDo
	Or(conds ...gen.Condition) IPassageCompanyDo
	Select(conds ...field.Expr) IPassageCompanyDo
	Where(conds ...gen.Condition) IPassageCompanyDo
	Order(conds ...field.Expr) IPassageCompanyDo
	Distinct(cols ...field.Expr) IPassageCompanyDo
	Omit(cols ...field.Expr) IPassageCompanyDo
	Join(table schema.Tabler, on ...field.Expr) IPassageCompanyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPassageCompanyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPassageCompanyDo
	Group(cols ...field.Expr) IPassageCompanyDo
	Having(conds ...gen.Condition) IPassageCompanyDo
	Limit(limit int) IPassageCompanyDo
	Offset(offset int) IPassageCompanyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPassageCompanyDo
	Unscoped() IPassageCompanyDo
	Create(values ...*model.PassageCompany) error
	CreateInBatches(values []*model.PassageCompany, batchSize int) error
	Save(values ...*model.PassageCompany) error
	First() (*model.PassageCompany, error)
	Take() (*model.PassageCompany, error)
	Last() (*model.PassageCompany, error)
	Find() ([]*model.PassageCompany, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PassageCompany, err error)
	FindInBatches(result *[]*model.PassageCompany, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PassageCompany) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPassageCompanyDo
	Assign(attrs ...field.AssignExpr) IPassageCompanyDo
	Joins(fields ...field.RelationField) IPassageCompanyDo
	Preload(fields ...field.RelationField) IPassageCompanyDo
	FirstOrInit() (*model.PassageCompany, error)
	FirstOrCreate() (*model.PassageCompany, error)
	FindByPage(offset int, limit int) (result []*model.PassageCompany, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPassageCompanyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p passageCompanyDo) Debug() IPassageCompanyDo {
	return p.withDO(p.DO.Debug())
}

func (p passageCompanyDo) WithContext(ctx context.Context) IPassageCompanyDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p passageCompanyDo) ReadDB() IPassageCompanyDo {
	return p.Clauses(dbresolver.Read)
}

func (p passageCompanyDo) WriteDB() IPassageCompanyDo {
	return p.Clauses(dbresolver.Write)
}

func (p passageCompanyDo) Session(config *gorm.Session) IPassageCompanyDo {
	return p.withDO(p.DO.Session(config))
}

func (p passageCompanyDo) Clauses(conds ...clause.Expression) IPassageCompanyDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p passageCompanyDo) Returning(value interface{}, columns ...string) IPassageCompanyDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p passageCompanyDo) Not(conds ...gen.Condition) IPassageCompanyDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p passageCompanyDo) Or(conds ...gen.Condition) IPassageCompanyDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p passageCompanyDo) Select(conds ...field.Expr) IPassageCompanyDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p passageCompanyDo) Where(conds ...gen.Condition) IPassageCompanyDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p passageCompanyDo) Order(conds ...field.Expr) IPassageCompanyDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p passageCompanyDo) Distinct(cols ...field.Expr) IPassageCompanyDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p passageCompanyDo) Omit(cols ...field.Expr) IPassageCompanyDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p passageCompanyDo) Join(table schema.Tabler, on ...field.Expr) IPassageCompanyDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p passageCompanyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPassageCompanyDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p passageCompanyDo) RightJoin(table schema.Tabler, on ...field.Expr) IPassageCompanyDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p passageCompanyDo) Group(cols ...field.Expr) IPassageCompanyDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p passageCompanyDo) Having(conds ...gen.Condition) IPassageCompanyDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p passageCompanyDo) Limit(limit int) IPassageCompanyDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p passageCompanyDo) Offset(offset int) IPassageCompanyDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p passageCompanyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPassageCompanyDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p passageCompanyDo) Unscoped() IPassageCompanyDo {
	return p.withDO(p.DO.Unscoped())
}

func (p passageCompanyDo) Create(values ...*model.PassageCompany) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p passageCompanyDo) CreateInBatches(values []*model.PassageCompany, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p passageCompanyDo) Save(values ...*model.PassageCompany) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p passageCompanyDo) First() (*model.PassageCompany, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PassageCompany), nil
	}
}

func (p passageCompanyDo) Take() (*model.PassageCompany, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PassageCompany), nil
	}
}

func (p passageCompanyDo) Last() (*model.PassageCompany, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PassageCompany), nil
	}
}

func (p passageCompanyDo) Find() ([]*model.PassageCompany, error) {
	result, err := p.DO.Find()
	return result.([]*model.PassageCompany), err
}

func (p passageCompanyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PassageCompany, err error) {
	buf := make([]*model.PassageCompany, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p passageCompanyDo) FindInBatches(result *[]*model.PassageCompany, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p passageCompanyDo) Attrs(attrs ...field.AssignExpr) IPassageCompanyDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p passageCompanyDo) Assign(attrs ...field.AssignExpr) IPassageCompanyDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p passageCompanyDo) Joins(fields ...field.RelationField) IPassageCompanyDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p passageCompanyDo) Preload(fields ...field.RelationField) IPassageCompanyDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p passageCompanyDo) FirstOrInit() (*model.PassageCompany, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PassageCompany), nil
	}
}

func (p passageCompanyDo) FirstOrCreate() (*model.PassageCompany, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PassageCompany), nil
	}
}

func (p passageCompanyDo) FindByPage(offset int, limit int) (result []*model.PassageCompany, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p passageCompanyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p passageCompanyDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p passageCompanyDo) Delete(models ...*model.PassageCompany) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *passageCompanyDo) withDO(do gen.Dao) *passageCompanyDo {
	p.DO = *do.(*gen.DO)
	return p
}
