// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newPassageLike(db *gorm.DB, opts ...gen.DOOption) passageLike {
	_passageLike := passageLike{}

	_passageLike.passageLikeDo.UseDB(db, opts...)
	_passageLike.passageLikeDo.UseModel(&model.PassageLike{})

	tableName := _passageLike.passageLikeDo.TableName()
	_passageLike.ALL = field.NewAsterisk(tableName)
	_passageLike.ID = field.NewUint32(tableName, "id")
	_passageLike.AccountID = field.NewUint32(tableName, "account_id")
	_passageLike.PassageID = field.NewUint32(tableName, "passage_id")

	_passageLike.fillFieldMap()

	return _passageLike
}

type passageLike struct {
	passageLikeDo

	ALL       field.Asterisk
	ID        field.Uint32
	AccountID field.Uint32
	PassageID field.Uint32

	fieldMap map[string]field.Expr
}

func (p passageLike) Table(newTableName string) *passageLike {
	p.passageLikeDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p passageLike) As(alias string) *passageLike {
	p.passageLikeDo.DO = *(p.passageLikeDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *passageLike) updateTableName(table string) *passageLike {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint32(table, "id")
	p.AccountID = field.NewUint32(table, "account_id")
	p.PassageID = field.NewUint32(table, "passage_id")

	p.fillFieldMap()

	return p
}

func (p *passageLike) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *passageLike) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["id"] = p.ID
	p.fieldMap["account_id"] = p.AccountID
	p.fieldMap["passage_id"] = p.PassageID
}

func (p passageLike) clone(db *gorm.DB) passageLike {
	p.passageLikeDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p passageLike) replaceDB(db *gorm.DB) passageLike {
	p.passageLikeDo.ReplaceDB(db)
	return p
}

type passageLikeDo struct{ gen.DO }

type IPassageLikeDo interface {
	gen.SubQuery
	Debug() IPassageLikeDo
	WithContext(ctx context.Context) IPassageLikeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPassageLikeDo
	WriteDB() IPassageLikeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPassageLikeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPassageLikeDo
	Not(conds ...gen.Condition) IPassageLikeDo
	Or(conds ...gen.Condition) IPassageLikeDo
	Select(conds ...field.Expr) IPassageLikeDo
	Where(conds ...gen.Condition) IPassageLikeDo
	Order(conds ...field.Expr) IPassageLikeDo
	Distinct(cols ...field.Expr) IPassageLikeDo
	Omit(cols ...field.Expr) IPassageLikeDo
	Join(table schema.Tabler, on ...field.Expr) IPassageLikeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPassageLikeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPassageLikeDo
	Group(cols ...field.Expr) IPassageLikeDo
	Having(conds ...gen.Condition) IPassageLikeDo
	Limit(limit int) IPassageLikeDo
	Offset(offset int) IPassageLikeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPassageLikeDo
	Unscoped() IPassageLikeDo
	Create(values ...*model.PassageLike) error
	CreateInBatches(values []*model.PassageLike, batchSize int) error
	Save(values ...*model.PassageLike) error
	First() (*model.PassageLike, error)
	Take() (*model.PassageLike, error)
	Last() (*model.PassageLike, error)
	Find() ([]*model.PassageLike, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PassageLike, err error)
	FindInBatches(result *[]*model.PassageLike, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PassageLike) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPassageLikeDo
	Assign(attrs ...field.AssignExpr) IPassageLikeDo
	Joins(fields ...field.RelationField) IPassageLikeDo
	Preload(fields ...field.RelationField) IPassageLikeDo
	FirstOrInit() (*model.PassageLike, error)
	FirstOrCreate() (*model.PassageLike, error)
	FindByPage(offset int, limit int) (result []*model.PassageLike, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPassageLikeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p passageLikeDo) Debug() IPassageLikeDo {
	return p.withDO(p.DO.Debug())
}

func (p passageLikeDo) WithContext(ctx context.Context) IPassageLikeDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p passageLikeDo) ReadDB() IPassageLikeDo {
	return p.Clauses(dbresolver.Read)
}

func (p passageLikeDo) WriteDB() IPassageLikeDo {
	return p.Clauses(dbresolver.Write)
}

func (p passageLikeDo) Session(config *gorm.Session) IPassageLikeDo {
	return p.withDO(p.DO.Session(config))
}

func (p passageLikeDo) Clauses(conds ...clause.Expression) IPassageLikeDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p passageLikeDo) Returning(value interface{}, columns ...string) IPassageLikeDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p passageLikeDo) Not(conds ...gen.Condition) IPassageLikeDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p passageLikeDo) Or(conds ...gen.Condition) IPassageLikeDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p passageLikeDo) Select(conds ...field.Expr) IPassageLikeDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p passageLikeDo) Where(conds ...gen.Condition) IPassageLikeDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p passageLikeDo) Order(conds ...field.Expr) IPassageLikeDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p passageLikeDo) Distinct(cols ...field.Expr) IPassageLikeDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p passageLikeDo) Omit(cols ...field.Expr) IPassageLikeDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p passageLikeDo) Join(table schema.Tabler, on ...field.Expr) IPassageLikeDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p passageLikeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPassageLikeDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p passageLikeDo) RightJoin(table schema.Tabler, on ...field.Expr) IPassageLikeDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p passageLikeDo) Group(cols ...field.Expr) IPassageLikeDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p passageLikeDo) Having(conds ...gen.Condition) IPassageLikeDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p passageLikeDo) Limit(limit int) IPassageLikeDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p passageLikeDo) Offset(offset int) IPassageLikeDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p passageLikeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPassageLikeDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p passageLikeDo) Unscoped() IPassageLikeDo {
	return p.withDO(p.DO.Unscoped())
}

func (p passageLikeDo) Create(values ...*model.PassageLike) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p passageLikeDo) CreateInBatches(values []*model.PassageLike, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p passageLikeDo) Save(values ...*model.PassageLike) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p passageLikeDo) First() (*model.PassageLike, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PassageLike), nil
	}
}

func (p passageLikeDo) Take() (*model.PassageLike, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PassageLike), nil
	}
}

func (p passageLikeDo) Last() (*model.PassageLike, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PassageLike), nil
	}
}

func (p passageLikeDo) Find() ([]*model.PassageLike, error) {
	result, err := p.DO.Find()
	return result.([]*model.PassageLike), err
}

func (p passageLikeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PassageLike, err error) {
	buf := make([]*model.PassageLike, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p passageLikeDo) FindInBatches(result *[]*model.PassageLike, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p passageLikeDo) Attrs(attrs ...field.AssignExpr) IPassageLikeDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p passageLikeDo) Assign(attrs ...field.AssignExpr) IPassageLikeDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p passageLikeDo) Joins(fields ...field.RelationField) IPassageLikeDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p passageLikeDo) Preload(fields ...field.RelationField) IPassageLikeDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p passageLikeDo) FirstOrInit() (*model.PassageLike, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PassageLike), nil
	}
}

func (p passageLikeDo) FirstOrCreate() (*model.PassageLike, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PassageLike), nil
	}
}

func (p passageLikeDo) FindByPage(offset int, limit int) (result []*model.PassageLike, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p passageLikeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p passageLikeDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p passageLikeDo) Delete(models ...*model.PassageLike) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *passageLikeDo) withDO(do gen.Dao) *passageLikeDo {
	p.DO = *do.(*gen.DO)
	return p
}
