// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newProfService(db *gorm.DB, opts ...gen.DOOption) profService {
	_profService := profService{}

	_profService.profServiceDo.UseDB(db, opts...)
	_profService.profServiceDo.UseModel(&model.ProfService{})

	tableName := _profService.profServiceDo.TableName()
	_profService.ALL = field.NewAsterisk(tableName)
	_profService.ID = field.NewUint32(tableName, "id")
	_profService.Type = field.NewString(tableName, "type")
	_profService.Title = field.NewString(tableName, "title")
	_profService.Name = field.NewString(tableName, "name")
	_profService.Digest = field.NewString(tableName, "digest")
	_profService.RecommendText = field.NewString(tableName, "recommend_text")
	_profService.ImageURL = field.NewString(tableName, "image_url")
	_profService.Gender = field.NewString(tableName, "gender")
	_profService.AdminID = field.NewUint32(tableName, "admin_id")
	_profService.CompanyID = field.NewUint32(tableName, "company_id")
	_profService.City = field.NewString(tableName, "city")
	_profService.Experience = field.NewInt32(tableName, "experience")
	_profService.Education = field.NewString(tableName, "education")
	_profService.PositionTag = field.NewString(tableName, "position_tag")
	_profService.PassageIds = field.NewString(tableName, "passage_ids")
	_profService.AccountID = field.NewUint32(tableName, "account_id")
	_profService.WorkingStatus = field.NewString(tableName, "working_status")
	_profService.MaritalStatus = field.NewString(tableName, "marital_status")
	_profService.CurrentSalary = field.NewString(tableName, "current_salary")
	_profService.ExpectSalary = field.NewInt32(tableName, "expect_salary")
	_profService.Introduction = field.NewString(tableName, "introduction")
	_profService.Evaluation = field.NewString(tableName, "evaluation")
	_profService.ViewCount = field.NewUint32(tableName, "view_count")
	_profService.LikeCount = field.NewUint32(tableName, "like_count")
	_profService.TimeInsert = field.NewUint32(tableName, "time_insert")
	_profService.TimeUpdate = field.NewUint32(tableName, "time_update")
	_profService.Status = field.NewInt32(tableName, "status")
	_profService.Service = field.NewString(tableName, "service")
	_profService.Pulisher = field.NewString(tableName, "pulisher")

	_profService.fillFieldMap()

	return _profService
}

type profService struct {
	profServiceDo

	ALL           field.Asterisk
	ID            field.Uint32
	Type          field.String
	Title         field.String
	Name          field.String // 姓名
	Digest        field.String
	RecommendText field.String // 推荐语
	ImageURL      field.String
	Gender        field.String // 性别
	AdminID       field.Uint32
	CompanyID     field.Uint32
	City          field.String
	Experience    field.Int32
	Education     field.String
	PositionTag   field.String // 职位标签
	PassageIds    field.String
	AccountID     field.Uint32 // 文章account_id
	WorkingStatus field.String
	MaritalStatus field.String
	CurrentSalary field.String
	ExpectSalary  field.Int32
	Introduction  field.String // 基本简介
	Evaluation    field.String // 猎头评估
	ViewCount     field.Uint32 // 阅读数量
	LikeCount     field.Uint32 // 点赞量
	TimeInsert    field.Uint32
	TimeUpdate    field.Uint32
	Status        field.Int32
	Service       field.String // 服务项目
	Pulisher      field.String // 发布者

	fieldMap map[string]field.Expr
}

func (p profService) Table(newTableName string) *profService {
	p.profServiceDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p profService) As(alias string) *profService {
	p.profServiceDo.DO = *(p.profServiceDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *profService) updateTableName(table string) *profService {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint32(table, "id")
	p.Type = field.NewString(table, "type")
	p.Title = field.NewString(table, "title")
	p.Name = field.NewString(table, "name")
	p.Digest = field.NewString(table, "digest")
	p.RecommendText = field.NewString(table, "recommend_text")
	p.ImageURL = field.NewString(table, "image_url")
	p.Gender = field.NewString(table, "gender")
	p.AdminID = field.NewUint32(table, "admin_id")
	p.CompanyID = field.NewUint32(table, "company_id")
	p.City = field.NewString(table, "city")
	p.Experience = field.NewInt32(table, "experience")
	p.Education = field.NewString(table, "education")
	p.PositionTag = field.NewString(table, "position_tag")
	p.PassageIds = field.NewString(table, "passage_ids")
	p.AccountID = field.NewUint32(table, "account_id")
	p.WorkingStatus = field.NewString(table, "working_status")
	p.MaritalStatus = field.NewString(table, "marital_status")
	p.CurrentSalary = field.NewString(table, "current_salary")
	p.ExpectSalary = field.NewInt32(table, "expect_salary")
	p.Introduction = field.NewString(table, "introduction")
	p.Evaluation = field.NewString(table, "evaluation")
	p.ViewCount = field.NewUint32(table, "view_count")
	p.LikeCount = field.NewUint32(table, "like_count")
	p.TimeInsert = field.NewUint32(table, "time_insert")
	p.TimeUpdate = field.NewUint32(table, "time_update")
	p.Status = field.NewInt32(table, "status")
	p.Service = field.NewString(table, "service")
	p.Pulisher = field.NewString(table, "pulisher")

	p.fillFieldMap()

	return p
}

func (p *profService) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *profService) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 29)
	p.fieldMap["id"] = p.ID
	p.fieldMap["type"] = p.Type
	p.fieldMap["title"] = p.Title
	p.fieldMap["name"] = p.Name
	p.fieldMap["digest"] = p.Digest
	p.fieldMap["recommend_text"] = p.RecommendText
	p.fieldMap["image_url"] = p.ImageURL
	p.fieldMap["gender"] = p.Gender
	p.fieldMap["admin_id"] = p.AdminID
	p.fieldMap["company_id"] = p.CompanyID
	p.fieldMap["city"] = p.City
	p.fieldMap["experience"] = p.Experience
	p.fieldMap["education"] = p.Education
	p.fieldMap["position_tag"] = p.PositionTag
	p.fieldMap["passage_ids"] = p.PassageIds
	p.fieldMap["account_id"] = p.AccountID
	p.fieldMap["working_status"] = p.WorkingStatus
	p.fieldMap["marital_status"] = p.MaritalStatus
	p.fieldMap["current_salary"] = p.CurrentSalary
	p.fieldMap["expect_salary"] = p.ExpectSalary
	p.fieldMap["introduction"] = p.Introduction
	p.fieldMap["evaluation"] = p.Evaluation
	p.fieldMap["view_count"] = p.ViewCount
	p.fieldMap["like_count"] = p.LikeCount
	p.fieldMap["time_insert"] = p.TimeInsert
	p.fieldMap["time_update"] = p.TimeUpdate
	p.fieldMap["status"] = p.Status
	p.fieldMap["service"] = p.Service
	p.fieldMap["pulisher"] = p.Pulisher
}

func (p profService) clone(db *gorm.DB) profService {
	p.profServiceDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p profService) replaceDB(db *gorm.DB) profService {
	p.profServiceDo.ReplaceDB(db)
	return p
}

type profServiceDo struct{ gen.DO }

type IProfServiceDo interface {
	gen.SubQuery
	Debug() IProfServiceDo
	WithContext(ctx context.Context) IProfServiceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProfServiceDo
	WriteDB() IProfServiceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProfServiceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProfServiceDo
	Not(conds ...gen.Condition) IProfServiceDo
	Or(conds ...gen.Condition) IProfServiceDo
	Select(conds ...field.Expr) IProfServiceDo
	Where(conds ...gen.Condition) IProfServiceDo
	Order(conds ...field.Expr) IProfServiceDo
	Distinct(cols ...field.Expr) IProfServiceDo
	Omit(cols ...field.Expr) IProfServiceDo
	Join(table schema.Tabler, on ...field.Expr) IProfServiceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProfServiceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProfServiceDo
	Group(cols ...field.Expr) IProfServiceDo
	Having(conds ...gen.Condition) IProfServiceDo
	Limit(limit int) IProfServiceDo
	Offset(offset int) IProfServiceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProfServiceDo
	Unscoped() IProfServiceDo
	Create(values ...*model.ProfService) error
	CreateInBatches(values []*model.ProfService, batchSize int) error
	Save(values ...*model.ProfService) error
	First() (*model.ProfService, error)
	Take() (*model.ProfService, error)
	Last() (*model.ProfService, error)
	Find() ([]*model.ProfService, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProfService, err error)
	FindInBatches(result *[]*model.ProfService, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ProfService) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProfServiceDo
	Assign(attrs ...field.AssignExpr) IProfServiceDo
	Joins(fields ...field.RelationField) IProfServiceDo
	Preload(fields ...field.RelationField) IProfServiceDo
	FirstOrInit() (*model.ProfService, error)
	FirstOrCreate() (*model.ProfService, error)
	FindByPage(offset int, limit int) (result []*model.ProfService, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProfServiceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p profServiceDo) Debug() IProfServiceDo {
	return p.withDO(p.DO.Debug())
}

func (p profServiceDo) WithContext(ctx context.Context) IProfServiceDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p profServiceDo) ReadDB() IProfServiceDo {
	return p.Clauses(dbresolver.Read)
}

func (p profServiceDo) WriteDB() IProfServiceDo {
	return p.Clauses(dbresolver.Write)
}

func (p profServiceDo) Session(config *gorm.Session) IProfServiceDo {
	return p.withDO(p.DO.Session(config))
}

func (p profServiceDo) Clauses(conds ...clause.Expression) IProfServiceDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p profServiceDo) Returning(value interface{}, columns ...string) IProfServiceDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p profServiceDo) Not(conds ...gen.Condition) IProfServiceDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p profServiceDo) Or(conds ...gen.Condition) IProfServiceDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p profServiceDo) Select(conds ...field.Expr) IProfServiceDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p profServiceDo) Where(conds ...gen.Condition) IProfServiceDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p profServiceDo) Order(conds ...field.Expr) IProfServiceDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p profServiceDo) Distinct(cols ...field.Expr) IProfServiceDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p profServiceDo) Omit(cols ...field.Expr) IProfServiceDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p profServiceDo) Join(table schema.Tabler, on ...field.Expr) IProfServiceDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p profServiceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProfServiceDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p profServiceDo) RightJoin(table schema.Tabler, on ...field.Expr) IProfServiceDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p profServiceDo) Group(cols ...field.Expr) IProfServiceDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p profServiceDo) Having(conds ...gen.Condition) IProfServiceDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p profServiceDo) Limit(limit int) IProfServiceDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p profServiceDo) Offset(offset int) IProfServiceDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p profServiceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProfServiceDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p profServiceDo) Unscoped() IProfServiceDo {
	return p.withDO(p.DO.Unscoped())
}

func (p profServiceDo) Create(values ...*model.ProfService) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p profServiceDo) CreateInBatches(values []*model.ProfService, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p profServiceDo) Save(values ...*model.ProfService) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p profServiceDo) First() (*model.ProfService, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfService), nil
	}
}

func (p profServiceDo) Take() (*model.ProfService, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfService), nil
	}
}

func (p profServiceDo) Last() (*model.ProfService, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfService), nil
	}
}

func (p profServiceDo) Find() ([]*model.ProfService, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProfService), err
}

func (p profServiceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProfService, err error) {
	buf := make([]*model.ProfService, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p profServiceDo) FindInBatches(result *[]*model.ProfService, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p profServiceDo) Attrs(attrs ...field.AssignExpr) IProfServiceDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p profServiceDo) Assign(attrs ...field.AssignExpr) IProfServiceDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p profServiceDo) Joins(fields ...field.RelationField) IProfServiceDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p profServiceDo) Preload(fields ...field.RelationField) IProfServiceDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p profServiceDo) FirstOrInit() (*model.ProfService, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfService), nil
	}
}

func (p profServiceDo) FirstOrCreate() (*model.ProfService, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfService), nil
	}
}

func (p profServiceDo) FindByPage(offset int, limit int) (result []*model.ProfService, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p profServiceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p profServiceDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p profServiceDo) Delete(models ...*model.ProfService) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *profServiceDo) withDO(do gen.Dao) *profServiceDo {
	p.DO = *do.(*gen.DO)
	return p
}
