// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newProfServiceInvite(db *gorm.DB, opts ...gen.DOOption) profServiceInvite {
	_profServiceInvite := profServiceInvite{}

	_profServiceInvite.profServiceInviteDo.UseDB(db, opts...)
	_profServiceInvite.profServiceInviteDo.UseModel(&model.ProfServiceInvite{})

	tableName := _profServiceInvite.profServiceInviteDo.TableName()
	_profServiceInvite.ALL = field.NewAsterisk(tableName)
	_profServiceInvite.ID = field.NewUint32(tableName, "id")
	_profServiceInvite.UserID = field.NewUint32(tableName, "user_id")
	_profServiceInvite.WantedID = field.NewUint32(tableName, "wanted_id")
	_profServiceInvite.Company = field.NewString(tableName, "company")
	_profServiceInvite.Name = field.NewString(tableName, "name")
	_profServiceInvite.Position = field.NewString(tableName, "position")
	_profServiceInvite.Phone = field.NewString(tableName, "phone")
	_profServiceInvite.WechatID = field.NewString(tableName, "wechat_id")
	_profServiceInvite.Message = field.NewString(tableName, "message")
	_profServiceInvite.TimeInsert = field.NewUint32(tableName, "time_insert")
	_profServiceInvite.TimeUpdate = field.NewUint32(tableName, "time_update")
	_profServiceInvite.Status = field.NewInt32(tableName, "status")

	_profServiceInvite.fillFieldMap()

	return _profServiceInvite
}

type profServiceInvite struct {
	profServiceInviteDo

	ALL        field.Asterisk
	ID         field.Uint32
	UserID     field.Uint32
	WantedID   field.Uint32
	Company    field.String
	Name       field.String
	Position   field.String
	Phone      field.String
	WechatID   field.String // 微信号
	Message    field.String // 备注
	TimeInsert field.Uint32
	TimeUpdate field.Uint32
	Status     field.Int32

	fieldMap map[string]field.Expr
}

func (p profServiceInvite) Table(newTableName string) *profServiceInvite {
	p.profServiceInviteDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p profServiceInvite) As(alias string) *profServiceInvite {
	p.profServiceInviteDo.DO = *(p.profServiceInviteDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *profServiceInvite) updateTableName(table string) *profServiceInvite {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint32(table, "id")
	p.UserID = field.NewUint32(table, "user_id")
	p.WantedID = field.NewUint32(table, "wanted_id")
	p.Company = field.NewString(table, "company")
	p.Name = field.NewString(table, "name")
	p.Position = field.NewString(table, "position")
	p.Phone = field.NewString(table, "phone")
	p.WechatID = field.NewString(table, "wechat_id")
	p.Message = field.NewString(table, "message")
	p.TimeInsert = field.NewUint32(table, "time_insert")
	p.TimeUpdate = field.NewUint32(table, "time_update")
	p.Status = field.NewInt32(table, "status")

	p.fillFieldMap()

	return p
}

func (p *profServiceInvite) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *profServiceInvite) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 12)
	p.fieldMap["id"] = p.ID
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["wanted_id"] = p.WantedID
	p.fieldMap["company"] = p.Company
	p.fieldMap["name"] = p.Name
	p.fieldMap["position"] = p.Position
	p.fieldMap["phone"] = p.Phone
	p.fieldMap["wechat_id"] = p.WechatID
	p.fieldMap["message"] = p.Message
	p.fieldMap["time_insert"] = p.TimeInsert
	p.fieldMap["time_update"] = p.TimeUpdate
	p.fieldMap["status"] = p.Status
}

func (p profServiceInvite) clone(db *gorm.DB) profServiceInvite {
	p.profServiceInviteDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p profServiceInvite) replaceDB(db *gorm.DB) profServiceInvite {
	p.profServiceInviteDo.ReplaceDB(db)
	return p
}

type profServiceInviteDo struct{ gen.DO }

type IProfServiceInviteDo interface {
	gen.SubQuery
	Debug() IProfServiceInviteDo
	WithContext(ctx context.Context) IProfServiceInviteDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProfServiceInviteDo
	WriteDB() IProfServiceInviteDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProfServiceInviteDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProfServiceInviteDo
	Not(conds ...gen.Condition) IProfServiceInviteDo
	Or(conds ...gen.Condition) IProfServiceInviteDo
	Select(conds ...field.Expr) IProfServiceInviteDo
	Where(conds ...gen.Condition) IProfServiceInviteDo
	Order(conds ...field.Expr) IProfServiceInviteDo
	Distinct(cols ...field.Expr) IProfServiceInviteDo
	Omit(cols ...field.Expr) IProfServiceInviteDo
	Join(table schema.Tabler, on ...field.Expr) IProfServiceInviteDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProfServiceInviteDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProfServiceInviteDo
	Group(cols ...field.Expr) IProfServiceInviteDo
	Having(conds ...gen.Condition) IProfServiceInviteDo
	Limit(limit int) IProfServiceInviteDo
	Offset(offset int) IProfServiceInviteDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProfServiceInviteDo
	Unscoped() IProfServiceInviteDo
	Create(values ...*model.ProfServiceInvite) error
	CreateInBatches(values []*model.ProfServiceInvite, batchSize int) error
	Save(values ...*model.ProfServiceInvite) error
	First() (*model.ProfServiceInvite, error)
	Take() (*model.ProfServiceInvite, error)
	Last() (*model.ProfServiceInvite, error)
	Find() ([]*model.ProfServiceInvite, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProfServiceInvite, err error)
	FindInBatches(result *[]*model.ProfServiceInvite, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ProfServiceInvite) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProfServiceInviteDo
	Assign(attrs ...field.AssignExpr) IProfServiceInviteDo
	Joins(fields ...field.RelationField) IProfServiceInviteDo
	Preload(fields ...field.RelationField) IProfServiceInviteDo
	FirstOrInit() (*model.ProfServiceInvite, error)
	FirstOrCreate() (*model.ProfServiceInvite, error)
	FindByPage(offset int, limit int) (result []*model.ProfServiceInvite, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProfServiceInviteDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p profServiceInviteDo) Debug() IProfServiceInviteDo {
	return p.withDO(p.DO.Debug())
}

func (p profServiceInviteDo) WithContext(ctx context.Context) IProfServiceInviteDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p profServiceInviteDo) ReadDB() IProfServiceInviteDo {
	return p.Clauses(dbresolver.Read)
}

func (p profServiceInviteDo) WriteDB() IProfServiceInviteDo {
	return p.Clauses(dbresolver.Write)
}

func (p profServiceInviteDo) Session(config *gorm.Session) IProfServiceInviteDo {
	return p.withDO(p.DO.Session(config))
}

func (p profServiceInviteDo) Clauses(conds ...clause.Expression) IProfServiceInviteDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p profServiceInviteDo) Returning(value interface{}, columns ...string) IProfServiceInviteDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p profServiceInviteDo) Not(conds ...gen.Condition) IProfServiceInviteDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p profServiceInviteDo) Or(conds ...gen.Condition) IProfServiceInviteDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p profServiceInviteDo) Select(conds ...field.Expr) IProfServiceInviteDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p profServiceInviteDo) Where(conds ...gen.Condition) IProfServiceInviteDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p profServiceInviteDo) Order(conds ...field.Expr) IProfServiceInviteDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p profServiceInviteDo) Distinct(cols ...field.Expr) IProfServiceInviteDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p profServiceInviteDo) Omit(cols ...field.Expr) IProfServiceInviteDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p profServiceInviteDo) Join(table schema.Tabler, on ...field.Expr) IProfServiceInviteDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p profServiceInviteDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProfServiceInviteDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p profServiceInviteDo) RightJoin(table schema.Tabler, on ...field.Expr) IProfServiceInviteDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p profServiceInviteDo) Group(cols ...field.Expr) IProfServiceInviteDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p profServiceInviteDo) Having(conds ...gen.Condition) IProfServiceInviteDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p profServiceInviteDo) Limit(limit int) IProfServiceInviteDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p profServiceInviteDo) Offset(offset int) IProfServiceInviteDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p profServiceInviteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProfServiceInviteDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p profServiceInviteDo) Unscoped() IProfServiceInviteDo {
	return p.withDO(p.DO.Unscoped())
}

func (p profServiceInviteDo) Create(values ...*model.ProfServiceInvite) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p profServiceInviteDo) CreateInBatches(values []*model.ProfServiceInvite, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p profServiceInviteDo) Save(values ...*model.ProfServiceInvite) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p profServiceInviteDo) First() (*model.ProfServiceInvite, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfServiceInvite), nil
	}
}

func (p profServiceInviteDo) Take() (*model.ProfServiceInvite, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfServiceInvite), nil
	}
}

func (p profServiceInviteDo) Last() (*model.ProfServiceInvite, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfServiceInvite), nil
	}
}

func (p profServiceInviteDo) Find() ([]*model.ProfServiceInvite, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProfServiceInvite), err
}

func (p profServiceInviteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProfServiceInvite, err error) {
	buf := make([]*model.ProfServiceInvite, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p profServiceInviteDo) FindInBatches(result *[]*model.ProfServiceInvite, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p profServiceInviteDo) Attrs(attrs ...field.AssignExpr) IProfServiceInviteDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p profServiceInviteDo) Assign(attrs ...field.AssignExpr) IProfServiceInviteDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p profServiceInviteDo) Joins(fields ...field.RelationField) IProfServiceInviteDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p profServiceInviteDo) Preload(fields ...field.RelationField) IProfServiceInviteDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p profServiceInviteDo) FirstOrInit() (*model.ProfServiceInvite, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfServiceInvite), nil
	}
}

func (p profServiceInviteDo) FirstOrCreate() (*model.ProfServiceInvite, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProfServiceInvite), nil
	}
}

func (p profServiceInviteDo) FindByPage(offset int, limit int) (result []*model.ProfServiceInvite, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p profServiceInviteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p profServiceInviteDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p profServiceInviteDo) Delete(models ...*model.ProfServiceInvite) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *profServiceInviteDo) withDO(do gen.Dao) *profServiceInviteDo {
	p.DO = *do.(*gen.DO)
	return p
}
