// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newResumeVisitHistory(db *gorm.DB, opts ...gen.DOOption) resumeVisitHistory {
	_resumeVisitHistory := resumeVisitHistory{}

	_resumeVisitHistory.resumeVisitHistoryDo.UseDB(db, opts...)
	_resumeVisitHistory.resumeVisitHistoryDo.UseModel(&model.ResumeVisitHistory{})

	tableName := _resumeVisitHistory.resumeVisitHistoryDo.TableName()
	_resumeVisitHistory.ALL = field.NewAsterisk(tableName)
	_resumeVisitHistory.ID = field.NewInt32(tableName, "id")
	_resumeVisitHistory.ResumeID = field.NewInt32(tableName, "resume_id")
	_resumeVisitHistory.AdminID = field.NewInt32(tableName, "admin_id")
	_resumeVisitHistory.Content = field.NewString(tableName, "content")
	_resumeVisitHistory.TimeInsert = field.NewInt32(tableName, "time_insert")
	_resumeVisitHistory.TimeUpdate = field.NewInt32(tableName, "time_update")
	_resumeVisitHistory.Status = field.NewInt32(tableName, "status")

	_resumeVisitHistory.fillFieldMap()

	return _resumeVisitHistory
}

// resumeVisitHistory 简历寻访表
type resumeVisitHistory struct {
	resumeVisitHistoryDo

	ALL        field.Asterisk
	ID         field.Int32
	ResumeID   field.Int32  // 简历Id
	AdminID    field.Int32  // 管理者Id
	Content    field.String // 寻访记录
	TimeInsert field.Int32  // 添加时间
	TimeUpdate field.Int32  // 编辑时间
	Status     field.Int32  // 0-删除，1-暂不使用，2-正常

	fieldMap map[string]field.Expr
}

func (r resumeVisitHistory) Table(newTableName string) *resumeVisitHistory {
	r.resumeVisitHistoryDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resumeVisitHistory) As(alias string) *resumeVisitHistory {
	r.resumeVisitHistoryDo.DO = *(r.resumeVisitHistoryDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resumeVisitHistory) updateTableName(table string) *resumeVisitHistory {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.ResumeID = field.NewInt32(table, "resume_id")
	r.AdminID = field.NewInt32(table, "admin_id")
	r.Content = field.NewString(table, "content")
	r.TimeInsert = field.NewInt32(table, "time_insert")
	r.TimeUpdate = field.NewInt32(table, "time_update")
	r.Status = field.NewInt32(table, "status")

	r.fillFieldMap()

	return r
}

func (r *resumeVisitHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resumeVisitHistory) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["id"] = r.ID
	r.fieldMap["resume_id"] = r.ResumeID
	r.fieldMap["admin_id"] = r.AdminID
	r.fieldMap["content"] = r.Content
	r.fieldMap["time_insert"] = r.TimeInsert
	r.fieldMap["time_update"] = r.TimeUpdate
	r.fieldMap["status"] = r.Status
}

func (r resumeVisitHistory) clone(db *gorm.DB) resumeVisitHistory {
	r.resumeVisitHistoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resumeVisitHistory) replaceDB(db *gorm.DB) resumeVisitHistory {
	r.resumeVisitHistoryDo.ReplaceDB(db)
	return r
}

type resumeVisitHistoryDo struct{ gen.DO }

type IResumeVisitHistoryDo interface {
	gen.SubQuery
	Debug() IResumeVisitHistoryDo
	WithContext(ctx context.Context) IResumeVisitHistoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IResumeVisitHistoryDo
	WriteDB() IResumeVisitHistoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IResumeVisitHistoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IResumeVisitHistoryDo
	Not(conds ...gen.Condition) IResumeVisitHistoryDo
	Or(conds ...gen.Condition) IResumeVisitHistoryDo
	Select(conds ...field.Expr) IResumeVisitHistoryDo
	Where(conds ...gen.Condition) IResumeVisitHistoryDo
	Order(conds ...field.Expr) IResumeVisitHistoryDo
	Distinct(cols ...field.Expr) IResumeVisitHistoryDo
	Omit(cols ...field.Expr) IResumeVisitHistoryDo
	Join(table schema.Tabler, on ...field.Expr) IResumeVisitHistoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IResumeVisitHistoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IResumeVisitHistoryDo
	Group(cols ...field.Expr) IResumeVisitHistoryDo
	Having(conds ...gen.Condition) IResumeVisitHistoryDo
	Limit(limit int) IResumeVisitHistoryDo
	Offset(offset int) IResumeVisitHistoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IResumeVisitHistoryDo
	Unscoped() IResumeVisitHistoryDo
	Create(values ...*model.ResumeVisitHistory) error
	CreateInBatches(values []*model.ResumeVisitHistory, batchSize int) error
	Save(values ...*model.ResumeVisitHistory) error
	First() (*model.ResumeVisitHistory, error)
	Take() (*model.ResumeVisitHistory, error)
	Last() (*model.ResumeVisitHistory, error)
	Find() ([]*model.ResumeVisitHistory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResumeVisitHistory, err error)
	FindInBatches(result *[]*model.ResumeVisitHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ResumeVisitHistory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IResumeVisitHistoryDo
	Assign(attrs ...field.AssignExpr) IResumeVisitHistoryDo
	Joins(fields ...field.RelationField) IResumeVisitHistoryDo
	Preload(fields ...field.RelationField) IResumeVisitHistoryDo
	FirstOrInit() (*model.ResumeVisitHistory, error)
	FirstOrCreate() (*model.ResumeVisitHistory, error)
	FindByPage(offset int, limit int) (result []*model.ResumeVisitHistory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IResumeVisitHistoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r resumeVisitHistoryDo) Debug() IResumeVisitHistoryDo {
	return r.withDO(r.DO.Debug())
}

func (r resumeVisitHistoryDo) WithContext(ctx context.Context) IResumeVisitHistoryDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resumeVisitHistoryDo) ReadDB() IResumeVisitHistoryDo {
	return r.Clauses(dbresolver.Read)
}

func (r resumeVisitHistoryDo) WriteDB() IResumeVisitHistoryDo {
	return r.Clauses(dbresolver.Write)
}

func (r resumeVisitHistoryDo) Session(config *gorm.Session) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Session(config))
}

func (r resumeVisitHistoryDo) Clauses(conds ...clause.Expression) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resumeVisitHistoryDo) Returning(value interface{}, columns ...string) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resumeVisitHistoryDo) Not(conds ...gen.Condition) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resumeVisitHistoryDo) Or(conds ...gen.Condition) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resumeVisitHistoryDo) Select(conds ...field.Expr) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resumeVisitHistoryDo) Where(conds ...gen.Condition) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resumeVisitHistoryDo) Order(conds ...field.Expr) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resumeVisitHistoryDo) Distinct(cols ...field.Expr) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resumeVisitHistoryDo) Omit(cols ...field.Expr) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resumeVisitHistoryDo) Join(table schema.Tabler, on ...field.Expr) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resumeVisitHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IResumeVisitHistoryDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resumeVisitHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IResumeVisitHistoryDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resumeVisitHistoryDo) Group(cols ...field.Expr) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resumeVisitHistoryDo) Having(conds ...gen.Condition) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resumeVisitHistoryDo) Limit(limit int) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resumeVisitHistoryDo) Offset(offset int) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resumeVisitHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resumeVisitHistoryDo) Unscoped() IResumeVisitHistoryDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resumeVisitHistoryDo) Create(values ...*model.ResumeVisitHistory) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resumeVisitHistoryDo) CreateInBatches(values []*model.ResumeVisitHistory, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resumeVisitHistoryDo) Save(values ...*model.ResumeVisitHistory) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resumeVisitHistoryDo) First() (*model.ResumeVisitHistory, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumeVisitHistory), nil
	}
}

func (r resumeVisitHistoryDo) Take() (*model.ResumeVisitHistory, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumeVisitHistory), nil
	}
}

func (r resumeVisitHistoryDo) Last() (*model.ResumeVisitHistory, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumeVisitHistory), nil
	}
}

func (r resumeVisitHistoryDo) Find() ([]*model.ResumeVisitHistory, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResumeVisitHistory), err
}

func (r resumeVisitHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResumeVisitHistory, err error) {
	buf := make([]*model.ResumeVisitHistory, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resumeVisitHistoryDo) FindInBatches(result *[]*model.ResumeVisitHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resumeVisitHistoryDo) Attrs(attrs ...field.AssignExpr) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resumeVisitHistoryDo) Assign(attrs ...field.AssignExpr) IResumeVisitHistoryDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resumeVisitHistoryDo) Joins(fields ...field.RelationField) IResumeVisitHistoryDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resumeVisitHistoryDo) Preload(fields ...field.RelationField) IResumeVisitHistoryDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resumeVisitHistoryDo) FirstOrInit() (*model.ResumeVisitHistory, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumeVisitHistory), nil
	}
}

func (r resumeVisitHistoryDo) FirstOrCreate() (*model.ResumeVisitHistory, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumeVisitHistory), nil
	}
}

func (r resumeVisitHistoryDo) FindByPage(offset int, limit int) (result []*model.ResumeVisitHistory, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resumeVisitHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resumeVisitHistoryDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resumeVisitHistoryDo) Delete(models ...*model.ResumeVisitHistory) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resumeVisitHistoryDo) withDO(do gen.Dao) *resumeVisitHistoryDo {
	r.DO = *do.(*gen.DO)
	return r
}
