// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newResumeRemind(db *gorm.DB, opts ...gen.DOOption) resumeRemind {
	_resumeRemind := resumeRemind{}

	_resumeRemind.resumeRemindDo.UseDB(db, opts...)
	_resumeRemind.resumeRemindDo.UseModel(&model.ResumeRemind{})

	tableName := _resumeRemind.resumeRemindDo.TableName()
	_resumeRemind.ALL = field.NewAsterisk(tableName)
	_resumeRemind.ID = field.NewInt32(tableName, "id")
	_resumeRemind.AdminID = field.NewInt32(tableName, "admin_id")
	_resumeRemind.ResumeID = field.NewInt32(tableName, "resume_id")
	_resumeRemind.RemindTime = field.NewString(tableName, "remind_time")
	_resumeRemind.AddTime = field.NewInt32(tableName, "add_time")

	_resumeRemind.fillFieldMap()

	return _resumeRemind
}

type resumeRemind struct {
	resumeRemindDo

	ALL        field.Asterisk
	ID         field.Int32
	AdminID    field.Int32  // 管理员ID
	ResumeID   field.Int32  // 简历ID
	RemindTime field.String // yymmdd
	AddTime    field.Int32  // 添加时间

	fieldMap map[string]field.Expr
}

func (r resumeRemind) Table(newTableName string) *resumeRemind {
	r.resumeRemindDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resumeRemind) As(alias string) *resumeRemind {
	r.resumeRemindDo.DO = *(r.resumeRemindDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resumeRemind) updateTableName(table string) *resumeRemind {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.AdminID = field.NewInt32(table, "admin_id")
	r.ResumeID = field.NewInt32(table, "resume_id")
	r.RemindTime = field.NewString(table, "remind_time")
	r.AddTime = field.NewInt32(table, "add_time")

	r.fillFieldMap()

	return r
}

func (r *resumeRemind) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resumeRemind) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 5)
	r.fieldMap["id"] = r.ID
	r.fieldMap["admin_id"] = r.AdminID
	r.fieldMap["resume_id"] = r.ResumeID
	r.fieldMap["remind_time"] = r.RemindTime
	r.fieldMap["add_time"] = r.AddTime
}

func (r resumeRemind) clone(db *gorm.DB) resumeRemind {
	r.resumeRemindDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resumeRemind) replaceDB(db *gorm.DB) resumeRemind {
	r.resumeRemindDo.ReplaceDB(db)
	return r
}

type resumeRemindDo struct{ gen.DO }

type IResumeRemindDo interface {
	gen.SubQuery
	Debug() IResumeRemindDo
	WithContext(ctx context.Context) IResumeRemindDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IResumeRemindDo
	WriteDB() IResumeRemindDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IResumeRemindDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IResumeRemindDo
	Not(conds ...gen.Condition) IResumeRemindDo
	Or(conds ...gen.Condition) IResumeRemindDo
	Select(conds ...field.Expr) IResumeRemindDo
	Where(conds ...gen.Condition) IResumeRemindDo
	Order(conds ...field.Expr) IResumeRemindDo
	Distinct(cols ...field.Expr) IResumeRemindDo
	Omit(cols ...field.Expr) IResumeRemindDo
	Join(table schema.Tabler, on ...field.Expr) IResumeRemindDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IResumeRemindDo
	RightJoin(table schema.Tabler, on ...field.Expr) IResumeRemindDo
	Group(cols ...field.Expr) IResumeRemindDo
	Having(conds ...gen.Condition) IResumeRemindDo
	Limit(limit int) IResumeRemindDo
	Offset(offset int) IResumeRemindDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IResumeRemindDo
	Unscoped() IResumeRemindDo
	Create(values ...*model.ResumeRemind) error
	CreateInBatches(values []*model.ResumeRemind, batchSize int) error
	Save(values ...*model.ResumeRemind) error
	First() (*model.ResumeRemind, error)
	Take() (*model.ResumeRemind, error)
	Last() (*model.ResumeRemind, error)
	Find() ([]*model.ResumeRemind, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResumeRemind, err error)
	FindInBatches(result *[]*model.ResumeRemind, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ResumeRemind) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IResumeRemindDo
	Assign(attrs ...field.AssignExpr) IResumeRemindDo
	Joins(fields ...field.RelationField) IResumeRemindDo
	Preload(fields ...field.RelationField) IResumeRemindDo
	FirstOrInit() (*model.ResumeRemind, error)
	FirstOrCreate() (*model.ResumeRemind, error)
	FindByPage(offset int, limit int) (result []*model.ResumeRemind, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IResumeRemindDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r resumeRemindDo) Debug() IResumeRemindDo {
	return r.withDO(r.DO.Debug())
}

func (r resumeRemindDo) WithContext(ctx context.Context) IResumeRemindDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resumeRemindDo) ReadDB() IResumeRemindDo {
	return r.Clauses(dbresolver.Read)
}

func (r resumeRemindDo) WriteDB() IResumeRemindDo {
	return r.Clauses(dbresolver.Write)
}

func (r resumeRemindDo) Session(config *gorm.Session) IResumeRemindDo {
	return r.withDO(r.DO.Session(config))
}

func (r resumeRemindDo) Clauses(conds ...clause.Expression) IResumeRemindDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resumeRemindDo) Returning(value interface{}, columns ...string) IResumeRemindDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resumeRemindDo) Not(conds ...gen.Condition) IResumeRemindDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resumeRemindDo) Or(conds ...gen.Condition) IResumeRemindDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resumeRemindDo) Select(conds ...field.Expr) IResumeRemindDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resumeRemindDo) Where(conds ...gen.Condition) IResumeRemindDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resumeRemindDo) Order(conds ...field.Expr) IResumeRemindDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resumeRemindDo) Distinct(cols ...field.Expr) IResumeRemindDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resumeRemindDo) Omit(cols ...field.Expr) IResumeRemindDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resumeRemindDo) Join(table schema.Tabler, on ...field.Expr) IResumeRemindDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resumeRemindDo) LeftJoin(table schema.Tabler, on ...field.Expr) IResumeRemindDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resumeRemindDo) RightJoin(table schema.Tabler, on ...field.Expr) IResumeRemindDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resumeRemindDo) Group(cols ...field.Expr) IResumeRemindDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resumeRemindDo) Having(conds ...gen.Condition) IResumeRemindDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resumeRemindDo) Limit(limit int) IResumeRemindDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resumeRemindDo) Offset(offset int) IResumeRemindDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resumeRemindDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IResumeRemindDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resumeRemindDo) Unscoped() IResumeRemindDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resumeRemindDo) Create(values ...*model.ResumeRemind) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resumeRemindDo) CreateInBatches(values []*model.ResumeRemind, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resumeRemindDo) Save(values ...*model.ResumeRemind) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resumeRemindDo) First() (*model.ResumeRemind, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumeRemind), nil
	}
}

func (r resumeRemindDo) Take() (*model.ResumeRemind, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumeRemind), nil
	}
}

func (r resumeRemindDo) Last() (*model.ResumeRemind, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumeRemind), nil
	}
}

func (r resumeRemindDo) Find() ([]*model.ResumeRemind, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResumeRemind), err
}

func (r resumeRemindDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResumeRemind, err error) {
	buf := make([]*model.ResumeRemind, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resumeRemindDo) FindInBatches(result *[]*model.ResumeRemind, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resumeRemindDo) Attrs(attrs ...field.AssignExpr) IResumeRemindDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resumeRemindDo) Assign(attrs ...field.AssignExpr) IResumeRemindDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resumeRemindDo) Joins(fields ...field.RelationField) IResumeRemindDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resumeRemindDo) Preload(fields ...field.RelationField) IResumeRemindDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resumeRemindDo) FirstOrInit() (*model.ResumeRemind, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumeRemind), nil
	}
}

func (r resumeRemindDo) FirstOrCreate() (*model.ResumeRemind, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResumeRemind), nil
	}
}

func (r resumeRemindDo) FindByPage(offset int, limit int) (result []*model.ResumeRemind, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resumeRemindDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resumeRemindDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resumeRemindDo) Delete(models ...*model.ResumeRemind) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resumeRemindDo) withDO(do gen.Dao) *resumeRemindDo {
	r.DO = *do.(*gen.DO)
	return r
}
