// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newResume(db *gorm.DB, opts ...gen.DOOption) resume {
	_resume := resume{}

	_resume.resumeDo.UseDB(db, opts...)
	_resume.resumeDo.UseModel(&model.Resume{})

	tableName := _resume.resumeDo.TableName()
	_resume.ALL = field.NewAsterisk(tableName)
	_resume.ID = field.NewInt32(tableName, "id")
	_resume.UserID = field.NewInt32(tableName, "user_id")
	_resume.AdminID = field.NewInt32(tableName, "admin_id")
	_resume.CompanyID = field.NewInt32(tableName, "company_id")
	_resume.Gender = field.NewString(tableName, "gender")
	_resume.Name = field.NewString(tableName, "name")
	_resume.Mobile = field.NewString(tableName, "mobile")
	_resume.Email = field.NewString(tableName, "email")
	_resume.CityID = field.NewInt32(tableName, "city_id")
	_resume.RecentCompany = field.NewString(tableName, "recent_company")
	_resume.Position = field.NewString(tableName, "position")
	_resume.BirthYear = field.NewString(tableName, "birth_year")
	_resume.University = field.NewString(tableName, "university")
	_resume.Major = field.NewString(tableName, "major")
	_resume.EducationID = field.NewInt32(tableName, "education_id")
	_resume.Source = field.NewString(tableName, "source")
	_resume.OriginText = field.NewString(tableName, "origin_text")
	_resume.FilePath = field.NewString(tableName, "file_path")
	_resume.TimeInsert = field.NewInt32(tableName, "time_insert")
	_resume.TimeUpdate = field.NewInt32(tableName, "time_update")
	_resume.Status = field.NewInt32(tableName, "status")
	_resume.Tags = field.NewString(tableName, "tags")
	_resume.LastOp = field.NewString(tableName, "last_op")

	_resume.fillFieldMap()

	return _resume
}

// resume 简历表
type resume struct {
	resumeDo

	ALL           field.Asterisk
	ID            field.Int32
	UserID        field.Int32  // 前台用户Id
	AdminID       field.Int32  // 后台上传者Id
	CompanyID     field.Int32  // 公司Id
	Gender        field.String // 性别
	Name          field.String // 姓名
	Mobile        field.String // 手机
	Email         field.String // 邮箱
	CityID        field.Int32  // 城市
	RecentCompany field.String // 最近公司
	Position      field.String // 职位
	BirthYear     field.String // 出生年份
	University    field.String // 毕业院校
	Major         field.String // 专业
	EducationID   field.Int32  // 学历
	Source        field.String // 简历来源
	OriginText    field.String // 简历原文
	FilePath      field.String // 简历文件位置
	TimeInsert    field.Int32  // 添加时间
	TimeUpdate    field.Int32  // 编辑时间
	Status        field.Int32  // 0-删除，1-暂不使用，2-正常
	Tags          field.String // 标签
	LastOp        field.String // 更新人

	fieldMap map[string]field.Expr
}

func (r resume) Table(newTableName string) *resume {
	r.resumeDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resume) As(alias string) *resume {
	r.resumeDo.DO = *(r.resumeDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resume) updateTableName(table string) *resume {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.UserID = field.NewInt32(table, "user_id")
	r.AdminID = field.NewInt32(table, "admin_id")
	r.CompanyID = field.NewInt32(table, "company_id")
	r.Gender = field.NewString(table, "gender")
	r.Name = field.NewString(table, "name")
	r.Mobile = field.NewString(table, "mobile")
	r.Email = field.NewString(table, "email")
	r.CityID = field.NewInt32(table, "city_id")
	r.RecentCompany = field.NewString(table, "recent_company")
	r.Position = field.NewString(table, "position")
	r.BirthYear = field.NewString(table, "birth_year")
	r.University = field.NewString(table, "university")
	r.Major = field.NewString(table, "major")
	r.EducationID = field.NewInt32(table, "education_id")
	r.Source = field.NewString(table, "source")
	r.OriginText = field.NewString(table, "origin_text")
	r.FilePath = field.NewString(table, "file_path")
	r.TimeInsert = field.NewInt32(table, "time_insert")
	r.TimeUpdate = field.NewInt32(table, "time_update")
	r.Status = field.NewInt32(table, "status")
	r.Tags = field.NewString(table, "tags")
	r.LastOp = field.NewString(table, "last_op")

	r.fillFieldMap()

	return r
}

func (r *resume) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resume) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 23)
	r.fieldMap["id"] = r.ID
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["admin_id"] = r.AdminID
	r.fieldMap["company_id"] = r.CompanyID
	r.fieldMap["gender"] = r.Gender
	r.fieldMap["name"] = r.Name
	r.fieldMap["mobile"] = r.Mobile
	r.fieldMap["email"] = r.Email
	r.fieldMap["city_id"] = r.CityID
	r.fieldMap["recent_company"] = r.RecentCompany
	r.fieldMap["position"] = r.Position
	r.fieldMap["birth_year"] = r.BirthYear
	r.fieldMap["university"] = r.University
	r.fieldMap["major"] = r.Major
	r.fieldMap["education_id"] = r.EducationID
	r.fieldMap["source"] = r.Source
	r.fieldMap["origin_text"] = r.OriginText
	r.fieldMap["file_path"] = r.FilePath
	r.fieldMap["time_insert"] = r.TimeInsert
	r.fieldMap["time_update"] = r.TimeUpdate
	r.fieldMap["status"] = r.Status
	r.fieldMap["tags"] = r.Tags
	r.fieldMap["last_op"] = r.LastOp
}

func (r resume) clone(db *gorm.DB) resume {
	r.resumeDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resume) replaceDB(db *gorm.DB) resume {
	r.resumeDo.ReplaceDB(db)
	return r
}

type resumeDo struct{ gen.DO }

type IResumeDo interface {
	gen.SubQuery
	Debug() IResumeDo
	WithContext(ctx context.Context) IResumeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IResumeDo
	WriteDB() IResumeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IResumeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IResumeDo
	Not(conds ...gen.Condition) IResumeDo
	Or(conds ...gen.Condition) IResumeDo
	Select(conds ...field.Expr) IResumeDo
	Where(conds ...gen.Condition) IResumeDo
	Order(conds ...field.Expr) IResumeDo
	Distinct(cols ...field.Expr) IResumeDo
	Omit(cols ...field.Expr) IResumeDo
	Join(table schema.Tabler, on ...field.Expr) IResumeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IResumeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IResumeDo
	Group(cols ...field.Expr) IResumeDo
	Having(conds ...gen.Condition) IResumeDo
	Limit(limit int) IResumeDo
	Offset(offset int) IResumeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IResumeDo
	Unscoped() IResumeDo
	Create(values ...*model.Resume) error
	CreateInBatches(values []*model.Resume, batchSize int) error
	Save(values ...*model.Resume) error
	First() (*model.Resume, error)
	Take() (*model.Resume, error)
	Last() (*model.Resume, error)
	Find() ([]*model.Resume, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Resume, err error)
	FindInBatches(result *[]*model.Resume, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Resume) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IResumeDo
	Assign(attrs ...field.AssignExpr) IResumeDo
	Joins(fields ...field.RelationField) IResumeDo
	Preload(fields ...field.RelationField) IResumeDo
	FirstOrInit() (*model.Resume, error)
	FirstOrCreate() (*model.Resume, error)
	FindByPage(offset int, limit int) (result []*model.Resume, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IResumeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r resumeDo) Debug() IResumeDo {
	return r.withDO(r.DO.Debug())
}

func (r resumeDo) WithContext(ctx context.Context) IResumeDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resumeDo) ReadDB() IResumeDo {
	return r.Clauses(dbresolver.Read)
}

func (r resumeDo) WriteDB() IResumeDo {
	return r.Clauses(dbresolver.Write)
}

func (r resumeDo) Session(config *gorm.Session) IResumeDo {
	return r.withDO(r.DO.Session(config))
}

func (r resumeDo) Clauses(conds ...clause.Expression) IResumeDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resumeDo) Returning(value interface{}, columns ...string) IResumeDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resumeDo) Not(conds ...gen.Condition) IResumeDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resumeDo) Or(conds ...gen.Condition) IResumeDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resumeDo) Select(conds ...field.Expr) IResumeDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resumeDo) Where(conds ...gen.Condition) IResumeDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resumeDo) Order(conds ...field.Expr) IResumeDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resumeDo) Distinct(cols ...field.Expr) IResumeDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resumeDo) Omit(cols ...field.Expr) IResumeDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resumeDo) Join(table schema.Tabler, on ...field.Expr) IResumeDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resumeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IResumeDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resumeDo) RightJoin(table schema.Tabler, on ...field.Expr) IResumeDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resumeDo) Group(cols ...field.Expr) IResumeDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resumeDo) Having(conds ...gen.Condition) IResumeDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resumeDo) Limit(limit int) IResumeDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resumeDo) Offset(offset int) IResumeDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resumeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IResumeDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resumeDo) Unscoped() IResumeDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resumeDo) Create(values ...*model.Resume) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resumeDo) CreateInBatches(values []*model.Resume, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resumeDo) Save(values ...*model.Resume) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resumeDo) First() (*model.Resume, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resume), nil
	}
}

func (r resumeDo) Take() (*model.Resume, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resume), nil
	}
}

func (r resumeDo) Last() (*model.Resume, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resume), nil
	}
}

func (r resumeDo) Find() ([]*model.Resume, error) {
	result, err := r.DO.Find()
	return result.([]*model.Resume), err
}

func (r resumeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Resume, err error) {
	buf := make([]*model.Resume, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resumeDo) FindInBatches(result *[]*model.Resume, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resumeDo) Attrs(attrs ...field.AssignExpr) IResumeDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resumeDo) Assign(attrs ...field.AssignExpr) IResumeDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resumeDo) Joins(fields ...field.RelationField) IResumeDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resumeDo) Preload(fields ...field.RelationField) IResumeDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resumeDo) FirstOrInit() (*model.Resume, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resume), nil
	}
}

func (r resumeDo) FirstOrCreate() (*model.Resume, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Resume), nil
	}
}

func (r resumeDo) FindByPage(offset int, limit int) (result []*model.Resume, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resumeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resumeDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resumeDo) Delete(models ...*model.Resume) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resumeDo) withDO(do gen.Dao) *resumeDo {
	r.DO = *do.(*gen.DO)
	return r
}
