// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newTopicQa(db *gorm.DB, opts ...gen.DOOption) topicQa {
	_topicQa := topicQa{}

	_topicQa.topicQaDo.UseDB(db, opts...)
	_topicQa.topicQaDo.UseModel(&model.TopicQa{})

	tableName := _topicQa.topicQaDo.TableName()
	_topicQa.ALL = field.NewAsterisk(tableName)
	_topicQa.ID = field.NewInt32(tableName, "id")
	_topicQa.Type = field.NewString(tableName, "type")
	_topicQa.Title = field.NewString(tableName, "title")
	_topicQa.Digest = field.NewString(tableName, "digest")
	_topicQa.ImageURL = field.NewString(tableName, "image_url")
	_topicQa.TimeBegin = field.NewInt32(tableName, "time_begin")
	_topicQa.TimeEnd = field.NewInt32(tableName, "time_end")
	_topicQa.PeopleDemand = field.NewString(tableName, "people_demand")
	_topicQa.Cost = field.NewString(tableName, "cost")
	_topicQa.Address = field.NewString(tableName, "address")
	_topicQa.Content = field.NewString(tableName, "content")
	_topicQa.Requirement = field.NewString(tableName, "requirement")
	_topicQa.Attention = field.NewString(tableName, "attention")
	_topicQa.AdminID = field.NewInt32(tableName, "admin_id")
	_topicQa.CompanyID = field.NewInt32(tableName, "company_id")
	_topicQa.City = field.NewString(tableName, "city")
	_topicQa.MeetingCategory = field.NewString(tableName, "meeting_category")
	_topicQa.PositionTag = field.NewString(tableName, "position_tag")
	_topicQa.Experience = field.NewString(tableName, "experience")
	_topicQa.Salary = field.NewString(tableName, "salary")
	_topicQa.PassageIds = field.NewString(tableName, "passage_ids")
	_topicQa.AccountID = field.NewUint32(tableName, "account_id")
	_topicQa.SourceURL = field.NewString(tableName, "source_url")
	_topicQa.IsTop = field.NewInt32(tableName, "is_top")
	_topicQa.Pulisher = field.NewString(tableName, "pulisher")
	_topicQa.ViewCount = field.NewInt32(tableName, "view_count")
	_topicQa.LikeCount = field.NewUint32(tableName, "like_count")
	_topicQa.TimeInsert = field.NewInt32(tableName, "time_insert")
	_topicQa.TimeUpdate = field.NewInt32(tableName, "time_update")
	_topicQa.Status = field.NewInt32(tableName, "status")

	_topicQa.fillFieldMap()

	return _topicQa
}

type topicQa struct {
	topicQaDo

	ALL             field.Asterisk
	ID              field.Int32
	Type            field.String
	Title           field.String
	Digest          field.String
	ImageURL        field.String
	TimeBegin       field.Int32
	TimeEnd         field.Int32
	PeopleDemand    field.String
	Cost            field.String
	Address         field.String
	Content         field.String
	Requirement     field.String // 参与条件
	Attention       field.String // 注意事项
	AdminID         field.Int32
	CompanyID       field.Int32
	City            field.String
	MeetingCategory field.String
	PositionTag     field.String
	Experience      field.String
	Salary          field.String
	PassageIds      field.String // 关联的职位id列表
	AccountID       field.Uint32 // 文章account_id
	SourceURL       field.String // 原文地址
	IsTop           field.Int32  // 是否置顶
	Pulisher        field.String // 发布者
	ViewCount       field.Int32  // 阅读数量
	LikeCount       field.Uint32 // 点赞量
	TimeInsert      field.Int32
	TimeUpdate      field.Int32
	Status          field.Int32

	fieldMap map[string]field.Expr
}

func (t topicQa) Table(newTableName string) *topicQa {
	t.topicQaDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t topicQa) As(alias string) *topicQa {
	t.topicQaDo.DO = *(t.topicQaDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *topicQa) updateTableName(table string) *topicQa {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.Type = field.NewString(table, "type")
	t.Title = field.NewString(table, "title")
	t.Digest = field.NewString(table, "digest")
	t.ImageURL = field.NewString(table, "image_url")
	t.TimeBegin = field.NewInt32(table, "time_begin")
	t.TimeEnd = field.NewInt32(table, "time_end")
	t.PeopleDemand = field.NewString(table, "people_demand")
	t.Cost = field.NewString(table, "cost")
	t.Address = field.NewString(table, "address")
	t.Content = field.NewString(table, "content")
	t.Requirement = field.NewString(table, "requirement")
	t.Attention = field.NewString(table, "attention")
	t.AdminID = field.NewInt32(table, "admin_id")
	t.CompanyID = field.NewInt32(table, "company_id")
	t.City = field.NewString(table, "city")
	t.MeetingCategory = field.NewString(table, "meeting_category")
	t.PositionTag = field.NewString(table, "position_tag")
	t.Experience = field.NewString(table, "experience")
	t.Salary = field.NewString(table, "salary")
	t.PassageIds = field.NewString(table, "passage_ids")
	t.AccountID = field.NewUint32(table, "account_id")
	t.SourceURL = field.NewString(table, "source_url")
	t.IsTop = field.NewInt32(table, "is_top")
	t.Pulisher = field.NewString(table, "pulisher")
	t.ViewCount = field.NewInt32(table, "view_count")
	t.LikeCount = field.NewUint32(table, "like_count")
	t.TimeInsert = field.NewInt32(table, "time_insert")
	t.TimeUpdate = field.NewInt32(table, "time_update")
	t.Status = field.NewInt32(table, "status")

	t.fillFieldMap()

	return t
}

func (t *topicQa) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *topicQa) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 30)
	t.fieldMap["id"] = t.ID
	t.fieldMap["type"] = t.Type
	t.fieldMap["title"] = t.Title
	t.fieldMap["digest"] = t.Digest
	t.fieldMap["image_url"] = t.ImageURL
	t.fieldMap["time_begin"] = t.TimeBegin
	t.fieldMap["time_end"] = t.TimeEnd
	t.fieldMap["people_demand"] = t.PeopleDemand
	t.fieldMap["cost"] = t.Cost
	t.fieldMap["address"] = t.Address
	t.fieldMap["content"] = t.Content
	t.fieldMap["requirement"] = t.Requirement
	t.fieldMap["attention"] = t.Attention
	t.fieldMap["admin_id"] = t.AdminID
	t.fieldMap["company_id"] = t.CompanyID
	t.fieldMap["city"] = t.City
	t.fieldMap["meeting_category"] = t.MeetingCategory
	t.fieldMap["position_tag"] = t.PositionTag
	t.fieldMap["experience"] = t.Experience
	t.fieldMap["salary"] = t.Salary
	t.fieldMap["passage_ids"] = t.PassageIds
	t.fieldMap["account_id"] = t.AccountID
	t.fieldMap["source_url"] = t.SourceURL
	t.fieldMap["is_top"] = t.IsTop
	t.fieldMap["pulisher"] = t.Pulisher
	t.fieldMap["view_count"] = t.ViewCount
	t.fieldMap["like_count"] = t.LikeCount
	t.fieldMap["time_insert"] = t.TimeInsert
	t.fieldMap["time_update"] = t.TimeUpdate
	t.fieldMap["status"] = t.Status
}

func (t topicQa) clone(db *gorm.DB) topicQa {
	t.topicQaDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t topicQa) replaceDB(db *gorm.DB) topicQa {
	t.topicQaDo.ReplaceDB(db)
	return t
}

type topicQaDo struct{ gen.DO }

type ITopicQaDo interface {
	gen.SubQuery
	Debug() ITopicQaDo
	WithContext(ctx context.Context) ITopicQaDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITopicQaDo
	WriteDB() ITopicQaDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITopicQaDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITopicQaDo
	Not(conds ...gen.Condition) ITopicQaDo
	Or(conds ...gen.Condition) ITopicQaDo
	Select(conds ...field.Expr) ITopicQaDo
	Where(conds ...gen.Condition) ITopicQaDo
	Order(conds ...field.Expr) ITopicQaDo
	Distinct(cols ...field.Expr) ITopicQaDo
	Omit(cols ...field.Expr) ITopicQaDo
	Join(table schema.Tabler, on ...field.Expr) ITopicQaDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITopicQaDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITopicQaDo
	Group(cols ...field.Expr) ITopicQaDo
	Having(conds ...gen.Condition) ITopicQaDo
	Limit(limit int) ITopicQaDo
	Offset(offset int) ITopicQaDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITopicQaDo
	Unscoped() ITopicQaDo
	Create(values ...*model.TopicQa) error
	CreateInBatches(values []*model.TopicQa, batchSize int) error
	Save(values ...*model.TopicQa) error
	First() (*model.TopicQa, error)
	Take() (*model.TopicQa, error)
	Last() (*model.TopicQa, error)
	Find() ([]*model.TopicQa, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TopicQa, err error)
	FindInBatches(result *[]*model.TopicQa, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TopicQa) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITopicQaDo
	Assign(attrs ...field.AssignExpr) ITopicQaDo
	Joins(fields ...field.RelationField) ITopicQaDo
	Preload(fields ...field.RelationField) ITopicQaDo
	FirstOrInit() (*model.TopicQa, error)
	FirstOrCreate() (*model.TopicQa, error)
	FindByPage(offset int, limit int) (result []*model.TopicQa, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITopicQaDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t topicQaDo) Debug() ITopicQaDo {
	return t.withDO(t.DO.Debug())
}

func (t topicQaDo) WithContext(ctx context.Context) ITopicQaDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t topicQaDo) ReadDB() ITopicQaDo {
	return t.Clauses(dbresolver.Read)
}

func (t topicQaDo) WriteDB() ITopicQaDo {
	return t.Clauses(dbresolver.Write)
}

func (t topicQaDo) Session(config *gorm.Session) ITopicQaDo {
	return t.withDO(t.DO.Session(config))
}

func (t topicQaDo) Clauses(conds ...clause.Expression) ITopicQaDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t topicQaDo) Returning(value interface{}, columns ...string) ITopicQaDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t topicQaDo) Not(conds ...gen.Condition) ITopicQaDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t topicQaDo) Or(conds ...gen.Condition) ITopicQaDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t topicQaDo) Select(conds ...field.Expr) ITopicQaDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t topicQaDo) Where(conds ...gen.Condition) ITopicQaDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t topicQaDo) Order(conds ...field.Expr) ITopicQaDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t topicQaDo) Distinct(cols ...field.Expr) ITopicQaDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t topicQaDo) Omit(cols ...field.Expr) ITopicQaDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t topicQaDo) Join(table schema.Tabler, on ...field.Expr) ITopicQaDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t topicQaDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITopicQaDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t topicQaDo) RightJoin(table schema.Tabler, on ...field.Expr) ITopicQaDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t topicQaDo) Group(cols ...field.Expr) ITopicQaDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t topicQaDo) Having(conds ...gen.Condition) ITopicQaDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t topicQaDo) Limit(limit int) ITopicQaDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t topicQaDo) Offset(offset int) ITopicQaDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t topicQaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITopicQaDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t topicQaDo) Unscoped() ITopicQaDo {
	return t.withDO(t.DO.Unscoped())
}

func (t topicQaDo) Create(values ...*model.TopicQa) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t topicQaDo) CreateInBatches(values []*model.TopicQa, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t topicQaDo) Save(values ...*model.TopicQa) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t topicQaDo) First() (*model.TopicQa, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TopicQa), nil
	}
}

func (t topicQaDo) Take() (*model.TopicQa, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TopicQa), nil
	}
}

func (t topicQaDo) Last() (*model.TopicQa, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TopicQa), nil
	}
}

func (t topicQaDo) Find() ([]*model.TopicQa, error) {
	result, err := t.DO.Find()
	return result.([]*model.TopicQa), err
}

func (t topicQaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TopicQa, err error) {
	buf := make([]*model.TopicQa, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t topicQaDo) FindInBatches(result *[]*model.TopicQa, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t topicQaDo) Attrs(attrs ...field.AssignExpr) ITopicQaDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t topicQaDo) Assign(attrs ...field.AssignExpr) ITopicQaDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t topicQaDo) Joins(fields ...field.RelationField) ITopicQaDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t topicQaDo) Preload(fields ...field.RelationField) ITopicQaDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t topicQaDo) FirstOrInit() (*model.TopicQa, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TopicQa), nil
	}
}

func (t topicQaDo) FirstOrCreate() (*model.TopicQa, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TopicQa), nil
	}
}

func (t topicQaDo) FindByPage(offset int, limit int) (result []*model.TopicQa, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t topicQaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t topicQaDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t topicQaDo) Delete(models ...*model.TopicQa) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *topicQaDo) withDO(do gen.Dao) *topicQaDo {
	t.DO = *do.(*gen.DO)
	return t
}
