// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"app/internal/db/mysql/model"
)

func newUserCenter(db *gorm.DB, opts ...gen.DOOption) userCenter {
	_userCenter := userCenter{}

	_userCenter.userCenterDo.UseDB(db, opts...)
	_userCenter.userCenterDo.UseModel(&model.UserCenter{})

	tableName := _userCenter.userCenterDo.TableName()
	_userCenter.ALL = field.NewAsterisk(tableName)
	_userCenter.UserID = field.NewInt32(tableName, "user_id")
	_userCenter.PassageID = field.NewInt32(tableName, "passage_id")
	_userCenter.CountRelay = field.NewInt32(tableName, "count_relay")
	_userCenter.CountApply = field.NewInt32(tableName, "count_apply")
	_userCenter.CountSecondApply = field.NewInt32(tableName, "count_second_apply")

	_userCenter.fillFieldMap()

	return _userCenter
}

type userCenter struct {
	userCenterDo

	ALL              field.Asterisk
	UserID           field.Int32
	PassageID        field.Int32
	CountRelay       field.Int32
	CountApply       field.Int32
	CountSecondApply field.Int32

	fieldMap map[string]field.Expr
}

func (u userCenter) Table(newTableName string) *userCenter {
	u.userCenterDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userCenter) As(alias string) *userCenter {
	u.userCenterDo.DO = *(u.userCenterDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userCenter) updateTableName(table string) *userCenter {
	u.ALL = field.NewAsterisk(table)
	u.UserID = field.NewInt32(table, "user_id")
	u.PassageID = field.NewInt32(table, "passage_id")
	u.CountRelay = field.NewInt32(table, "count_relay")
	u.CountApply = field.NewInt32(table, "count_apply")
	u.CountSecondApply = field.NewInt32(table, "count_second_apply")

	u.fillFieldMap()

	return u
}

func (u *userCenter) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userCenter) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 5)
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["passage_id"] = u.PassageID
	u.fieldMap["count_relay"] = u.CountRelay
	u.fieldMap["count_apply"] = u.CountApply
	u.fieldMap["count_second_apply"] = u.CountSecondApply
}

func (u userCenter) clone(db *gorm.DB) userCenter {
	u.userCenterDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userCenter) replaceDB(db *gorm.DB) userCenter {
	u.userCenterDo.ReplaceDB(db)
	return u
}

type userCenterDo struct{ gen.DO }

type IUserCenterDo interface {
	gen.SubQuery
	Debug() IUserCenterDo
	WithContext(ctx context.Context) IUserCenterDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserCenterDo
	WriteDB() IUserCenterDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserCenterDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserCenterDo
	Not(conds ...gen.Condition) IUserCenterDo
	Or(conds ...gen.Condition) IUserCenterDo
	Select(conds ...field.Expr) IUserCenterDo
	Where(conds ...gen.Condition) IUserCenterDo
	Order(conds ...field.Expr) IUserCenterDo
	Distinct(cols ...field.Expr) IUserCenterDo
	Omit(cols ...field.Expr) IUserCenterDo
	Join(table schema.Tabler, on ...field.Expr) IUserCenterDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserCenterDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserCenterDo
	Group(cols ...field.Expr) IUserCenterDo
	Having(conds ...gen.Condition) IUserCenterDo
	Limit(limit int) IUserCenterDo
	Offset(offset int) IUserCenterDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserCenterDo
	Unscoped() IUserCenterDo
	Create(values ...*model.UserCenter) error
	CreateInBatches(values []*model.UserCenter, batchSize int) error
	Save(values ...*model.UserCenter) error
	First() (*model.UserCenter, error)
	Take() (*model.UserCenter, error)
	Last() (*model.UserCenter, error)
	Find() ([]*model.UserCenter, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserCenter, err error)
	FindInBatches(result *[]*model.UserCenter, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserCenter) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserCenterDo
	Assign(attrs ...field.AssignExpr) IUserCenterDo
	Joins(fields ...field.RelationField) IUserCenterDo
	Preload(fields ...field.RelationField) IUserCenterDo
	FirstOrInit() (*model.UserCenter, error)
	FirstOrCreate() (*model.UserCenter, error)
	FindByPage(offset int, limit int) (result []*model.UserCenter, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserCenterDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userCenterDo) Debug() IUserCenterDo {
	return u.withDO(u.DO.Debug())
}

func (u userCenterDo) WithContext(ctx context.Context) IUserCenterDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userCenterDo) ReadDB() IUserCenterDo {
	return u.Clauses(dbresolver.Read)
}

func (u userCenterDo) WriteDB() IUserCenterDo {
	return u.Clauses(dbresolver.Write)
}

func (u userCenterDo) Session(config *gorm.Session) IUserCenterDo {
	return u.withDO(u.DO.Session(config))
}

func (u userCenterDo) Clauses(conds ...clause.Expression) IUserCenterDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userCenterDo) Returning(value interface{}, columns ...string) IUserCenterDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userCenterDo) Not(conds ...gen.Condition) IUserCenterDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userCenterDo) Or(conds ...gen.Condition) IUserCenterDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userCenterDo) Select(conds ...field.Expr) IUserCenterDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userCenterDo) Where(conds ...gen.Condition) IUserCenterDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userCenterDo) Order(conds ...field.Expr) IUserCenterDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userCenterDo) Distinct(cols ...field.Expr) IUserCenterDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userCenterDo) Omit(cols ...field.Expr) IUserCenterDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userCenterDo) Join(table schema.Tabler, on ...field.Expr) IUserCenterDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userCenterDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserCenterDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userCenterDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserCenterDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userCenterDo) Group(cols ...field.Expr) IUserCenterDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userCenterDo) Having(conds ...gen.Condition) IUserCenterDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userCenterDo) Limit(limit int) IUserCenterDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userCenterDo) Offset(offset int) IUserCenterDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userCenterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserCenterDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userCenterDo) Unscoped() IUserCenterDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userCenterDo) Create(values ...*model.UserCenter) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userCenterDo) CreateInBatches(values []*model.UserCenter, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userCenterDo) Save(values ...*model.UserCenter) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userCenterDo) First() (*model.UserCenter, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCenter), nil
	}
}

func (u userCenterDo) Take() (*model.UserCenter, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCenter), nil
	}
}

func (u userCenterDo) Last() (*model.UserCenter, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCenter), nil
	}
}

func (u userCenterDo) Find() ([]*model.UserCenter, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserCenter), err
}

func (u userCenterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserCenter, err error) {
	buf := make([]*model.UserCenter, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userCenterDo) FindInBatches(result *[]*model.UserCenter, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userCenterDo) Attrs(attrs ...field.AssignExpr) IUserCenterDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userCenterDo) Assign(attrs ...field.AssignExpr) IUserCenterDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userCenterDo) Joins(fields ...field.RelationField) IUserCenterDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userCenterDo) Preload(fields ...field.RelationField) IUserCenterDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userCenterDo) FirstOrInit() (*model.UserCenter, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCenter), nil
	}
}

func (u userCenterDo) FirstOrCreate() (*model.UserCenter, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCenter), nil
	}
}

func (u userCenterDo) FindByPage(offset int, limit int) (result []*model.UserCenter, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userCenterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userCenterDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userCenterDo) Delete(models ...*model.UserCenter) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userCenterDo) withDO(do gen.Dao) *userCenterDo {
	u.DO = *do.(*gen.DO)
	return u
}
